### ISSUE TITLE
Social: Graphics for Ticket Sales

### ISSUE THREAD

**Issue by KGorr** [MozillaFoundation/mozfest-design-2018#10]
It would be great if we could duplicate the [MozFest Call for Proposals graphics](https://github.com/MozillaFoundation/mozfest-design-2018/issues/4) and adjust for ticket sales. 

Suggested Phrases:
"MozFest Tickets Are Now Available"
"Join Me At MozFest 2018!"
"Data Done Right: MozFest 2018"

Would include in Ticket Sales Communication Cheat Sheet: https://docs.google.com/document/d/1jTn78OyXn0SiMrz26CWXzeh-NbQQ7aiFAwV-GhuWFtA/edit?usp=sharing

Will be distributing this cheat sheet end of July/early August.

Facebook/Twitter platforms preferred

**Comment by KGorr** [comment]
@Saallen @KevZawacki @caltrider - thoughts on the suggested phrases above?

**Comment by KevZawacki** [comment]
Hi @KGorr, 

I'd change the second to "Join Us At MozFest 2018!"

Otherwise, right on 👍

**Comment by caltrider** [comment]
@KGorr I think you could lose the work "are" in the first one: MozFest Tickets Now Available"

Otherwise, looks good to me.

**Comment by sabrinang** [comment]
Great, final copy is:
"MozFest Tickets Now Available"
"Join Us At MozFest 2018!"
"Data Done Right: MozFest 2018"

**Comment by sabrinang** [comment]
@KGorr Can you review these ticket graphics for social? https://redpen.io/p/nyb128bb0ec90417aa

**Comment by KGorr** [comment]
@sabrinang - I love all of them!

**Comment by sabrinang** [comment]
Thanks for the review @KGorr 

I have exported the .jpgs social assets on google drive here: https://drive.google.com/open?id=1YBdmf0wKYs3bvRoyN-IDyLsYs_N_-R83

Referring to https://github.com/mozilla/mozillafestival.org/issues/992 I have included `MozFest Tickets Now Available` heading on l10n versions as well (Swahili isn't translated).

**Comment by KGorr** [comment]
@sabrinang - Thank you!
