### ISSUE TITLE
Create MozFest Slide Template

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2018#101]
Create a simple Mozfest google slide template that program staff can use for presentations. Doesn't need to be elaborate, just needs MozFest branding.

**Comment by gideonthomas** [comment]
@natalieworth do you think this is something you can do or would you rather Sabrina take this on?

**Comment by sabrinang** [comment]
https://docs.google.com/presentation/d/1rGjD1cNQ1QOzsGH1dqMePbHo65gFmCoDMex269YpwUQ/edit?usp=sharing

Slide is View only so template can't be overwritten. Please go to _**File > Make a copy...**_ to use.

Lots of options when you select `New Slide with Layout`:
![image](https://user-images.githubusercontent.com/2492510/47249355-5ef70600-d3c7-11e8-87dc-c3ff330fe6fa.png)

**Comment by Saallen** [comment]
Looks incredible- thanks @sabrinang 
@gideonthomas can we keep this issue open?

Looping in @KevZawacki @marcwalsh @ldecoursy @LindseyFrost  and @sarahWat as people who will use these slides

**Comment by sabrinang** [comment]
## Post Mozfest Documentation

Slide template was spotted on the large screen on the Mozilla Zone floor:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/2492510/48280766-71ce8a80-e409-11e8-86f3-4803c059a88b.png">

Link to the slides used here: https://docs.google.com/presentation/d/1ft_osKn-x39QxNhDENBMMY6M58DUONBjBQ8FNkNDoeU/edit#slide=id.g45434e9a7c_0_3
