### ISSUE TITLE
Create Dialogues and Debates logo for Guidebook

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2018#102]
We're looking to place Dialogues and Debates on the left nav bar of Guidebook, however we need an icon. 

@gideonthomas - would a designer have the bandwidth to design an icon we can use for this?

**Comment by sabrinang** [comment]
I can work on this guidebook icon (related to other request https://github.com/MozillaFoundation/mozfest-design-2018/issues/103)

**Comment by sabrinang** [comment]
<img width="151" alt="mozilla-festival-2018_schedule-app_dialogues-debates 2x" src="https://user-images.githubusercontent.com/2492510/47321149-a7e9cd00-d608-11e8-83cc-9d638d08e9a4.png">
Download PNG here on google drive: https://drive.google.com/file/d/1fUFtlQBU2BNF9UXzQs6-y0b0AlVChzm8/view?usp=sharing

**Comment by marcwalsh** [comment]
Thanks for the speediness of getting this done Sabrina! :)

**Comment by marcwalsh** [comment]
Uploaded to Guidebook! Closing ticket :) Thanks again
