### ISSUE TITLE
Science Fair Icon for Guidebook

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#103]
Matt requested via slack:

_Stephanie and I are working together to get the Science Fair uploaded to guidebook. To make it a custom list available on the app we need a logo._

**Comment by sabrinang** [comment]
I aligned with the science fair icon in the printed guide: 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/2492510/47321084-69541280-d608-11e8-81dd-fd854b32c4e1.png">
<img width="151" alt="mozilla-festival-2018_schedule-app_science-fair 2x" src="https://user-images.githubusercontent.com/2492510/47321091-6f49f380-d608-11e8-96ae-a6e5a6708057.png">

Download PNG here on google drive: https://drive.google.com/file/d/1fWJC-60Yipp50A7DHVICe6ecH25gNN0x/view?usp=sharing

**Comment by marcwalsh** [comment]
Uploaded to Guidebook! Thanks Sabrina :)
