### ISSUE TITLE
Update Tito Banner Image

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#104]
Sarah requested via slack

_I was updating another ticket and by mistake updated this page. I don't have correct photo. If either of you edited the banner can you update it to the correct dimensions when you get a chance? https://ti.to/Mozilla/mozilla-festival-2018_

**Comment by sabrinang** [comment]
@Saallen Instead of the stretched photo, we can use a graphic: 
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/2492510/47321853-e6808700-d60a-11e8-8db0-c9f4764bd70c.png">

Images (original and retina versions) exported on gdrive here: https://drive.google.com/drive/folders/1fmYinPXm57xXbwrDztQvsCQZ82WbuaSl?usp=sharing

/cc @gideonthomas

**Comment by marcwalsh** [comment]
@sabrinang - I tried to upload this but I was getting a warning that it wasn't the correct size and for some reason illustrator isn't liking me resizing!

Banner image should be a JPEG, GIF or PNG, 900×265px (@1x) or 1800×530px (@2x)

Would you be able to adjust this please?

**Comment by sabrinang** [comment]
@marcwalsh I exported the banner in the specified dimensions as PNGs here: https://drive.google.com/drive/folders/1fmYinPXm57xXbwrDztQvsCQZ82WbuaSl?usp=sharing
