### ISSUE TITLE
Social: Template for Experiences

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#14]
Create a graphic that will accompany social media posts that has a border or template that frames the experiences images.

Experiences:
Queering MozFest
Gaming MozFest
Art + Data - https://issuu.com/mozfest/docs/mozillafestival_art_data_online_cat

**Copy:** TBD
**Date to be Posted:**  TBD
**Platforms:** Twitter

**Comment by sabrinang** [comment]
These are the experiences sticker designs, handing this off to another designer to make this into a template, export different dimensions or you can use it as is etc.

redpen: https://redpen.io/p/vj7b8fce74bbb84ffd
gdrive folder files: https://drive.google.com/open?id=17Y7sriIR_d73jB4KO7xT2Xg158tphuL0
<img width="507" alt="image" src="https://user-images.githubusercontent.com/2492510/46446319-82b41e00-c730-11e8-9fb1-8dfdfd536473.png">

**Comment by zee-moz** [comment]
@sabrinang these look great! 👍

**Comment by beccaklam** [comment]
@sabrinang Just to clarify, for this task, is it to create a template for quotes, images?

**Comment by beccaklam** [comment]
@zee-moz Added these to the mozfest social photoshop file: https://drive.google.com/open?id=1ERXyx6NPTq3gbo1_SeeIluATDsGXk6sl
