### ISSUE TITLE
Social: Graphics for each Space

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#15]
Create a graphic for social media of each of the 6 spaces at MozFest. https://mozillafestival.org/spaces

- Decentralisation
- Digital Inclusion
- Openness
- Privacy and Security
- Web Literacy
- Youth Zone

**Copy:** TBD
**Date to be Posted:**  TBD
**Platforms:** Twitter 

____________________
### Reference from Previous Years:

2017 issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/62

**Comment by zee-moz** [comment]
let's wait on this for now

**Comment by sabrinang** [comment]
These are similar space design headers used in guidebook, handing this off to another design to include text, template, export different dimensions or you can use as is etc.

redpen: https://redpen.io/p/vj7b8fce74bbb84ffd
gdrive folder files: https://drive.google.com/open?id=17Y7sriIR_d73jB4KO7xT2Xg158tphuL0
![image](https://user-images.githubusercontent.com/2492510/46445891-ee48bc00-c72d-11e8-8aed-cdad26b04184.png)

**Comment by zee-moz** [comment]
@sabrinang love these designs. my only bit of feedback is that the illustrations are hard to see, and they get a bit lost from a distance. Anyway to increase the contrast or line weight on the illustrations? If not, it's OK! they are lovely either way 😃

**Comment by beccaklam** [comment]
@zee-moz Here are the designs with larger and darker illustrations: https://drive.google.com/drive/folders/1QdFRhHhj1Y21llZimn1AEh8V_7Iea96L?usp=sharing
Let me know if these work!

**Comment by beccaklam** [comment]
Closing for now, please reopen if needed!
