### ISSUE TITLE
Social: Graphic for Theme

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#17]
Create a graphic for social media of the Data Done Right theme this year. 

**l10n copy issue:** https://github.com/mozilla/mozillafestival.org/issues/923
**Date to be Posted:**  TBD
**Platforms:** Twitter

**Comment by Saallen** [comment]
cc in @zee-moz and @marcwalsh for info only

**Comment by sabrinang** [comment]
These are some theme tagline designs you can use as is, handing this off to another designer to generate more from the tagline files, export different dimensions or include copy etc. 

tagline lockup files: https://drive.google.com/drive/u/1/folders/1fK-REXx9vEUAvfj82yeFLdzvq3TNIT9t

redpen: https://redpen.io/p/vj7b8fce74bbb84ffd
gdrive folder files: https://drive.google.com/open?id=17Y7sriIR_d73jB4KO7xT2Xg158tphuL0
<img width="500" alt="image" src="https://user-images.githubusercontent.com/2492510/46445966-61523280-c72e-11e8-8d31-d6802c14af2a.png">

**Comment by zee-moz** [comment]
Awesome! love these @sabrinang 🥇

**Comment by beccaklam** [comment]
Given the tight timeline and the fact that sabrina has actually already created some graphics for this already, I'm going to close this ticket for now. Please reopen if need.
