### ISSUE TITLE
Social: Dialogue & Debates Speaker Profile Cards

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#19]
Create profile cards for each Dialogue & Debates speaker or a template that can be used for social media promotion.

List of speakers TBD

____________________
### Reference from Previous Years:

2017 issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/55

**Comment by Saallen** [comment]
cc in @zee-moz and @marcwalsh for info only

**Comment by zee-moz** [comment]
@KevZawacki how would you like to promote speakers on social, since there are more panels this year, and less individual speakers?

**Comment by KevZawacki** [comment]
@zee-moz Good question! How about:

-- For individual talks, let's put the speaker's name + headshot on the profile card

-- For panels, let's put the panel name + speakers headshots on the card (no need to include their names; I'll include them in the tweet copy)

What do you think?

**Comment by sabrinang** [comment]
Note: good to align D&D social with visuals seen in festival guide section https://github.com/MozillaFoundation/mozfest-design-2018/issues/73

**Comment by zee-moz** [comment]
@sabrinang great! is there anything I can do to help on this?  😸

**Comment by beccaklam** [comment]
All of the profile cards and the working files can be found here: https://drive.google.com/drive/folders/16fnNBtj8r2bHJxCPih42Nyx6a6stwBvM?usp=sharing

**Comment by beccaklam** [comment]
Closing for now, please reopen if needed!
