### ISSUE TITLE
Social: Space Wrangler Profile Cards

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#20]
Create profile cards for space wranglers or a template that can be used for social media promotion. These cards can perhaps be by space instead of individuals.

https://mozillafestival.org/team/wranglers

Wrangler bio spreadsheet: https://docs.google.com/spreadsheets/d/1eCbNq1dK2xG5DtYmoMysCGlXb4cf7dlGzIt0u7QnN0g/edit#gid=0

_____________________
It may be helpful to reference Dialogue & Debates Profile Cards issue https://github.com/MozillaFoundation/mozfest-design-2018/issues/19

**Comment by Saallen** [comment]
cc in @zee-moz and @marcwalsh for info only

**Comment by zee-moz** [comment]
let's not do this one right now-- will reopen if we have time.
