### ISSUE TITLE
Social: Template for Generic Photo/Border Image Treatment

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#22]
Create templates for images that can be used for sharing on social.

____________________
### Reference from Previous Years:

2017 issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/59

**Comment by Saallen** [comment]
cc in @zee-moz and @marcwalsh for info only

**Comment by zee-moz** [comment]
@sabrinang  go ahead with this one, should be super quick!

**Comment by sabrinang** [comment]
This template is here on slides: https://docs.google.com/presentation/d/1CO_QNsCaxyz34jDScR59EKoRy972heCRWbDCSyBn16E/edit#slide=id.g4393812be4_5_121
The dimensions are twice as large so when you export the resolution is good on retina. Handing this off to another designer to create more photo overlays + borders etc.

redpen: https://redpen.io/p/vj7b8fce74bbb84ffd
gdrive folder files: https://drive.google.com/open?id=17Y7sriIR_d73jB4KO7xT2Xg158tphuL0
![image](https://user-images.githubusercontent.com/2492510/46446236-091c3000-c730-11e8-99aa-ae2ba4be31aa.png)

**Comment by sabrinang** [comment]
Note: Zannah prefers templates as psd files

**Comment by zee-moz** [comment]
@sabrinang @beccaklam These are the two I need as psd files Would be nice to have layers so it's easy to put a background on the logo if the photo is too dark in that corner. 
Thanks! :)

**Comment by beccaklam** [comment]
Hi @zee-moz what social accounts will you be sharing on? Just so I know what dimensions to build the templates at. Thanks!

**Comment by zee-moz** [comment]
twitter and instagram. thanks!

**Comment by beccaklam** [comment]
@zee-moz I made a psd file with the templates and made layers where you can add images or text. You can download it here: https://drive.google.com/file/d/1ERXyx6NPTq3gbo1_SeeIluATDsGXk6sl/view?usp=sharing Let me know if it works for you!
