### ISSUE TITLE
Social: Short Promotional Video

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#23]
We have videos under a minute that can be used short promotional videos:

MozFest Social 2017: https://vimeo.com/264062401
MozFest House 2017: https://vimeo.com/264061565
MozFest Science Fair 2017: https://vimeo.com/264061848

We may not need to trim videos ourselves this year.
____________________
### Reference from Previous Years:

2017 issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/61

**Comment by sabrinang** [comment]
@KGorr All these videos are under a minute:
MozFest Social 2017: https://vimeo.com/264062401
MozFest House 2017: https://vimeo.com/264061565
MozFest Science Fair 2017: https://vimeo.com/264061848

Would you need anything else for short promotional videos or can we close this issue?

**Comment by KGorr** [comment]
@sabrinang - I think all of these will work well. Thanks!
