### ISSUE TITLE
Social: Update Profile & Cover Photos

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#24]
Refresh MozFest's social media properties by updating profile photos and header cover photos.

Examples:

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/2492510/43172587-cabc0d24-8f64-11e8-8314-f5f80e78bb1d.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/2492510/43172551-aa750d04-8f64-11e8-8e8a-798b11694fed.png">
<img width="999" alt="image" src="https://user-images.githubusercontent.com/2492510/43172615-f0c76504-8f64-11e8-81e3-0a2d2511da4d.png">

These cover photos can be reused as generic email or form header graphics as well.

____________________
### Reference from Previous Years:

2017 issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/19

**Comment by Saallen** [comment]
Adding in @zee-moz @marcwalsh for info only at this time

**Comment by zee-moz** [comment]
@Saallen we are using "Data Done Right" here as the festival tagline, is that correct?  Do we use "Where Web Meets World" anywhere? 

cc: @caltrider 

@sabrinang pls go ahead with the confirmed tagline.

**Comment by sabrinang** [comment]
Please review this cover design and if you want to include the dates or not, background colour preference and the tagline is incorporated subtly in the background similar to stage design. 

redpen: https://redpen.io/p/vj7b8fce74bbb84ffd
drive folder files: https://drive.google.com/drive/u/1/folders/17C0TDzZWGzs3X2EdYoDYOJzDtrwcaV9N

<img width="381" alt="image" src="https://user-images.githubusercontent.com/2492510/46446187-bcd0f000-c72f-11e8-8c0c-f77615b81fe8.png">

**Comment by zee-moz** [comment]
@sabrinang these are awesome. I personally like the more aqua one, just a bit more contrast. 
Dates are good! thanks so much 💯
