### ISSUE TITLE
Branding: Colour

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#27]
### Description:
Determine colour palette used for this year's MozFest. Align with Mozilla wide palette or Foundation site palette or adapt last year's palette. Include a variety that works with people who have colour vision deficiencies.  

**Format**
Include .ase file and document in style guide.

### Previous Applications
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2492510/30232413-d10be250-94a4-11e7-8bf3-811211e78ce3.png">

### Reference from Last Year: 
Swatch file (.ase): https://drive.google.com/open?id=0B4Q8pzCpDS_eZWdNMlBkVVNoYkE
Style guide files (.ai/.pdf) updated to include pantone: https://drive.google.com/open?id=0B4Q8pzCpDS_eSjZ1QTVGM2lRaGM
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/49

**Comment by sabrinang** [comment]
Revised this palette (cool tone) for 2018. Black and white will be prominent throughout the palette along with the primary tones (tints and shades may be used):
![mozilla-festival-2018_colours](https://user-images.githubusercontent.com/2492510/44433454-27044b80-a55b-11e8-9bb0-88d4bbc2139d.jpg)

From an accessibility standpoint, we would use the lime green as an accent colour but not for any main wayfinding as it is very close to yellow and we have selected a range of colours overall that appears different across the spectrum of vision abilities. We will be using patterns with problematic pairs if we are using it for wayfinding without text or icons.
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/2492510/44433668-38018c80-a55c-11e8-9aa0-341d2afcd814.png">

@makikoumezawa and I have been using http://www.color-hex.com for monochromatic reference.

CC Library for colour will be linked here: https://adobe.ly/2BtobD3
.ai file in gdrive folder here: https://drive.google.com/file/d/1bjBPAAPL4rqNClA3XBw1LuNgMabe4_OR/view?usp=sharing

We need to colour match Pantones for print and usage will be documented in style guide.

**Comment by taisdesouzalessa** [comment]
Love the fact accessibility is being considered and also seeing examples on how people perceive the colors. I think the mood of MozFest is always energetic and I think the choice of colors above reflects it very well.

**Comment by sabrinang** [comment]
An overview of the tints, shades and gradient variations we iterated upon and documented. We will use a warm palette for MozFest House and a cool palette for MozFest Weekend to help distinguish the overarching brand as we explored last year. The thematic spaces will use corresponding colours to assist in wayfinding again. Black and white will be prominent in the design and lime green can accompany both spaces as a highlight if needed. I used the Colour Bridge Uncoated PANTONE Plus Series book to match the colours. 

![image](https://user-images.githubusercontent.com/2492510/45133346-7f397100-b149-11e8-9d31-f0b93aef6bb6.png)

Google Drive folder (.ai swatch file and .ai overview file included) : https://drive.google.com/open?id=1kvphhKYnl2KCDlG2GH90f437_741K2Nm

![mozilla-festival-2018_colours-overview 2x](https://user-images.githubusercontent.com/2492510/45132720-de49b680-b146-11e8-952d-eb54ea95ab76.jpg)

**Comment by sabrinang** [comment]
Documented in [WIP extended style guide](https://docs.google.com/presentation/d/1Otj7kAwG3EyQd_Ya1K7jigJ0YLRMMiCbuq_L4QCbM1M/edit?usp=sharing) - closing issue.

**Comment by sabrinang** [comment]
Update: I adjusted the purple (web/print) as it printed and appeared to similar to blue after some applications and made the green (web) slightly more yellow so it differentiated from cyan a bit more.
![image](https://user-images.githubusercontent.com/2492510/45514903-9258cc00-b75b-11e8-8751-c97d8f4e1790.png)
