### ISSUE TITLE
Branding: Experience Alignment

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#30]
### Description:
This year we are introducing _Queering MozFest_, _Gaming MozFest_, _Art & Data_(renamed) as an experiences at MozFest.

### Question and Previous Applications:
Previously we had "Curated Programming" or "Tracks" throughout the festival's spaces instead which were: journalism, open policy + advocacy and youth-led but we did not need visuals to signal these. Do we need anything visual for these experiences across festival spaces this year? Curious if they show up in design assets? I would use something typographic since it changes every year. Example:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/2492510/43810873-ad8f661e-9a6e-11e8-95b3-01e68cca171a.png">

What about aligning experiences that have visuals throughout the spaces such as artist open studios? How do we coordinate and align here? Last year they did their own thing:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/2492510/43230932-09458d80-901f-11e8-8cca-8474dfd907e5.png">

### Reference
More information on this can be found on the medium post announcement https://medium.com/mozilla-festival/oh-deer-mozfest-goes-queer-444711319d48 or experiences section https://mozillafestival.org/spaces#Queering-MozFest

**Comment by sabrinang** [comment]
@Saallen any thoughts on this topic?

**Comment by Saallen** [comment]
@sabrinang I think creating alignment between them all through visual branding is great but I would advise talking to each one to see what their perspective is. 
Queering MozFest and Art + Data (not &) will be working with artists and might appreciate a distinctive link- Gaming mozfest will be presenting itself as a "organisation" that is asking you to participate in their game and so might want something different to others.

**Comment by sabrinang** [comment]
### Experience Alignment Overview

**Related Gaming MozFest Issues:**
Registration Table Area Design & Signs: https://github.com/MozillaFoundation/mozfest-design-2018/issues/44
Table Cloth: https://github.com/MozillaFoundation/mozfest-design-2018/issues/43
Name Card: https://github.com/MozillaFoundation/mozfest-design-2018/issues/58

We can place the gaming table near the youth/accessibility/press table and align the wayfinding materials (floor sign and table cloth) if possible. I'm not sure what gaming is planning for name card icebreakers but Abby has mentioned there might be something tied in.

![experience-alignment-concept_gaming 2x](https://user-images.githubusercontent.com/2492510/45636911-f6caa280-ba5d-11e8-8b87-815e62db0854.jpg)

__________________
**Related Art + Data / Queering MozFest Issues:**
Floor Banner: https://github.com/MozillaFoundation/mozfest-design-2018/issues/41

Since these experiences will be located on floors they will have floor banners. 

![experience-alignment-concept_artdata-queering 2x](https://user-images.githubusercontent.com/2492510/45636910-f6caa280-ba5d-11e8-910f-caed1d8ce7ed.jpg)

__________________
**Related Experience Issues for all:**
Floor stickers: https://github.com/MozillaFoundation/mozfest-design-2018/issues/48
Festival Guide: https://github.com/MozillaFoundation/mozfest-design-2018/issues/73
Motion Graphic: https://github.com/MozillaFoundation/mozfest-design-2018/issues/36
Hackable Signs: https://github.com/MozillaFoundation/mozfest-design-2018/issues/51

We can include floor stickers for each experience. A spread for experiences will be in the festival guide and a screen for experiences could be included in the motion graphic. I'm unsure if experiences would need specific hackable signs but we can make a border style for all MozFest experiences. 

![experience-alignment-concept_all 2x](https://user-images.githubusercontent.com/2492510/45636909-f6caa280-ba5d-11e8-8d0d-421b42796eec.jpg)

**Comment by gideonthomas** [comment]
@Saallen - could you confirm what kind of physical assets/wayfinding assets we need for each experience? For example, do we need hackable signs for Gaming MozFest, do we need banners for Queering Mozfest, etc.

@Saallen, the discourse between experience folk and us is slowing down production of these assets. Can we design these assets and let them figure out what they want to use - this will allow for proper brand alignment. Otherwise, are you able to appoint a person who has the bandwidth to facilitate conversations with the experience wranglers to figure out what wayfinding assets they need and if they have certain preferences for design...and they need to provide this info within a certain deadline.

**Comment by Saallen** [comment]
@gideonthomas yes-
Lets move without them-  I wil chase but lets go with basic requirements and if they have additional pieces then we see if we have the bandwidth

We should design for 
- [ ] Banner
- [ ] Tracked table cloth
- [ ] floor stickers

**Comment by gideonthomas** [comment]
Thanks @Saallen! @sabrinang, does that work?

**Comment by gideonthomas** [comment]
@marcwalsh to mention how many tablecloths we can produce based on cost.

**Comment by gideonthomas** [comment]
@sabrinang, let's create those three assets for the experiences (Banner, table cloth, and floor stickers) whether they use them or not. If they haven't provided any other design requirements, let's just move with these three.

We don't need hackable signs for the three experiences.

Just a quick note - it is unlikely that Gaming Mozfest will be at the location you show in the map above. Location is TBD. Does it affect any of your work?

**Comment by marcwalsh** [comment]
@sabrinang  We won't be having Gaming MozFest in the registration area.  If possible can we make these generic to reuse?

For experiences I spoke to @Saallen and we should be treating them the same as a space but without the totem.

**Comment by sabrinang** [comment]
![experience-overview](https://user-images.githubusercontent.com/2492510/47250847-0f700480-d3de-11e8-9c64-31f10906dbfd.png)

Experience branding will appear across the festival in lime green/blue with text and MozFest cubes highlighted in various design assets:
- floor signs #46 
- floor maps #42 
- floor banners #41 
- floor stickers #48 
- swag stickers #57 
- festival guide spread #73 
- hackable signage #50 #51 
- social #14
