### ISSUE TITLE
Lighting: Wall Projection (Gobo Design)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#34]
### Description:
On level 4's Big Space, we will have a gobo light projection design on to the wall. It can include variations in colour and motion.

### Previous Applications
![mozfest-logo-wall-projection small](https://cloud.githubusercontent.com/assets/2492510/20079232/a1f511b8-a4f8-11e6-8166-2813613cbcb2.gif)
![mozfest-lighting](https://user-images.githubusercontent.com/2492510/33042747-c7360a4e-cdf7-11e7-8810-a52cf93ee7a0.gif)

### Related Issues:
https://github.com/MozillaFoundation/mozfest-design-2018/issues/33

### Reference from Last Year: 
Github issue 2016: https://github.com/MozillaFoundation/Mozfest2016_production/issues/188#issuecomment-258993050
Github issue 2017: https://github.com/MozillaFoundation/mozfest-design-2017/issues/11

**Comment by sabrinang** [comment]
@marcwalsh Let's go with cog logo design again. SVG on gdrive here: https://drive.google.com/file/d/1V4mq9fpyepH75vcaUZ8kRRszYT0-wOYw/view

**Comment by marcwalsh** [comment]
Sent to Whitelight to create! Thanks all - I'll close this and reopen if there's any changes required.

**Comment by sabrinang** [comment]
## Post MozFest Documentation
The gobo gear design was in white and was animated with a slow clockwise rotation. I mentioned to the lighting designer Luke to scale it down so the edges aren't to close to the round windows (the bottom was still a bit close). I noticed after it was positioned higher than the year before so we can note to make it lower so it is more in frame for close up photos for next year.

![dsc02273](https://user-images.githubusercontent.com/2492510/48504951-d4090000-e7fa-11e8-8871-47b872e846a7.jpg)
![dsc02303](https://user-images.githubusercontent.com/2492510/48504975-de2afe80-e7fa-11e8-89ea-e29f5a807528.jpg)
