### ISSUE TITLE
Stage: Main and Secondary Printed Backdrops

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#35]
### Description:
There are two stages:
- the Main Stage on Level 4 
- the Secondary _(Dialogue and Debates Stage)_ in the Walker Space on Level 0

These had a printed backdrop, two screens and one comfort monitor.

#### Things to Consider
- Both stages should have related designs to each other
- Talks will be streamed and recorded from Secondary stage
- This is a good opportunity to think about how branding shows up in video frames and the design should not be too busy and consider reducing contrast of tagline to be more subtle.
- Stages have artificial lights directed on them (Walker room will be artificially lit because there are no windows or natural light)
- MozFest Wordmark and Tagline should be included

#### Last year's dimensions
**Format:** High Res 100% (Actual Size) image size either PDF or EPS for each image.
**Size:** 4800mm x 2400mm
**Bleed:** 100mm bleed

### Reference from Last Year: 
Floor 0 - Print Files (.pdf / .eps): https://drive.google.com/open?id=0B4Q8pzCpDS_eLXFOSnQ2bEZwWHM
Floor 4 - Print Files (.pdf/ .eps): https://drive.google.com/open?id=0B4Q8pzCpDS_eYUY4SmxuSmxFY0E
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/25

### Previous Application

<img width="933" alt="screen shot 2017-10-17 at 7 14 59 pm" src="https://user-images.githubusercontent.com/2492510/31704000-2de496e4-b394-11e7-9ff1-d46dca9a6dbc.png">

![mozilla-festival-2017-128](https://user-images.githubusercontent.com/2492510/33223779-d987474e-d117-11e7-9518-85b3b8ceccdd.jpg)
Scale of last year was quite a bit smaller than the year before and it was set up from the ground (not propped up) and stages were switched. Please include installation instructions and preferences (design check list and issue).

**Comment by sabrinang** [comment]
After chatting with Marc and @gideonthomas, I got more stage details:

- Print deadline is October 1.
- New dimensions are 6m x 3m (WxH)

@marcwalsh What bleeds does the printer need for the stage? If there is a specific template output please let me know

**Comment by sabrinang** [comment]
@marcwalsh informed me stage vendors want a bleed of 100mm around the edges

**Comment by marcwalsh** [comment]
We’ve updated the sizing of the stage backdrops to reduce costs and to ensure none of the content is obscured by the large monitors.

Floor 4 is now 400cm x 300cm (W x H)
Floor 0 to 500cm x 300cm (W x H)

**Comment by sabrinang** [comment]
**Stage design**
I've designed level 0 stage to be blue featuring the gear logo in the center and the wordmark in the upper corner. For the level 4 stage, the lockup is featured in the centre with subtle data done right taglines in the background texture. 

@Saallen Please review these designs in redpen here: https://redpen.io/ctdc6e0b837c1893f6
![image](https://user-images.githubusercontent.com/2492510/46327211-5031e600-c5b5-11e8-8ec9-7a519e8f39d8.png)

**Comment by Saallen** [comment]
Love these @sabrinang - very happy with them

**Comment by marcwalsh** [comment]
@sabrinang can you post the link to the PDF of these files please?

**Comment by sabrinang** [comment]
@marcwalsh PDFs exported on google drive here: https://drive.google.com/open?id=16e0lZFeb_ub4qo4rnxXfNKRrhTwieqEf

Since there is a 1" bleed limit in Illustrator, I made the files larger to accommodate the 10cm required bleed so the file sizes for Level 0 Stage is 520cmx320cm and Level 4 Stage is 420cmx320cm (no trim marks are exported). Let me know if this works for the printer.

**Comment by marcwalsh** [comment]
Sent to print on Oct 4th.

Closing ticket and will reopen if the printer comes back with comments.

**Comment by sabrinang** [comment]
## Post MozFest Documentation 

**Main Stage**
![45650704841_a3c936dac0_z](https://user-images.githubusercontent.com/2492510/48505593-3f070680-e7fc-11e8-88a5-111755985d85.jpg)
![45650703181_2393b0f726_z](https://user-images.githubusercontent.com/2492510/48505597-43332400-e7fc-11e8-89b3-e41a9ec6d412.jpg)
![dsc02330](https://user-images.githubusercontent.com/2492510/48505693-855c6580-e7fc-11e8-94d0-08371086a92b.jpg)

**Dialogue & Debates Stage**
![20180928-mozfest-sunday-79](https://user-images.githubusercontent.com/2492510/48505297-8b9e1200-e7fb-11e8-83ca-0be130ed798b.jpg)
![30710101167_6b35cbb577_z](https://user-images.githubusercontent.com/2492510/48505403-d9b31580-e7fb-11e8-8cc0-f5db87a2384a.jpg)
![dsc02348](https://user-images.githubusercontent.com/2492510/48505435-ea638b80-e7fb-11e8-8a4e-a087f177ed97.jpg)

The stages are taller than last year's which helps frame the speaker better in photographs. The bottom edge sits a bit beneath the stage itself. I liked having the annual MozFest lockup or logo be the predominant focus of the stage design rather than the tagline as it is more recognizable if we share it. The colours turned out nice and the D&D stage had a lighting colour wash above it. The screens for the D&D stage were positioned a bit close which made the stage area feel tighter.
