### ISSUE TITLE
Screen: Motion Graphic Video

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#36]
### Description:
This video will be on loop playing motion graphics on screens around the building displaying festival information.

Content TBD such as:
* MozFest 2018 Logo
* Tagline
* Experiences (Queering MozFest, Gaming MozFest, Art + Data)
* Dialogue & Debates (times, talk, speaker, location)
* #mozhelp + info desk
* Social Media (hashtags, handles, platforms, pulse)
* WiFi (network, password)
* Schedule App
* Food (lunch, coffee)
* Internet Health Report
* Participation Guideline (email, phone)
* Sponsorship Slide (Presenting festival partner, Science Fair partner, Closing party partner and Youth Zone partner)
* Learn about Moz’s Fellowship and Awards programs on Level 1 (green slide)

### Reference from Last Year: 
Google Drive File: https://drive.google.com/drive/folders/0B20-0lpP23c0S1BRZ25KTllHanc?usp=sharing
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/13

**Comment by sabrinang** [comment]
Note: Sabrina to reach out to Tim to coordinate mozilla 20th anniversary video clip

**Comment by gideonthomas** [comment]
@Saallen to assign to someone that will be responsible for content and specifying the order of the content by Friday, Sep 7.

**Comment by Saallen** [comment]
Assigned @marcwalsh to help w content here. He will update asap

**Comment by Saallen** [comment]
Content doc out-of-date: ~I created a [content document](https://docs.google.com/document/d/1RKDXZuhZIC-ZQlUaaRTpkITQYrsh333IfA3M_iDDyAU/edit#)~

Requesting updates from 
- [ ]  @marcwalsh 
- [x] @consuelamckenzie 
 
Stephanie Rowe will coordinate this content and update the sheet
- [ ] Confirming all requested content has been added

**Comment by consuelamckenzie** [comment]
@Saallen added content yesterday.

**Comment by marcwalsh** [comment]
@gideonthomas @Saallen I'm awaiting confirmation from Ravensbourne about the SSID for the network at Rave.

**Comment by sabrinang** [comment]
**Sponsorship Update:**

We'll need to include a sponsorship slide this year for the Presenting festival partner, Science Fair partner, Closing party partner and Youth Zone partner. It will display their logo along their partner role at MozFest this year.

**Comment by Saallen** [comment]
@marcwalsh any updates for us here?

**Comment by marcwalsh** [comment]
@gideonthomas sorry this was due from Ravensbourne today. They are meeting with the IT dept there tomorrow (Thurs) so we should have it confirmed by then.

**Comment by consuelamckenzie** [comment]
@gideonthomas confirmed from Ravensbourne;
SSID 'MozFest2018'
password Mozfest18

**Comment by gideonthomas** [comment]
@consuelamckenzie, @marcwalsh, or @Saallen just to confirm the password - it is "Mozfest18" with a capital 'M' and a lowercase 'f'?

**Comment by consuelamckenzie** [comment]
@gideonthomas yes, to confirm password is 'Mozfest18'

**Comment by gideonthomas** [comment]
cc @xmatthewx

**Comment by natalieworth** [comment]
From Matthew:

 > for Fellow/Awards, can we do a simple screen slide that says something like “Investing in Leaders for Internet Health // Visit the Fellowships and Awards booth on Level 1 to learn more.”

**Comment by annmarie123** [comment]
@natalieworth that copy for the fellows/awards is just fine.

**Comment by Saallen** [comment]
The fellow will be based on level one in the Mozilla zone

**Comment by natalieworth** [comment]
Have a rough [draft here](https://drive.google.com/drive/folders/12i7L_sZb9nR1L6LPFAxq5wfC9KlpOM5_?usp=sharing)!   


Still have to add:
- [x] Fellows slide
- [x]  Icons from wayfinding/ name tags
- [ ] Subtle Animations

cc @Saallen @sabrinang @gideonthomas @xmatthewx

**Comment by natalieworth** [comment]
I think it's still uploading—so maybe about another 30 mins before the link is viewable. ^

**Comment by Saallen** [comment]
Im getting a 404 for that link Nat
Sarah Allen

Director, Events and training
Executive Director, MozFest
*Mozilla Foundation*

Find out more about MozFest <https://mozillafestival.org/> and follow the
conversation on twitter <https://twitter.com/mozillafestival?lang=en-gb>

**Comment by gideonthomas** [comment]
@Saallen the link should now be working.

**Comment by gideonthomas** [comment]
@natalieworth would you be able to remove Nani Jansen from the D&D section -- she had to cancel. The Media Partner should be after the Science Fair Partner.

**Comment by natalieworth** [comment]
Made those changes. Just have to add subtle animations if time (after completing the Science Fair slides tmrw). 

V2 will be in same folder (once it's uploaded). I made the file size a bit smaller for draft export so hopefully it loads to the drive a bit quicker :)
https://drive.google.com/drive/u/0/folders/12i7L_sZb9nR1L6LPFAxq5wfC9KlpOM5_

cc @Saallen @sabrinang @gideonthomas

**Comment by marcwalsh** [comment]
@natalieworth - the link isn't working for me, could you resent please?

**Comment by natalieworth** [comment]
@marcwalsh Try this one: https://drive.google.com/file/d/1tffYUgudXB0xKxlSUptRheRd5-DIe1fi/view?usp=sharing

Gideon had one update about the D&D content, but will export the final video EOD to the drive. 

cc @sabrinang @marcwalsh @gideonthomas @Saallen

**Comment by natalieworth** [comment]
High-res V3 version of final content (before background effects/ animation)[ is here.](https://drive.google.com/file/d/12shdh5nIWVdk7RyFgGB77tGPTLPOnlGg/view?usp=sharing)

I've got a few other P1's, but if I'm able to add some effects tonight—I'll place a V4 in the doc.

cc @sabrinang @marcwalsh @gideonthomas

**Comment by sabrinang** [comment]
## Post MozFest Documentation
The motion graphic reel was on loop throughout the Ravensbourne mininet screens.

![img_5927](https://user-images.githubusercontent.com/2492510/48511051-6ebd0b00-e80a-11e8-9930-210e17805882.JPG)
![img_5908](https://user-images.githubusercontent.com/2492510/48511060-75e41900-e80a-11e8-8b15-e46fd9a81f31.JPG)
![img_5913](https://user-images.githubusercontent.com/2492510/48507958-27328100-e802-11e8-9867-4826e23eeab2.JPG)
![dsc02367](https://user-images.githubusercontent.com/2492510/48510882-f7877700-e809-11e8-8da4-1082b2c89275.jpg)
![img_5850](https://user-images.githubusercontent.com/2492510/48511074-7ed4ea80-e80a-11e8-9817-c1024047d812.JPG)

A screen or two was down temporarily near the registration but we notified Marc to get it up again.
![dsc02376](https://user-images.githubusercontent.com/2492510/48511458-a082a180-e80b-11e8-9929-84df72e42805.jpg)
