### ISSUE TITLE
Screen: Dialogue & Debates Google Slide Template

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#37]
### Description:
Create slides that come before and after speaker's own slides (intro/outro) with new visuals in various colour. Slides to consider to design:
* Dialogue & Debates Section Intros (Date, Time)
* Individual Speaker Slide (Name, Role, Handle)
* Generic Text slide
* Logo slide
* Tagline slide
* Q&A
* Thank You

TBD that speaker's are providing there own slide content in between.

### Previous Applications
https://github.com/MozillaFoundation/mozfest-design-2017/issues/12#issuecomment-346899703

### Reference from Last Year: 
Google Slide Template: https://docs.google.com/a/mozilla.com/presentation/d/1mpZinScsuF8Lnjfik600ZBnjnGuGHWPt60if543o4B0/edit?usp=sharing
Google Drive Files: https://drive.google.com/drive/folders/0B3b1KWRwjxtoak9EdWtvbzV1dDA
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/12#issuecomment-346899703

**Comment by Saallen** [comment]
cc @KevZawacki what are your preferences here?
should the slide follow the same format as last year?
 as seen here https://docs.google.com/presentation/d/1mpZinScsuF8Lnjfik600ZBnjnGuGHWPt60if543o4B0/edit

**Comment by KevZawacki** [comment]
@Saallen @sabrinang 

Yes, please! I love the 2017 slide design!

Note: We will have far more panels, are far few solo talks, this year. As a result, most of the slides will look like [this one](https://docs.google.com/presentation/d/1mpZinScsuF8Lnjfik600ZBnjnGuGHWPt60if543o4B0/edit#slide=id.g292795bfc0_0_0). We'll want to include the panel titles on those slides, too.

@sabrinang, you can find all that information [here](https://medium.com/mozilla-festival/cryptographers-activists-engineers-speakers-at-mozfest-2018-b4e31e4c648a). Please let me know how I can help.

**Comment by Saallen** [comment]
Great- happy for design team to proceed

**Comment by gideonthomas** [comment]
cc @xmatthewx

**Comment by makikoumezawa** [comment]
@KevZawacki Here are the Dialogues and Debates Google Slides: https://docs.google.com/presentation/d/1KT-76PFRXPuCldcxB_71PwJBUU8LcJoCvPlp22w87VU/edit?usp=sharing

Could you please review them?

You can access the folder including all the png images here: https://drive.google.com/open?id=1fQemQhz1sGmrWGkJmcH6nHs_GpQruo_q

/cc @sabrinang @gideonthomas

**Comment by KevZawacki** [comment]
Hi @makikoumezawa, these are excellent. One change: Nani Jansen had to cancel at the last minute. Can we simply delete slide 14?

And, tagging in @airmoandy.

**Comment by gideonthomas** [comment]
I made the change @KevZawacki, @airmoandy let me know if you need any changes to the format.

**Comment by KevZawacki** [comment]
Hi @gideonthomas, MozFest speaker Renee DiResta has a last-minute change to her talk title. Can we update her slide to read: 

"Renee DiResta: Atonement and the Internet’s Original Sin"

**Comment by makikoumezawa** [comment]
@KevZawacki I've changed Renee's talk title on google slides. Does Mitchell Baker have a title for her talk? I've noticed she's the only one without a title. 

/cc @gideonthomas

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The slides were used as holding graphics in the stream and displayed in the stream itself but some speakers had it and some did not. 
![image](https://user-images.githubusercontent.com/2492510/48515540-d75db500-e815-11e8-90e2-3d7c0bedbd30.png)

It looked like some of speakers content changed from the original and the someone updated the slide to reflect that:
**original**
![image](https://user-images.githubusercontent.com/2492510/48515900-e8f38c80-e816-11e8-92d1-d3c9b62cf1fe.png)
**updated by unknown (in Zilla typeface)**
![image](https://user-images.githubusercontent.com/2492510/48515807-a29e2d80-e816-11e8-9fe5-6c9758df54ef.png)

The slides were displayed on two screens by the stage. Note that the text can be larger to be seen from the back.
![dsc02343](https://user-images.githubusercontent.com/2492510/48513894-f1959400-e811-11e8-8dee-d59126fb21e6.jpg)
![dsc02543](https://user-images.githubusercontent.com/2492510/48513908-fb1efc00-e811-11e8-96b9-a5cb6540751b.jpg)
![img_6156](https://user-images.githubusercontent.com/2492510/48513933-05d99100-e812-11e8-8b7d-7c788aa17083.JPG)
