### ISSUE TITLE
Screen: Dialogue & Debates Video Title and End Cards  

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#38]
### Description:
Create screens that come before and after speaker's videos (intro/outro). These can correspond with the speaker slides itself (issue https://github.com/MozillaFoundation/mozfest-design-2018/issues/37)

**Each title card contains:**
- Speaker's Name
- Mozilla Festival 2018 Wordmark
- Dialogue & Debates title

**An individual end card can be used for all videos that contain:**
- Mozilla Festival 2018
- website URL
- tagline or festival short description
- consider spacing layout according to platform end screen

Dimensions: 1920x1080 (16:9 ratio)
Format: .png files
Platform: Youtube (consider overlay thumbnails and annotations) https://github.com/MozillaFoundation/mozfest-design-2017/issues/87#issuecomment-382134898

### Previous Applications
Youtube playlist: https://www.youtube.com/watch?v=atYKpi_74Ak&list=PLYiaJo7rYNXInD71OAShY4xfl6fhskoUV

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=1H3cc4VG1kwUOJV75so2Sjk9nAacgpvnr
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/87#issuecomment-382134898

### Related Issue:
Issue slide https://github.com/MozillaFoundation/mozfest-design-2018/issues/37

**Comment by gideonthomas** [comment]
cc @xmatthewx

**Comment by makikoumezawa** [comment]
@KevZawacki Here are the Dialogues and Debates Google Slides: https://docs.google.com/presentation/d/1KT-76PFRXPuCldcxB_71PwJBUU8LcJoCvPlp22w87VU/edit?usp=sharing

Could you please review them?

You can access the folder including all the png images here: https://drive.google.com/open?id=1fQemQhz1sGmrWGkJmcH6nHs_GpQruo_q

/cc @sabrinang @gideonthomas

**Comment by makikoumezawa** [comment]
Here is the folder with the Dialogue & Debates Video Title and End Cards: https://drive.google.com/open?id=16iKgOtQPeV4F3WM-KpvaAcwsC3GmLUrT

Last year, the end cards were covered by the profile icon and the playlist video thumbnail so here is a mockup on how it looks with this years end cards:

![screen shot 2018-10-19 at 8 57 07 pm](https://user-images.githubusercontent.com/41972873/47251066-afc82800-d3e2-11e8-8c9d-261d752551ae.png)

/cc @gideonthomas @sabrinang

**Comment by Saallen** [comment]
Looks great - thanks @makikoumezawa

**Comment by gideonthomas** [comment]
@sabrinang what does handoff look like for this?

**Comment by KevZawacki** [comment]
@makikoumezawa These are fantastic!

@sabrinang May I send to Andy, over at AirMozilla?

**Comment by sabrinang** [comment]
@KevZawacki Yup, please pass them on to @airmoandy

**Comment by KevZawacki** [comment]
@airmoandy the speaker series title and end cards are finished 👆

Do you need anything further? Please let me know if I can help!

**Comment by airmoandy** [comment]
@KevZawacki Thank you Kevin! I will pass these onto Mac and the projectionist in the D&D.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

Since the videos were cut from the live stream there didn't seem to be distinct end cards with channel or playlist recommendation after it. The title card has been used in the stream itself but for the end card it might be something we can set up with on Youtube after the video has been uploaded. If we can have end cards as the video finishes and title cards can be used as the thumbnail too that would be preferable.
![image](https://user-images.githubusercontent.com/2492510/48515591-f65c4700-e815-11e8-8466-83ea881a44b0.png)
