### ISSUE TITLE
Screen: Background + Assets for ProPresenter Social

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#39]
### Description:
Screens near the main stage will be using ProPresenter to showcase social media activity from twitter, instagram etc. 

Assets TBD to deliver:
- background
- typography
- lockups
- tagline
- hashtag

### Previous Applications:
https://github.com/MozillaFoundation/mozfest-design-2017/issues/14#issuecomment-346896553
![mozilla-festival-2017_propresenter-slide](https://user-images.githubusercontent.com/2492510/31857907-fc7ad4f2-b69e-11e7-8b6a-e43c91b7e040.jpg)

![mozilla-festival-2017-123](https://user-images.githubusercontent.com/2492510/33223905-26386180-d119-11e7-955c-36e2edca07f7.jpg)
![mozilla-festival-2017-128](https://user-images.githubusercontent.com/2492510/33223908-2c4d7e16-d119-11e7-8b3a-05f9d4442bb7.jpg)

### Deliver to:
A/V Mac

### Reference from Last Year: 
Google Drive File: https://drive.google.com/open?id=0B4Q8pzCpDS_ea3NxRUZ5R3VXZFk
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/14

**Comment by sabrinang** [comment]
Here are the backgrounds for ProPresenter that will display on the screens beside the stage throughout the festival. 

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/2492510/47103591-65815400-d1f4-11e8-8997-802edbc73c33.png">

Last year's example: 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/2492510/47103180-84331b00-d1f3-11e8-90e4-f6ce5a8bb8a4.png">
In the past it looks like mismatched text has been added separately, if you are including the text above please use Zilla Slab: https://fonts.google.com/specimen/Zilla+Slab

White gear logo SVG here: https://drive.google.com/file/d/1V4mq9fpyepH75vcaUZ8kRRszYT0-wOYw/view

Various PNG (backgorund only, text and text/logo versions) are exported on gdrive here: https://drive.google.com/drive/u/1/folders/1bqz64rDzrxhTSqPS4Jcm25WpCHMUTIgn

@Saallen I put `share your #MozFest experience` instead of `tweet your #mozfest experience` since there was mention of instagram use too on name tags. Please review copy and designs.

/cc @gideonthomas Note: this would need to go to Mac Jefferies but I don't know if he uses github

**Comment by gideonthomas** [comment]
I can coordinate the handover

**Comment by gideonthomas** [comment]
@Saallen what are the screens we need for this?

@marcwalsh do you have a way to share the propresenter app with @natalieworth? It seems like it's a paid app.

**Comment by marcwalsh** [comment]
@gideonthomas @natalieworth there is a download link for a two week trail available here:
https://renewedvision.com/propresenter/download/

**Comment by gideonthomas** [comment]
oh perfect, thanks @marcwalsh!

@Saallen what content is going into these slides?

**Comment by Saallen** [comment]
@gideonthomas I think we just need each number point per slide and logos

1. We would like to thank our Sponsors
2. Presenting partner -Private Internet Access
3. Science Fair partner - Internet Society
4. Media partner- Shareable
5. Closing partner - Sticker Mule
6. Youth Zone - Samsung

**Comment by gideonthomas** [comment]
Thanks @Saallen, I'll get a start on it and hand it over to @natalieworth

**Comment by Saallen** [comment]
@gideonthomas - can you share this with @marcwalsh?

**Comment by marcwalsh** [comment]
Thanks all! Closing! :)

**Comment by sabrinang** [comment]
## Post MozFest Documentation

Throughout the festival we used ProPresenter on the two screens by the stage to display social, sponsors and the mozilla 20th anniversary reel. There were limitations to the proportions and backgrounds during the set up of these screens. @gideonthomas may have more details.
![dsc02286](https://user-images.githubusercontent.com/2492510/48513095-ce69e500-e80f-11e8-8db6-f62737965a50.jpg)
![dsc02592](https://user-images.githubusercontent.com/2492510/48513342-6ff13680-e810-11e8-9093-4642eb83b7db.jpg)
![img_5650](https://user-images.githubusercontent.com/2492510/48513412-957e4000-e810-11e8-8138-ba5da8bef18d.JPG)
![image](https://user-images.githubusercontent.com/2492510/48514863-2c003080-e814-11e8-860f-ee15b2fda00d.png)

**Comment by gideonthomas** [comment]
Template file (some things needed to be updated): https://drive.google.com/file/d/1G8zxXcmfvV5Hb7JlSDlcuGdtKzYaV7Pf/view?usp=sharing

ProPresenter is awful, there are significant limitations on slide transitions, backgrounds, proportions, etc. and the AV team had difficulty setting it up to work with the screens. We shouldn't use this next time and instead use a website or google slides and figure out a way to embed tweets.
