### ISSUE TITLE
Social: Graphics for Call for Proposals

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#4]
Create a simple graphic that will accompany social media posts for proposals that is dependent on issue https://github.com/mozilla/mozillafestival.org/issues/859

Platforms: Twitter and Facebook (any others?)
Date: Sent out on June 1

____________________
### Reference from Previous Years:

2017 issue: https://github.com/mozilla/mozillafestival.org/issues/541
2017 l10n issue: https://github.com/mozilla/mozillafestival.org/issues/580

**Comment by bunnybooboo** [comment]
I share quite a bit on Mastodon ([recently added](https://discourse.mozilla.org/t/iam-coss-parsys-sprint-h-review/28144) to Mozillians accts too):
  - user acct avatar image size at most 2MB and downscaled to 400x400px
  - user acct header image size at most 2MB and downscaled to 700x335px
  - maximum shareable image size 1280x1280 @ 8MB
  - since v2.3.3 it's possible to define the 'center' of cropped image (aka Focal Point)
  - timeline default thumbnails crop to 16:9 ratio (though this may differ among apps.. stick with focal point instead)
  - a11y friendly image descriptions

**Comment by sabrinang** [comment]
<img width="1094" alt="screen shot 2018-06-02 at 2 40 35 am" src="https://user-images.githubusercontent.com/2492510/40873409-631a93bc-6614-11e8-8191-97b2a010b793.png">
Call for proposal graphic .jpgs available in EN, DE, ES, FR in four colours in gdrive folder: https://drive.google.com/open?id=1q5Yn3Hv7Zs0UpyxBGd4mCZEpqcfgXfTV

### Reference
copy issue/duplicate: https://github.com/mozilla/mozillafestival.org/issues/890
l10n issue: https://github.com/mozilla/mozillafestival.org/issues/904

@KGorr I'll be on PTO on Monday but I hope you can use these then. I'll iterate on them after if needed and when we have the copy for the remaining two languages.

**Comment by KGorr** [comment]
@sabrinang - these are amazing! Thanks so much for the quick turnaround!

**Comment by KGorr** [comment]
@sabrinang - can we turn the gdrive link for these to anyone with the link can view? I believe that's what we did last year so folks could download. Let me know!

**Comment by bunnybooboo** [comment]
Is it possible to have all 4 colors in both sizes?

**Comment by sabrinang** [comment]
@KGorr I changed permissions to _Anyone who has the link can view_ now
@bunnybooboo Yes, I can work on colours for both sizes and will update this ticket and the folder

**Comment by sabrinang** [comment]
I have updated the folder: https://drive.google.com/open?id=1q5Yn3Hv7Zs0UpyxBGd4mCZEpqcfgXfTV 

@bunnybooboo colours are available in both sizes now
@barrosgeraldo your pt-br translation can be found in the folder too

**Comment by barrosgg** [comment]
Thank @sabrinang

**Comment by sabrinang** [comment]
I updated the folder with the remaining hi-IN and SW language variations: https://drive.google.com/open?id=1q5Yn3Hv7Zs0UpyxBGd4mCZEpqcfgXfTV
