### ISSUE TITLE
Screen: Background + Assets for AirMo + Youtube Video Stream

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#40]
### Description:
For audiences tuning into the Dialogue & Debates on Air Mozilla and Youtube, we need to prepare some branded assets to be displayed with the video stream.

Assets TBD to deliver:
- Background behind AirMo Logo (16x9, 1920x1080)
- Lockup, Logo + Wordmark (.png)
- Title Card for MozFest 2017 Opening Keynote (16:9, 1920x1080)
- Title Card for Speaker Names
- Title Card for MozFest 2017 Speaker Series (16:9, 1920x1080)

### Previous Applications:
https://github.com/MozillaFoundation/mozfest-design-2017/issues/15#issuecomment-346898958

### Reference from Last Year: 
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/15
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eZGZwMW94ZFd4dkk

**Comment by airmoandy** [comment]
Thanks Sabrina!

**Comment by sabrinang** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/2492510/47051698-27cfed00-d15a-11e8-9ceb-a1090f55d163.png">

These screens are designed for the Saturday opening ceremony which includes a background slide, wordmark slide, welcome slide and opening keynote title slide.

@Saallen Do we have speakers for the opening keynote? and if so we can create title cards for these speakers with their names.

@airmoandy you can download the PNGs (original and retina 2x size) and I exported it to the same gdrive folder and separated dialogues and debates screens there too: https://drive.google.com/drive/u/1/folders/1aceHgoM4QBJ6XdWCHPDhHlgPS3s3M78R

**Comment by airmoandy** [comment]
R=Thank you so much for creating these additional graphics Sabrina! :-)

**Comment by sabrinang** [comment]
@airmoandy regarding webcast console:
![webcast console reference](https://user-images.githubusercontent.com/2492510/47102653-26ea9a00-d1f2-11e8-99dc-3ecb1aac2780.png)
This graphic background is also used for the ProPresenter #39 as well so they will match. You can find the PNG here: https://drive.google.com/file/d/1bvz5pfZ3FyOctdzdgRL0zMOhJ6zRClub/view

**Comment by airmoandy** [comment]
![image](https://user-images.githubusercontent.com/43478485/47106778-873f0300-d215-11e8-8dfc-540f690d4f24.png)
I made the changes (speaker bio now used as example). The logo does indeed have a white glow edge, which I think is necessary to make it prominent.

**Comment by Saallen** [comment]
Looping in Sarah Watson to answer @sabrinang question above "Do we have speakers for the opening keynote? and if so we can create title cards for these speakers with their names" 
We might not need slides for each but would be nice to have a static one but will let sarah make the decision

**Comment by SarahWat** [comment]
Thanks - these look great! 

Keynote will consist of: 
- Allen Gunn, Executive Director of Aspiration 
- Mark Surman, Executive Director of Mozilla Foundation 
- Stéphanie Ouillon, Firefox Security Engineer, Mozilla Corporation 
- Sunil Abraham, VP, Leadership Programs, Mozilla Foundation

**Comment by SarahWat** [comment]
Although I don't believe we need slides for everyone. I think just having the MozFest 2018 slide up while everyone speaks is sufficient.

**Comment by sabrinang** [comment]
Great thanks @SarahWat
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/2492510/47111773-493be200-d209-11e8-9508-b5645a0b21ef.png">

PNGs exported in gdrive folder: https://drive.google.com/drive/u/1/folders/1bUoEsnIFbf9isbrH0ZpWrgi0Dkeupn84

**Comment by gideonthomas** [comment]
@airmoandy let us know i you need any other assets other than the additional keynote ones above.

**Comment by airmoandy** [comment]
Thank you Gideon! I believe that we are set with graphics for now :-)

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The speaker cards didn’t get displayed on youtube or airmo  but displayed the generic title card as a placeholder. There were additional speakers who got added which we didn’t know about so we didn't have cards for them (mysdiggi, Amba Kak, Winnie & Priyanka). The colour and background adjustments looked good but (bg may be stretched depending on browser window). For the logo on airmo, we should avoid shadow/outer glow as it doesn’t match the others and doesn't follow the overall brand guide anyway https://mozilla.design/mlogo/. 

![image](https://user-images.githubusercontent.com/2492510/48512108-83e76900-e80d-11e8-90f6-cfe3aa82dc59.png)
![image](https://user-images.githubusercontent.com/2492510/48512205-c27d2380-e80d-11e8-896d-86323db38feb.png)
