### ISSUE TITLE
Wayfinding: Entrance, Space and Floor Banners

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#41]
### Description:
Design banners that hang from the balustrades that can be seen from the foyer and atrium that help indicate what each floor is for. 

**This collection of banners include:**
- [ ] Mozilla Festival 2018 Branded (Entrance) x2
- [ ] Data Done Right (Entrance) x2
- [ ] Floor No. (M-9)
- [ ] Youth Zone
- [ ] Privacy & Security
- [ ] Openness
- [ ] Decentralization
- [ ] Digital Inclusion
- [ ] Web Literacy

**Other TBD**
- M Floor
- 0 Dialogues and Debates (Walker Space)
- Quiet Space

### Specifications
**Print:** .pdfs exported using custom Pixart templates
**Dimensions:** Large (100cm x 200cm) & Small (75cm x 150cm) 
**Holes:** 3 holes at the top of large banners and 2 holes for small banners
**Format:** can reconsider horizontal format to consider long titles (example: decentralization was hyphenated)

### Previous Applications
https://github.com/MozillaFoundation/mozfest-design-2017/issues/33#issuecomment-346881591
![mozilla-festival-2017-39](https://user-images.githubusercontent.com/2492510/33220913-dad149cc-d100-11e7-8ac8-2b59ca47b791.jpg)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eV3dXRnNYM3U0dlk
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/33 and https://github.com/MozillaFoundation/mozfest-design-2017/issues/30

**Comment by gideonthomas** [comment]
@Saallen to confirm what the non-space thematic floors are. Are they the same as last year? (e.g. quiet space, internet research hub, unbox, cafe, etc.)

**Comment by gideonthomas** [comment]
Testing a ping for @Saallen

**Comment by Saallen** [comment]
This collection of banners include:

Mozilla Festival 2018 Branded (Entrance) x2
Data Done Right (Entrance) x2
Floor No. (M-9)
Youth Zone
Privacy & Security
Openness
Decentralization
Digital Inclusion
Web Literacy
Art + Data
Queering MozFest
Quiet Space
Internet research Hub

We would like additional banners but not in the same format- as these will be in rooms or by tables
Dialogues and Debates
Gaming MozFest

**Comment by sabrinang** [comment]
@Saallen From today's discussion, we would need a type of MozFest Café floor banner like last year. I don't know if sponsors expect "Lounge" or if there are other Lounge pieces we would need to coordinate with. After some consideration, Lounge may be less misleading than Café (which may have more restaurant associations than a hang out space?) for where it was last year:
![image](https://user-images.githubusercontent.com/2492510/46032902-ac76a080-c0b1-11e8-952f-5e6d2ad85a7e.png)

Sarah, I just want to confirm on the issue which name we are going with?

/cc @gideonthomas

**Comment by Saallen** [comment]
Happy to change the name to Lounge.

Would also need to add the sponsors name so suggesting...
Brought to you by our Presenting Festival Partner, Private Internet Access

**Comment by Saallen** [comment]
@marcwalsh can we delay this design deadline?

**Comment by makikoumezawa** [comment]
@Saallen Here is the overview of the floor banners: https://redpen.io/p/uyc27e0defb58f60ca

/cc @gideonthomas @sabrinang

**Comment by gideonthomas** [comment]
@Saallen re-pinging for review.

**Comment by Saallen** [comment]
Hey @makikoumezawa looking great two requests however
* Can you make a banner that says Mozilla Zone
* Lounge space- should say  something that indicates its "brought to you by our Presenting partner Private internet access" w logo

**Comment by Saallen** [comment]
@makikoumezawa Did you impliment the changes requested above?
I dont see them in the new red pen to review @sabrinang 

cc @gideonthomas

**Comment by makikoumezawa** [comment]
**Overview**
![screen shot 2018-10-16 at 9 19 43 pm](https://user-images.githubusercontent.com/41972873/47113211-47741d80-d20d-11e8-9835-e853a2a62086.png) 


**Data Done Right Tagline Banner and Mozilla Festival Annual Lockup Banner**
![screen shot 2018-10-16 at 9 03 53 pm](https://user-images.githubusercontent.com/41972873/47113396-c9644680-d20d-11e8-9bf1-7be4dab88e54.png)


**Mockup**
![screen shot 2018-10-17 at 1 03 07 pm](https://user-images.githubusercontent.com/41972873/47113148-1e538d00-d20d-11e8-87cd-694a32e9c5f9.png)



@Saallen I've added Mozilla Zone and the sponsorship for Lounge space. I've also included Internet Research Hub which was listed on your banner list. This space was not included in the maps but could you confirm if we are still putting up Internet Research Hub?

I followed the Pixart template by adding the dimensions to generate the customized guidelines.

Dimensions: Number Banners (75cm x 150cm) & Space Banners (150cm x 150cm)

Holes: 4 holes at the top of Space Banners (recommended by Pixart) and 2 holes for Number Banners

Here is the link of the folder containing all the pdfs: 
https://drive.google.com/open?id=11YH5hWcVNpqv7CjU9SZzG6npArqJVIAJ

All Number Banners and Space Banners plus Data Done Right Lockup (Number Banner size) and Mozilla Festival Lockup (Space Banner size) are in this folder as seperate pdfs. 

Please look over the Redpen for the revised version: https://redpen.io/p/uyc27e0defb58f60ca


/cc @gideonthomas @sabrinang

**Comment by gideonthomas** [comment]
@Saallen does this look good?

**Comment by marcwalsh** [comment]
Sent to print! ⏲

**Comment by marcwalsh** [comment]
Sorry closed the wrong ticket accidently!

**Comment by Saallen** [comment]
Looks great thank you- yes please keep Internet research hub

**Comment by marcwalsh** [comment]
Sent to print! 🔢

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The floor banners had reinforced perimeters and small banners had two holes while large banners had 4 holes. All headings were horizontal with similar banner heights which made the design look clean. The tagline and lockup banners didn’t get printed at pixart so we sent it to print at Ravensbourne which did vinyl printing (quality was subpar from Raves as the ink looked like it was running out, had full hand prints from handlers and poor cutting by hand). We reinforced the edges to hide the cutting (tape wasn’t strong, time consuming to do so). We installed the banners with cable ties and aligned them across the rails which looked great. For quiet space, we used white tac only and the banner adhered to the wall since it didn’t have anything to cable tie to.

![dsc02267](https://user-images.githubusercontent.com/2492510/48591519-1284e480-e8f9-11e8-9adb-3f6bccd1c81b.jpg)
![img_6140](https://user-images.githubusercontent.com/2492510/48584050-97fa9b80-e8dd-11e8-8b04-70bbcca7f8d5.JPG)
![img_6027](https://user-images.githubusercontent.com/2492510/48584077-aba60200-e8dd-11e8-9d39-d54f2b313a9e.JPG)
![img_6025](https://user-images.githubusercontent.com/2492510/48584770-887c5200-e8df-11e8-8015-7623d59cc7f6.JPG)
![dsc02279](https://user-images.githubusercontent.com/2492510/48584377-6e8e3f80-e8de-11e8-879f-9af35e21d866.jpg)
![dsc02290](https://user-images.githubusercontent.com/2492510/48584485-adbc9080-e8de-11e8-8120-b591bd0d0b17.jpg)
