### ISSUE TITLE
Wayfinding: Floor Plan Maps 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#42]
### Description:
Update location of spaces and specific locations for this year and update the branding and colours. This content includes highlighting:
- Spaces
- Lunch 
- Coffee
- D&D Stage
- Main Stage
- Quiet Space
- Toilets
- Water
- #mozhelp
- Info Booth
- Artist Space
- Registration

### The collection of maps include:
- [ ]  11 Current Floor Maps
- each floor has a unique version
- [ ] 1 Floor Overview Map
- [ ] Festival Guide may contain a version of these maps

### Specifications
**Print:** .pdfs exported using custom Pixart templates
**Dimensions:** A3 + A2
**Format:** Cardboard printing had ink spreading (blurry text), last year we used a plastic but consider using something that is recyclable?
**Quantity:**
22 x Generic Floor Maps
2 x 11 Floor Specific Maps 
2 x Large A2 Generic Floor Maps

### Previous Applications
https://github.com/MozillaFoundation/mozfest-design-2017/issues/32#issuecomment-346711699
![mozilla-festival-2017-268](https://user-images.githubusercontent.com/2492510/33190984-ac404ca4-d068-11e7-80b0-a4f6eb1f92c0.jpg)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eVmluRV9vdWF3dWc
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/32

**Comment by sabrinang** [comment]
Note: Confirm dates when the spaces will be finalized by (project spreadsheet says Oct 1)

**Comment by gideonthomas** [comment]
Hopefully this should be ready by the third week of September. Tracking issue for the space information is here: https://github.com/mozilla/mozillafestival.org/issues/1068

**Comment by gideonthomas** [comment]
@makikoumezawa the location info copied from mozilla/mozillafestival.org#1068 is:

**Spaces**
* Youth zone - 2
* Web Literacy - Library
* Decentralisation - level 6
* Openness- 7
* Digital Inclusion - level 8
* Privacy and Security - level 9

**Experiences**
Art+Data - M (or mezzanine) 
Tracked - 5
Queering MozFest - 6

**Extra areas**- (that dont have to be on the map but might have high footfall)
Mozilla Zone - 1 
Emergent Sessions  - 8
Prototyping Lab 9


Other content:

    Registration- 0
    Dialogues & Debates Stage - 0
    Main Stage - 4
    #MozHelp - 4
    Quiet Space - 0
    Lunch- 0, 4, 7, 9
    Info Booth - at entrance to 2, 6, 7, 8, 9
    Coffee 0, 5, 9 
    Water- all floors (same as last year)
    Toilets all floors ( same as last year)
(Private access internet) Lounge 5 

I have also shared the floor plans for Ravensbourne with you. Let me know if you're missing any information.

**Comment by makikoumezawa** [comment]
Here is a draft of the floor maps. Please review before being exported.
https://redpen.io/p/tv5dbb6fbb96b46b85

PDF version: https://drive.google.com/open?id=1zPx1WaYbZzEVkfntUyR5q4kCuaLaAwIQ

/cc @gideonthomas @sabrinang

**Comment by sabrinang** [comment]
Great work on this so far @makikoumezawa and I left some comments in the redpen for content inconsistencies. 

Some overall design feedback:
- consider consistent colouring with overview map and large maps
    - example: on larger maps, level 6 has darker orange shade, experiences are darker except queering, youth zone and D&D space
- consider consistent headings on overview map and large maps
    - example: overview map has all caps while large maps have title case; colour treatment is different but I can see how it may look too busy adjacent to each other on overview so navy is fine

**Comment by gideonthomas** [comment]
@Saallen how do the floor maps look: https://drive.google.com/open?id=1SNI-duT6YYM0Zl0rTdvGkcvacSXwn_OC

**Comment by makikoumezawa** [comment]
@sabrinang I've made all the corrections from your feedback and included version 2 on Redpen.

Pdf version: https://drive.google.com/open?id=1SNI-duT6YYM0Zl0rTdvGkcvacSXwn_OC

@Saallen Can you please confirm if I placed Quiet Space, Lounge, Study Zone, and Emergent Sessions in the correct location? I'm aware which level they are on but I couldn't find any information where these spaces will be located specifically. 

/cc @gideonthomas

**Comment by Saallen** [comment]
Hey @makikoumezawa  I reviewed and made some edits here 
[scan-1.pdf](https://github.com/MozillaFoundation/mozfest-design-2018/files/2473909/scan-1.pdf)

**level 1** 0- Quiet space is next door to where you allocated
Mezz on my print out has the M right up against Art....weirdly its not on the digital versions
**Level 1** is fine
**Level 2** is fine
**Level 3** is fine
**Level 4** has too many words-
Remove study zone
I would suggest removing Stage and leaving big space but I don't mind
**Level 5** Lounge is in the wrong position- see scan for correct position
Gaming MozFest is by the balcony and coffee should be shifted a little to the left (although dont mind leaving in current location is you think it looks better)
**level 6** Looks fine
**Level 7** looks fine but the food are is a room so added broken lines to the map.
708 is positioned a little more to the left nearer the balcony but dont mind if you want to keep location if it looks better
**Level 8** Emergent sessions are in 801
**Level 9** Shift coffee a little to the left as its does sit right by the balcony ( again if you think it looks better in its current position then I'm fine with you leaving it)
Shift 905 to the x position and the info booht to the ? position

**Comment by Saallen** [comment]
Good to note the the level list at the bottom of each large map
on level 4 you share Main Stage/Web Literacy

* please note all revisions apply across the pages, not just the one with all the maps

**Comment by gideonthomas** [comment]
@makikoumezawa -- requesting one more change (since it can be a bit confusing). Can we separate out lunch into two things?

So in the legend it would be:
\<fork and knife icon\> Hot Lunch
\<some appropriate icon\> Grab & Go Food

and then mark them on the maps?
Grab & Go Food will be on Level 0 and 9
Hot Lunch will be on Level 4 and 7.

Let me know if you're able to make these changes.

**Comment by gideonthomas** [comment]
@makikoumezawa how's this going?

**Comment by makikoumezawa** [comment]
![screen shot 2018-10-15 at 2 53 30 pm](https://user-images.githubusercontent.com/41972873/46980701-3e0e7800-d08a-11e8-818e-1894c038ba25.png)


@gideonthomas I've included all the requests and made Sarah's corrections.

PDF version: https://drive.google.com/open?id=14wrFGxd5onSqCLUrLwetGp-VuuvEMljF
Redpen: https://redpen.io/p/tv5dbb6fbb96b46b85

/cc @Saallen @sabrinang

**Comment by gideonthomas** [comment]
@Saallen would you be able to review these one last time?

@makikoumezawa would you be able to export each map as a separate pdf?

**Comment by makikoumezawa** [comment]
@gideonthomas Here's the folder with all maps and background layered sheets as separate pdfs:

https://drive.google.com/open?id=1BVbH8DQNOiyYW52_jeKlsGU2yAyFCgKQ

**Comment by Saallen** [comment]
Aproved and look so pretty- Thanks 🌹

**Comment by marcwalsh** [comment]
@makikoumezawa - I think there may be an error on the L8 background. Could you check as it appears to be purple instead of the pink. :)

**Comment by makikoumezawa** [comment]
@marcwalsh - Thank you for finding my mistake. I've changed the L8 Background pdf and updated on the folder.

**Comment by marcwalsh** [comment]
Sent to print!! Thanks 🍦

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The floor plan maps from pixart had issues in delivery so it was partially delivered and we ended up printing the rest at aspect print. We assembled the map on backgrounds and used a spacer to keep it consistent. We mounted the maps in lifts, outside the lifts and high traffic areas near the stairs. The layered style helped the maps stand out against the many posters in the space. 

![31778184848_3ee6cf59ae_z](https://user-images.githubusercontent.com/2492510/48581831-bf4e6a00-e8d7-11e8-94b2-8753b589d914.jpg)
![dsc02558](https://user-images.githubusercontent.com/2492510/48581840-cb3a2c00-e8d7-11e8-97f8-bf97c0c296a7.jpg)
![img_5916](https://user-images.githubusercontent.com/2492510/48581926-050b3280-e8d8-11e8-9f30-783fa6e0c11a.JPG)
![img_6028](https://user-images.githubusercontent.com/2492510/48581974-22400100-e8d8-11e8-9d52-980a92906ba0.JPG)
