### ISSUE TITLE
Wayfinding: Registration Table Banner (or Table Cloth)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#43]
### Description:
When attendees enter the venue, there are a few registration tables set up and signs or table cloths that help make the tables look official so people know where to go.

### Specifications
Previous year's we printed a paper banner for the front. Let's aim to streamline these 10 tables to have tablecloths. These table cloths can include:
- Mozilla Festival Lockup
- Mozilla Logo
- Welcome
- Logo or cube pattern or branding _(think evergreen designs we can reuse following years)_

### Previous Applications
![image](https://user-images.githubusercontent.com/2492510/43549190-dac2cdee-9594-11e8-9717-c474ae3086c2.png)
We have around 10 tables set up in registration:
![image](https://user-images.githubusercontent.com/2492510/43549226-f09f3634-9594-11e8-9f0c-790ab65d72ad.png)
MozFest House had nice table cloths anchoring the space:
![mozfest-house-39](https://user-images.githubusercontent.com/2492510/32521579-d16cdb70-c3c8-11e7-96ef-434cb927875c.jpg)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eUWZsc1NmRXU0MHM
Registration Table SIgnage Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/26
MozFest House Table Cloth Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/64

**Comment by sabrinang** [comment]
After chatting with @marcwalsh @gideonthomas today, table cloths are a bit pricey (MozFest House style) but we will look at PixArt textiles https://www.pixartprinting.co.uk/printing-flags-textiles/ for the registration area. We would need 6:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/2492510/45776115-c40fde00-bc06-11e8-9983-38dc40516840.png">

@marcwalsh to provide dimensions for the size of two folding tables side by side. Also, would it be cheaper if they were all the same design or is it the same price if they are unique?

**Comment by marcwalsh** [comment]
@sabrinang We had a discussion today about placement of tables in the registration area. 

**We require table clothes for:**
4x Registration
2x Press and Youth
1x Swag
1x Name Tag 

I'm waiting for the size of the tables, I've pinged Ravensbourne and requested them ASAP.

**Comment by gideonthomas** [comment]
@marcwalsh would you be able to provide the dimensions of the tables?

**Comment by marcwalsh** [comment]
Rave folding table dimms:

70.5cm (D) 140.5cm (W) 77.2cm (H)

**Comment by sabrinang** [comment]
@Saallen @gideonthomas If the buyer's guide team is going to be on level 0, would they need a table cloth too?

**Comment by gideonthomas** [comment]
@Saallen and @marcwalsh would you be able to coordinate about that ^, it shouldn't affect design right?

**Comment by Saallen** [comment]
I dont think so @beccaklam can you confirm?

**Comment by gideonthomas** [comment]
Confirmed, we don't need a table cloth for Buyer's Guide

**Comment by sabrinang** [comment]
Here is the table cloth design 220cmx150cm so the table cloth drop is approximately 40cm. If budget allows, we can have reinforced stitching on entire perimetre.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/2492510/46699320-4704d280-cbce-11e8-89ba-51f6f3ca7d1d.png">

@Saallen Please review design of table cloth and @marcwalsh please confirm these dimensions would work for the table cloth.  Redpen here: https://redpen.io/wo05f32200c3f52ea2

.ai file using custom pixart template for large format synthetic fabrics flags on gdrive here: https://drive.google.com/file/d/1IpW4jhqk1ZWlEhNDF4CiEgSUuuzsjSmg/view

**Comment by marcwalsh** [comment]
Sent to print! 🕺

Closing and will reopen if there are any changes required.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The size for table cloth worked out nicely and had reinforced stitching on entire perimetre. Overall it made the registration area look more organized and united. It look like there were extra from the photo and we could of distributed them throughout the table by info booth spaces if this is the case next year. The fabric was a durable, stiff synthetic material (unsure what exactly was ordered) but the colour came out more grey green than black.

![dsc02376](https://user-images.githubusercontent.com/2492510/48581301-4995ce80-e8d6-11e8-9fa4-21acb6a8751f.jpg)
![img_6133](https://user-images.githubusercontent.com/2492510/48581375-7d70f400-e8d6-11e8-8a19-b4ae2da4bae2.JPG)
![img_6083](https://user-images.githubusercontent.com/2492510/48581398-8feb2d80-e8d6-11e8-947a-9e2e22776834.JPG)
![img_6137](https://user-images.githubusercontent.com/2492510/48581349-6a5e2400-e8d6-11e8-9c17-2d0adb60482c.JPG)
![44925978434_248fff226f_z](https://user-images.githubusercontent.com/2492510/48590443-51646b80-e8f4-11e8-89d3-4018f78a3a25.jpg)
