### ISSUE TITLE
Wayfinding: Registration Table Signage & Area Design

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#44]
### Description:
When attendees enter the venue, there is registration signage to help identify the various stations to guide them through the process.

### This collection of signs include:

- [ ] Welcome sign (with l10n incorporated) https://github.com/mozilla/mozillafestival.org/issues/720
- [ ] Sign-in & Register Sign
- [ ] Participation Guidelines
- [ ] Customize Your Name ID Sign
- [ ] Instructions about Icebreaker Game/ Language/Pronouns Sticker Sign
- [ ] Collect Your Swag
- [ ] Youth & Press & Accessibility SIgn

**Format:**
Consider the order in which the stations are arranged and document on design checklist. Include Large type that is legible from afar. Plan to have organizers for pens or stickers because that station gets messy. Also, I would consider the Collect your Swag station to be at the end (since there was various waterbottles/guides left at the customization station and people won't have to fumble with stuff as they make their name cards look fancy.)

### Previous Applications
![image](https://user-images.githubusercontent.com/2492510/43550628-1880265a-9599-11e8-8e04-e57acafd7407.png)
![image](https://user-images.githubusercontent.com/2492510/43550657-2daecb94-9599-11e8-8ea2-ae1f25595cf0.png)
![image](https://user-images.githubusercontent.com/2492510/43550668-36dcb1a4-9599-11e8-9838-c32af70964c8.png)
![image](https://user-images.githubusercontent.com/2492510/43550768-7e5ee934-9599-11e8-9b65-0c1883181a80.png)

### Related Issue
Registration Table Cloths: https://github.com/MozillaFoundation/mozfest-design-2018/issues/43

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ebktZM3RsSklzNDg/view?usp=sharing
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/26#issuecomment-340008251 & https://github.com/MozillaFoundation/mozfest-design-2017/issues/26#issuecomment-340008251

**Comment by sabrinang** [comment]
Confirmed with @marcwalsh we can have floor signage from PixArt https://www.pixartprinting.co.uk/displays/point-of-sale-displays/floor-display/

**Comment by sabrinang** [comment]
@Saallen Please review the copy and design on redpen: https://redpen.io/p/uy68fd9de2b1cef2a5

These are the large floor displays at the registration area for sign-in, name tag customisation, swag, youth/press/accessibility, participaiton guideline and privacy alert for the weekend. I'm not sure if these floor displays are too large for MozFest House but but I exported the for the CPG and privacy alert in case you want it in this format as well. These are the same size as https://github.com/MozillaFoundation/mozfest-design-2018/issues/83 (100cmx70cm)

I used customise instead of customize since our other things replace z.

<img width="976" alt="image" src="https://user-images.githubusercontent.com/2492510/46848660-f47b1000-cd9f-11e8-8e7c-334c0f725dc8.png">

Print PDFs on gdrive here exported on floor display pixart template: https://drive.google.com/drive/u/1/folders/1QkClCz8GkdeSYGPAFx-lHlW-8vZzD7OI

Note: I'll be make the instructions about Icebreaker Game and Welcome sign in different formats from these floor displays

/cc @gideonthomas

**Comment by Saallen** [comment]
Looks great - approved 👍

**Comment by marcwalsh** [comment]
Sent to print! Thanks 💆‍♂️

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The registration floor displays (with table cloths) helped tie the registration space together and was large enough not to be overlooked while entering the space. The signage had a top tab that often snapped that needed to be reinforced with tape so the back stand would stay in place. It was a good system to have privacy alert, participation guideline and sponsor signs in the same size with related design to help distinguish this official set of wayfinding.

![img_6000](https://user-images.githubusercontent.com/2492510/48585772-8e276700-e8e2-11e8-80d0-78fa2d969943.JPG)
![dsc02376](https://user-images.githubusercontent.com/2492510/48585341-32a8a980-e8e1-11e8-8558-6868984bcbfd.jpg)
![img_6074](https://user-images.githubusercontent.com/2492510/48585404-67b4fc00-e8e1-11e8-8913-c27082cb3115.JPG)
![img_6136](https://user-images.githubusercontent.com/2492510/48585576-e3af4400-e8e1-11e8-830b-d91f2ae3f2aa.JPG)
![dsc02426](https://user-images.githubusercontent.com/2492510/48585366-43f1b600-e8e1-11e8-9d11-29d674cfcdba.jpg)
![dsc02368](https://user-images.githubusercontent.com/2492510/48585658-25d88580-e8e2-11e8-8d4a-9df389115a52.jpg)
