### ISSUE TITLE
Registration Table: Understand Me Better Cards (a11y)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#45]
### Description
At the Youth & Press & Accessibility registration table, there will be "Understand Me Better" cards the size of business cards for people to use to hand out when communication is difficult

**Format**
An idea was to include a hole puncher here too so attendees can clip it on their name card for convenient access.

### Previous Applications
https://github.com/MozillaFoundation/mozfest-design-2017/issues/70#issuecomment-345853634
![mozilla-festival-2017-202](https://user-images.githubusercontent.com/2492510/33044725-dd43fb46-cdfe-11e7-8e28-db3183f0a312.jpg)

### Related Issues
Registration Signage: https://github.com/MozillaFoundation/mozfest-design-2018/issues/44

### Reference from Last Year
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eYXBlaTFia2NKanc
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/70

**Comment by sabrinang** [comment]
@marcwalsh Can you use last year's file to print more of these if we don't have them?
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eYXBlaTFia2NKanc

**Comment by marcwalsh** [comment]
Sent to print! 🥇

**Comment by sabrinang** [comment]
## Post MozFest Documentation

These were distributed on the accessibility table and registration. I requested for a hole puncher to be placed with these cards so they can attach it to their name tag if needed but I don’t think the hole puncher ever showed up. I don’t have feedback if these cards were effective or used.

![img_5702](https://user-images.githubusercontent.com/2492510/48585079-60412300-e8e0-11e8-9587-bf854a94a179.JPG)
![44736312345_cb79ca9a00_z](https://user-images.githubusercontent.com/2492510/48585225-d6de2080-e8e0-11e8-9107-06a43b64bd47.jpg)
