### ISSUE TITLE
Wayfinding: Info Booths for Spaces

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#46]
### Description:
At the entrance or stairway to each space or floor, we have a desk stationed with space information for attendees. We can place this information totem to anchor the space with description, map and participation guidelines.

**This booth can include:**

- [ ] Space Info (Name, Icon, Description) for all 6 Spaces
- [ ] Information Symbol
- [ ] Participation Guidelines
- [ ] Map of Space

Space Descriptions: https://mozillafestival.org/spaces

### Previous Applications
<img width="926" alt="image" src="https://user-images.githubusercontent.com/2492510/31684966-51b8ed1c-b336-11e7-92cb-8414c92b6162.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/43551659-a1f61d9c-959c-11e8-8c73-7dffe8066c7c.png">

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eZUxJOHhvN0NWX2s?usp=sharing
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/28

**Comment by sabrinang** [comment]
Participation Guideline content dependent on https://github.com/mozilla/mozillafestival.org/issues/1045

**Comment by sabrinang** [comment]
Floor Plan maps content dependent on https://github.com/MozillaFoundation/mozfest-design-2018/issues/42

**Comment by gideonthomas** [comment]
@Saallen to confirm by Friday, Sep 7, that we can use the same content pieces we used for last year.

**Comment by Saallen** [comment]
Content for boards this year
This booth can include:

    Space Info (Name, Icon, Description) for all 6 Spaces
    Information Symbol
    Participation Guidelines
    Map of Space

On third panel- we would like the blank area to be laid out as a board/info template for wranglers to write info, session details other pieces. Idea is that this panel is for scheduling needs and so should still have link to digital schedule

**Comment by sabrinang** [comment]
@marcwalsh Do you have a deadline for this? Can we make it Oct 12?

**Comment by sabrinang** [comment]
@marcwalsh Can we also confirm we are going with Totem 3 XL this year too? https://www.pixartprinting.co.uk/displays/point-of-sale-displays/totem-3-xl/

**Comment by marcwalsh** [comment]
@sabrinang this is fine to move to Friday and yes we're using the Totem 3 XL again

**Comment by sabrinang** [comment]
The totems include maps from https://github.com/MozillaFoundation/mozfest-design-2018/issues/42 and participation guidelines from https://github.com/MozillaFoundation/mozfest-design-2018/issues/56. It includes the #MozHelp hashtag and sched URL on the side and features the floor number, space name, icon and short description.

For the experiences, I included a floor display that features their experience name and description if they want to put it near the entrance of their space as well.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/2492510/46983801-09ed8400-d097-11e8-99d9-3f729bd19964.png">

@Saallen Please review redpen here: https://redpen.io/p/bq1c8e63c463c16be8

Spaces exported on Totem XL and experiences exported on large floor displays on gdrive here: https://drive.google.com/drive/u/1/folders/1X7Bcj250sslGzfDwUk4iwry4dUUqNGGv

/cc @gideonthomas

**Comment by Saallen** [comment]
Gorgeous- reviewed with no issues

**Comment by marcwalsh** [comment]
Sent to print! 🗺

**Comment by sabrinang** [comment]
@marcwalsh In case there are issues with the totems, I have exported the info booths in the Two Panel Folding Banner format too https://www.pixartprinting.co.uk/displays/banner-stands/expobanner-tri/

PDFs exported on gdrive: https://drive.google.com/open?id=1gxvNyJWLco4HRlrPYZE9Bd5Fk87Rb4vV

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The info booths were helpful to distinguish the space and floor signs for experiences were a nice addition. The large booths were folding on itself as we were unboxing it and we noticed it created a fold in the centre.  We were relieved these got delivered as the similar oversized totems for MozFest House got stuck in customs (or something) and did not arrive. 

![dsc02446](https://user-images.githubusercontent.com/2492510/48585918-0857eb80-e8e3-11e8-9c86-6c472aac1715.jpg)
![dsc02465](https://user-images.githubusercontent.com/2492510/48585928-11e15380-e8e3-11e8-87af-0ca76e9082e7.jpg)
![dsc02493](https://user-images.githubusercontent.com/2492510/48585951-2887aa80-e8e3-11e8-91d0-6dee14c7de8c.jpg)
![img_6009](https://user-images.githubusercontent.com/2492510/48585977-3b01e400-e8e3-11e8-80b2-9636ed6f021f.JPG)
![img_5955](https://user-images.githubusercontent.com/2492510/48585991-4a812d00-e8e3-11e8-8240-76563fb0195f.JPG)
![img_5656](https://user-images.githubusercontent.com/2492510/48586005-5cfb6680-e8e3-11e8-8a90-00385097d971.JPG)
![44925584034_8da351a015_z](https://user-images.githubusercontent.com/2492510/48586292-62a57c00-e8e4-11e8-9dfd-5f07bbb4d0b8.jpg)
![img_6116](https://user-images.githubusercontent.com/2492510/48586339-836dd180-e8e4-11e8-9eda-cb04d9983205.JPG)
![img_5910](https://user-images.githubusercontent.com/2492510/48586368-8f599380-e8e4-11e8-8abe-16a3e3f64448.JPG)
