### ISSUE TITLE
Wayfinding: #MozHelp Desk Signage & Area Design

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#47]
### Description:
Last year, the #MozHelp desk was on level 4 outside the library. Design some signs to make this easy to find.

### This collection of signs include:
- [ ] Metal Bus Stop Sign
- [ ] Floor Sign
- [ ] Table Front sign
- [ ] Plastic Mini Stand Sign
- Large Banner in the back?

**Format:**
There are various formats of signage (bus stop sign, floor sign, plastic stand, table front) near the help desk area. These signs can coordinate with the #mozhelp volunteer t-shirts.

### Previous Applications
![image](https://user-images.githubusercontent.com/2492510/43552237-a5a7c3da-959e-11e8-8dd2-07ef6c4cbea4.png)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eMDJ3cVh0R0ZwaGs & https://github.com/MozillaFoundation/mozfest-design-2017/issues/29#issuecomment-339990429
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/29

**Comment by sabrinang** [comment]
Note: We may want to include a #MozHelp sign about toiletries we want to supply at the desk area and in the halls of the washrooms

/cc @Saallen for more details on what we are supplying and copy

**Comment by Saallen** [comment]
The production team will make a small a4 page with what we have in that box. No need for designed posters

**Comment by sabrinang** [comment]
The #MozHelp booth will have similar wayfinding to the registration floor display designs https://github.com/MozillaFoundation/mozfest-design-2018/issues/44 . This includes A4 bus stop signs, big poster and floor sign to cover up Ravensbourne's information desk signs. We don't need horizontal A4s those were extra last year.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/2492510/47036017-5df87700-d130-11e8-8773-b0b7ee7721c3.png">

@Saallen Review redpen here: https://redpen.io/p/sycab6bc498a2b0205

Print PDF on gdrive here: https://drive.google.com/drive/u/1/folders/1aW8hZvZmoISnFUr5zdmwpRGrruYfBw9w

/cc @gideonthomas

**Comment by Saallen** [comment]
Perfect thanks @sabrinang

**Comment by sabrinang** [comment]
## Post MozFest Documentation

We had two A4 but it was difficult to find the other plastic stand so unsure if the other was used. The signage set printed at Ravensbourne. Originally the floor sign was right in front but it looks like it was relocated to be in a more noticeable angle which is great. The floor sign was a good durable material.

![img_5956](https://user-images.githubusercontent.com/2492510/48586504-0131dd00-e8e5-11e8-8bb7-76fe89648f3a.JPG)
