### ISSUE TITLE
Wayfinding: Floor Stickers

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#48]
### Description:
To accompany the wayfinding maps, we will use a floor sticker system that displays floor number, space name, directional arrows, venue areas and branding. The information is modular in case we don't know which space is assigned to which particular floor until early October so when we do the install at Ravensbourne we have a flexible system. Last year we printed extra stair vinyls and it was helpful as we lost some or they got torn/ripped during the weekend.

**This collection of vinyls include:**
- [ ] MozFest (Gear) Logo
- [ ] MozFest Lockup
- [ ] Data Done Right Tagline Lockup
- [ ] 6 Sets of Space Labels for Stairs (Floor Number, Space Name, Arrow)
- [ ] 3 Sets of Experience Labels for Stairs (TBD)
- [ ] Debates and Discussions (Walker Space on Level 0) + Arrow
- [ ] MozHelp + Arrow
- [ ] Sponsorship - Presenting Festival Partner

**Format**
StickerMule print these as oversized stickers and print as large as 1.48m x 5m format.

**Quantities:**
- 1x large mozilla festival lockup
- 1x large web for all
- 4x large arrows
- 2x large dialogue & debates
- 2x floor numbers (m-9)
- 12x side arrow
- 12x diagonal arrow
- 2x space icons + gear (7 types)
- 2x dialogue & debates
- 4x #mozhelp
- 2x art + data
- 2x queering mozfest
- 2x gaming mozfest
- 2x decentralization
- 2x digital inclusion
- 2x openness
- 2x web literacy
- 2x privacy and security 
- 2x youth zone

### Previous Applications
![image](https://user-images.githubusercontent.com/2492510/43552899-65ec9600-95a1-11e8-99ee-d79fb5102543.png)
![image](https://user-images.githubusercontent.com/2492510/43552865-277c9226-95a1-11e8-8b63-47acb77f6feb.png)
![image](https://user-images.githubusercontent.com/2492510/43552869-368ebae6-95a1-11e8-8d20-4b9dec716b5a.png)
![image](https://user-images.githubusercontent.com/2492510/43611027-c2a0c5e0-965c-11e8-8f90-f48918f958b1.png)
![image](https://user-images.githubusercontent.com/2492510/43611057-da7f29fe-965c-11e8-99a7-5f60f3f6afb0.png)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eOF9OUTYwcnVjZEE
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/31

**Comment by sabrinang** [comment]
**Sponsorship Update:**

We have a Presenting Festival Partner at MozFest this year and we will print x2 floor stickers of their logo. These will be placed in front of elevators and designed with _Presenting Festival Partner at MozFest_ for context.

**Comment by Saallen** [comment]
Juan confirmed this for the presenting partner

**Comment by gideonthomas** [comment]
Sponsorship Update: https://github.com/MozillaFoundation/mozfest-design-2018/issues/75#issuecomment-424507958

- x2 floor stickers of the presenting festival partner
- x1 floor sticker of the closing party partner

**Comment by sabrinang** [comment]
I have designed the floor stickers to include spaces, experiences, mozhelp, d&d, space icons, level numbers, directional arrows, sponsors, MozFest lockup, logo and taglines.

@Saallen Please review the content and designs on redpen here: https://redpen.io/p/mj494e39187a6feea3
<img width="403" alt="image" src="https://user-images.githubusercontent.com/2492510/46565384-a6f43400-c8c3-11e8-8e01-34cb1c6de927.png">

I've exported these as .ai files with a stickermule template for printing here: https://drive.google.com/open?id=1DU4trit6eCXdnvx0TgVm4jfdc8h7N-rQ

**Comment by sabrinang** [comment]
Note: last year's floor stickers had "decentralization" should it be "decentralisation" to be consistent else where?

**Comment by Saallen** [comment]
Yes- we are using S this year. 🤷‍♀️ 

Designs look great- added a few comments

**Comment by sabrinang** [comment]
Floor stickers updated:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/2492510/46701211-d5c81e00-cbd3-11e8-813e-d44316c1c162.png">

.ai files with a stickermule template for printing here: https://drive.google.com/open?id=1DU4trit6eCXdnvx0TgVm4jfdc8h7N-rQ

**Comment by sabrinang** [comment]
Separate .ai exports are updated in the same folder: https://drive.google.com/drive/u/1/folders/1DU4trit6eCXdnvx0TgVm4jfdc8h7N-rQ

### Floor Stickers Dimensions
Art+Data
33.1087 cm x 10 cm

Closing Party Partner
72.6857 cm x 26.2485 cm

Data Done Right Blue
125.7367 cm x 76.694 cm

Data Done Right Multi
58.7109 cm x 10 cm

Decentralisation
58.7109 cm x 10cm

Dialogues and Debates Large
135.7656 cm x 20 cm

Dialogues and Debates
67.8828 cm x 10 cm

Digital Inclusion
56.8923 cm x 10 cm

Gaming MozFest
52.3637 cm x 10 cm

Gear Logo Blue
127.7609 cm x 127.7609 cm

Large Arrow
27.9341 cm x 17.2705 cm

MozHelp
34.5368 cm x 10 cm

Mozilla Festival Lockup Large
126.0209 cm x 50.3659 cm

Openness
33.6226 cm x 10 cm

Presenting Festival Partner
89.1266 cm x 25.8402 cm

Privacy & Security
69.8571 cm x 10 cm

Queering MozFest
58.6373 cm x 10 cm

Web Literacy
45.4133 cm x 10 cm

Youth Zone
38.8949 cm x 10cm

### Floor Square Folder Dimensions
All 23 designs in the Floor Squares folder are:
10 cm x 10 cm

**Comment by marcwalsh** [comment]
Sent to print! 👍

**Comment by sabrinang** [comment]
@marcwalsh Is it too late to print additional floor stickers? I'm going through the set up and noticed the floor banners have some areas indicated but they don't have floor stickers (a nice to have not necessary):

(1) Mozilla Zone
(0) Quiet Space
(1) Internet Research Hub
(8) Emergent Sessions
(5) Lounge

**Comment by sabrinang** [comment]
@marcwalsh I exported the 5 stickers above as an .ai file of all of them and separate pdfs (trim mark + 3mm bleed) on gdrive here to be printed at Ravensbourne: https://drive.google.com/drive/folders/1gM707yqRDJm2tZbPx38VPzjHJwEgGotb

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The tagline and lockup stickers looked great aligned to the floor lines near the entrance of the space. We used the gear logo to anchor the floor space by the step and repeat. We managed to print the additional floor stickers for the non-space areas at Ravensbourne and the quality of the sticker matched nicely. The modular system with arrows was flexible during floor and stair installation. We used multiple steps this time instead of having them all on the top step and was spaced well for easy reading. The sponsorship floor stickers were stuck near both lifts on level 0. During the closing party, we installed it by the level 4 stair by the big space but got removed by volunteers when they were doing take down during closing party (they need to be informed what they should not remove but the sticker itself indicates closing party). We used the sticker on carpet by the stage and it adhered well. We used the extra stickermule sponsor sticker on the table where we giving away extra stickers.

![45650700561_25b0a7fa85_z](https://user-images.githubusercontent.com/2492510/48593018-d608b700-e8ff-11e8-98e7-072f4db24407.jpg)
![dsc02373](https://user-images.githubusercontent.com/2492510/48586709-8ae1aa80-e8e5-11e8-8f5d-f842377a4b1f.jpg)
![44925964344_d3d6dbd285_z](https://user-images.githubusercontent.com/2492510/48593041-f3d61c00-e8ff-11e8-96bb-3f47238f56df.jpg)
![dsc02361](https://user-images.githubusercontent.com/2492510/48586718-8f0dc800-e8e5-11e8-9b0f-ba095ce4b977.jpg)
![dsc02366](https://user-images.githubusercontent.com/2492510/48586721-92a14f00-e8e5-11e8-848b-4e1c1d79b04e.jpg)
![dsc02551](https://user-images.githubusercontent.com/2492510/48586728-99c85d00-e8e5-11e8-95b9-847aa1e2785e.jpg)
![img_5932](https://user-images.githubusercontent.com/2492510/48586863-02173e80-e8e6-11e8-9271-4cfdd83cdff4.JPG)
![img_5884](https://user-images.githubusercontent.com/2492510/48586905-25da8480-e8e6-11e8-845b-3feed93fdc33.JPG)
![img_5793](https://user-images.githubusercontent.com/2492510/48586974-5f12f480-e8e6-11e8-822e-3db3af9d621f.JPG)
![dsc02491](https://user-images.githubusercontent.com/2492510/48586753-afd61d80-e8e5-11e8-9176-c09de26703db.jpg)
![dsc02522](https://user-images.githubusercontent.com/2492510/48586773-bebcd000-e8e5-11e8-8769-184109cfb41c.jpg)


![45600537842_9995fd2fac_z](https://user-images.githubusercontent.com/2492510/48592920-81653c00-e8ff-11e8-80bf-205a000cc2b2.jpg)
![31778602988_50c8b27757_z](https://user-images.githubusercontent.com/2492510/48592925-83c79600-e8ff-11e8-9f08-bb87466dec2c.jpg)
![45600542112_84ffc6f6b7_z](https://user-images.githubusercontent.com/2492510/48592926-8629f000-e8ff-11e8-9a93-cbd2861d6ded.jpg)
