### ISSUE TITLE
Wayfinding: Hackable Signs for Space Session Schedule

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#50]
### Description:
Design empty template signs for wranglers to make a sign for sessions hosted in their space.

This year we may want to try the idea of having a hackable schedule poster like a whiteboard near the space entrance. It can be empty blocks for wranglers or info booth volunteers to fill in if it is useful but even having framed hackable posters is a good start to make these schedules look more official.
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/2492510/29840716-c522ab80-8cb7-11e7-8928-fed92a5a24ba.png">

### Previous Applications
Last year there were a lot of these flip chart style schedules, we can help provide a template for wranglers to use so attendees can differentiate what is official or not:
![image](https://user-images.githubusercontent.com/2492510/43600103-8c30976a-963e-11e8-9cf3-d1193818dc48.png)
![image](https://user-images.githubusercontent.com/2492510/43600121-9d446e8c-963e-11e8-8c87-55fcbc15902f.png)
![image](https://user-images.githubusercontent.com/2492510/43600131-a4a97bae-963e-11e8-8f97-d1ca0323bda4.png)
![image](https://user-images.githubusercontent.com/2492510/43600167-bb8845f8-963e-11e8-9cc5-1d56b6eb8e91.png)
![image](https://user-images.githubusercontent.com/2492510/43600629-fe737a08-963f-11e8-844f-5f3ae28920b2.png)

### Reference from Last Year: 
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/34

**Comment by marcwalsh** [comment]
@sabrinang - what size are we expecting these to be? I would do them as a [Custom Format](https://www.pixartprinting.co.uk/digital-litho-printing/printing-other-formats/) if you're after something long like in the intial comment.

**Comment by gideonthomas** [comment]
Due Oct 17

**Comment by sabrinang** [comment]
I made A1 portrait hackable signs for schedules to be used instead of flip chart paper examples above. This design includes a light dotted grid in the back to help with alignment and a frame for each space, an experience frame for all three and a generic MozFest design if needed. 

@marcwalsh If these should be smaller let me know but A2 seemed a bit too small but each space probably wouldn't need to many (each space/experience probably needs just 1-2 per day?)

@Saallen Please review redpen here: https://redpen.io/p/nv40d15d16f67fa8eb
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/2492510/46986102-70c46a80-d0a2-11e8-9db5-ac29acf0f1c3.png">


A1 Print PDF on gdrive here: https://drive.google.com/drive/u/1/folders/1_DtmkzPTNI6PiI9ILwtcvwV_CULRyxlj

**Comment by Saallen** [comment]
Look great- thanks

**Comment by marcwalsh** [comment]
Sent to print! ⌛️

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The hackable large signs were used in various ways to display room numbers, schedules, drawn maps, session names and beyond to supplement space wayfinding.

![img_5855](https://user-images.githubusercontent.com/2492510/48598952-6bb14000-e91a-11e8-9237-aae6a4cd250f.JPG)
![img_5955](https://user-images.githubusercontent.com/2492510/48598967-7cfa4c80-e91a-11e8-9da0-0a2621a6dbb4.JPG)
![dsc02465](https://user-images.githubusercontent.com/2492510/48599257-cac38480-e91b-11e8-8ea3-b4274e976acd.jpg)
![44736303845_96e6366cc6_z](https://user-images.githubusercontent.com/2492510/48599723-cc8e4780-e91d-11e8-8399-f092d0aa5549.jpg)
