### ISSUE TITLE
Wayfinding: Hackable Signs for Session Cards

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#51]
### Description:
Design empty template signs for session hosts to make a sign for their session. These cards can be used for the science fair demos as well.

**Format**
- full A4
- folded A4

### Previous Applications
https://github.com/MozillaFoundation/mozfest-design-2017/issues/34#issuecomment-346195634
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2492510/31708044-cdacf4b0-b3a2-11e7-8d16-8f952eb7d8c5.png">
I loved that the decentralization space stuck on a white layer to make whiteboard markers work on these signs. If it is cost efficient I would like to do this more broadly for hackable schedules.
![mozilla-festival-2017-243](https://user-images.githubusercontent.com/2492510/33101719-3e93e4d6-cece-11e7-9381-5dc4c3a9c8c4.jpg)

### Reference from Last Year: 
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/34

**Comment by sabrinang** [comment]
@marcwalsh Confirming we printing these from PixartPrinting?

**Comment by marcwalsh** [comment]
@sabrinang - Yes these are ([Custom Formats](https://www.pixartprinting.co.uk/digital-litho-printing/printing-other-formats/), but not pre-folded), I've attached a template below.
@gideonthomas - Looking at timelines, it might be safer to have these on Oct 17th to ensure I get them as early as possible when wranglers arrive.

[A4 Template is here...](https://github.com/MozillaFoundation/mozfest-design-2018/files/2451006/pixartprinting-template-small-format-custom-formats.2.pdf)

**Comment by sabrinang** [comment]
I made A4 portrait hackable signs for sessions for each space, an experience frame for all three, a generic MozFest design along with one we can fold for science fair.
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/2492510/46985811-255d8c80-d0a1-11e8-9f1c-7d768960790e.png">

@Saallen Please review redpen here: https://redpen.io/p/nv40d15d16f67fa8eb

A4 Print PDF on gdrive here: https://drive.google.com/drive/u/1/folders/1YZsN4CyDLAPL73yn0B8MBU5veUwkqkJC

**Comment by Saallen** [comment]
reviewed- and approved

**Comment by marcwalsh** [comment]
Sent to print! 🖊

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The folded hackable signs were used at science fair and throughout the festival. The card stock wasn’t very good at standing up on its on though. The hackable A4s were fine and used in the corresponding spaces.

![dsc02265](https://user-images.githubusercontent.com/2492510/48594278-deafbc00-e904-11e8-918a-99c1b004dd2b.jpg)
![dsc02275](https://user-images.githubusercontent.com/2492510/48594300-e8d1ba80-e904-11e8-9839-d8888db45511.jpg)
![dsc02302](https://user-images.githubusercontent.com/2492510/48594307-eec79b80-e904-11e8-8c7e-5294be101c0c.jpg)
![dsc02495](https://user-images.githubusercontent.com/2492510/48594325-fd15b780-e904-11e8-90c7-2127059d094a.jpg)
![dsc02429](https://user-images.githubusercontent.com/2492510/48598908-3147a300-e91a-11e8-9ad1-d907b6546cb5.jpg)
![img_5842](https://user-images.githubusercontent.com/2492510/48598944-5805d980-e91a-11e8-9ca2-59ac662a5ca1.JPG)
![img_5974](https://user-images.githubusercontent.com/2492510/48598972-84b9f100-e91a-11e8-841d-81b5c28675d3.JPG)
![img_6042](https://user-images.githubusercontent.com/2492510/48639098-6b9b5980-e987-11e8-9905-90d241872ea5.JPG)
