### ISSUE TITLE
Poster: Tagline Poster (& L10n Version)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#53]
### Description:
Design official MozFest Tagline posters that will be around the building and collect them at the end of the event for people to take them home. There will be a version with the l10n of the tagline as a poster. 

**Format and Quantity**
- [ ] Main (EN) Poster
- [ ] L10n Poster

### Previous Applications
![mozilla-festival-2017-227](https://user-images.githubusercontent.com/2492510/33100642-f3f99b54-cec9-11e7-8546-b7ca2f090456.jpg)

### Related L10N Issue:
https://github.com/mozilla/mozillafestival.org/issues/923
https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2018/mozfest.lang&action=translate&show#string2

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_ea1M2M0NlbERTVVk
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/36

**Comment by sabrinang** [comment]
I designed a light and dark poster with the main lockup. Also, included a design for the l10n versions of the lockup. 

@Saallen What would you suggest for location info or copy? Last year it was London, UK but on our website we have Greenwich alone so I am a bit confused what is the proper way to write out the location on the poster.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/2492510/47198121-6531a780-d31f-11e8-962b-9a70968f137a.png">

Please review the design, l10n and copy on the print PDFs exported on pixart A3 on gdrive here: https://drive.google.com/open?id=1doOmZcvz8E8S1s4HLA-DwSB56HOt859C

/cc @gideonthomas

**Comment by Saallen** [comment]
Lets do same copy as last year, London
Looks so good @sabrinang thanks

**Comment by sabrinang** [comment]
Updated to London, UK on all posters on gdrive for print: https://drive.google.com/drive/folders/1doOmZcvz8E8S1s4HLA-DwSB56HOt859C

<img width="920" alt="image" src="https://user-images.githubusercontent.com/2492510/47231337-76130500-d381-11e8-905c-9e4fad90d25c.png">

**Comment by sabrinang** [comment]
I didn't catch it earlier the dates were 22-26 so I changed them to 22-28. I updated the print PDF again: https://drive.google.com/drive/folders/1doOmZcvz8E8S1s4HLA-DwSB56HOt859C 

<img width="870" alt="image" src="https://user-images.githubusercontent.com/2492510/47233891-e6715480-d388-11e8-89ff-9d15334eed52.png">

**Comment by marcwalsh** [comment]
Sent to print!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The posters looked like they were printed on semi gloss and was put up throughout the space for additional branding. During closing, we collected the posters we put up with our extra prints and gave them away on the front table during closing for people to take.

![dsc02269](https://user-images.githubusercontent.com/2492510/48600147-981b8b00-e91f-11e8-8157-178d8d316e3b.jpg)
![dsc02550](https://user-images.githubusercontent.com/2492510/48600169-b2556900-e91f-11e8-9d74-50d70c14d8a6.jpg)
![dsc02507](https://user-images.githubusercontent.com/2492510/48600164-acf81e80-e91f-11e8-9c06-da0e041874b5.jpg)
![img_6146](https://user-images.githubusercontent.com/2492510/48600237-f21c5080-e91f-11e8-9bd4-0ecc3c0f2352.JPG)
![45600542112_84ffc6f6b7_z](https://user-images.githubusercontent.com/2492510/48640469-ad2e0380-e98b-11e8-9c23-343c0eb7c64c.jpg)
