### ISSUE TITLE
Poster: Dialogues & Debates

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#54]
### Description:
Design promotional poster for the speakers this year at MozFest. Last year, each time block was designed as a collection to feature a cluster of speakers. Posters should include information such as:

- Time of talk
- Speakers' names
- Speakers' photos
- Title of each speaker's talk
- Location (Walker Space on the ground floor)

Information on speakers will be here but to be confirmed by Kevin: 
https://mozillafestival.org/speakers or https://medium.com/mozilla-festival/cryptographers-activists-engineers-speakers-at-mozfest-2018-b4e31e4c648a

**Format**
- A2

### Previous Applications
![mozilla-festival-2017-204](https://user-images.githubusercontent.com/2492510/33099899-640c34b8-cec7-11e7-815d-8a69ba14acd1.jpg)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/file/d/0B3b1KWRwjxtoenV0NG1QWmhuekk/view?usp=sharing
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/37

**Comment by gideonthomas** [comment]
@Saallen to confirm that we can use content from the Speakers page by Friday, Sep 7.

**Comment by Saallen** [comment]
Yes confirming you can use content from speakers page @gideonthomas

**Comment by makikoumezawa** [comment]
@Saallen Here is the pdf version for the Dialogues and Debates Posters which will be printed at Ravensbourne: https://drive.google.com/open?id=1jZKX9fphXjyVcTLcy0zFSoZp4vSl0lf8

/cc @sabrinang  @gideonthomas

**Comment by Saallen** [comment]
I am going to ask @KevZawacki to review as I dont trust myself with timings.
Kev can you double check the timings here?

**Comment by KevZawacki** [comment]
Oh man, this is fantastic! 🎆 Thank you, @makikoumezawa.

One change, if possible: Nani jansen Reventlow had to bow out at the last minute. Is it possible to remove her graphic?

**Comment by makikoumezawa** [comment]
@KevZawacki I've removed Nani Jansen Reventlow from the poster. 

@marcwalsh Here is the updated version: https://drive.google.com/open?id=1jZKX9fphXjyVcTLcy0zFSoZp4vSl0lf8

/cc @sabrinang @gideonthomas @Saallen

**Comment by gideonthomas** [comment]
@marcwalsh feel free to change labels if we are going to print this at Ravensbourne.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

We made last minute updates to the speaker roster on the poster and the first set of posters had a missing logo (showed up as black square) so we reprinted at Ravensbourne. The paper was high gloss and we would of preferred a matt paper as it was very reflective. On Sunday, it looks like the Saturday poster was taken down.

![dsc02366](https://user-images.githubusercontent.com/2492510/48584917-f0cb3380-e8df-11e8-8f48-f63e4158872b.jpg)

![img_6077](https://user-images.githubusercontent.com/2492510/48584888-d7c28280-e8df-11e8-91af-ca2188469f14.JPG)
