### ISSUE TITLE
Poster: Photo & Video Consent 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#55]
### Description:
Poster that outlines our photo consent policy. This is displayed prominently at registration, near the debates room and near the mains stage area. This will be at MozFest House as well.

**Format**
- A2 and A3?

### Previous Applications
I prefer the smaller sandwich board style on the table than the oversized leaning on front. It can be installed behind them.
![mozfest-house-25](https://user-images.githubusercontent.com/2492510/32525022-5ef82cd4-c3d7-11e7-9884-374eaca7c1bb.jpg)
![mozilla-festival-2017-187](https://user-images.githubusercontent.com/2492510/33099287-4777bfae-cec5-11e7-88f3-a46b8673b533.jpg)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eWGl2U0N6cEtKcFU
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/38

**Comment by sabrinang** [comment]
### Copy from 2017:

**Privacy Alert**
Please don't photograph people with yellow lanyards

- If you do not wish to be photographed or videoed, please request a yellow lanyard from Registration. These special lanyards signify that you do not wish to be captured by the onsite photography and video team.  

- Stage activity on the 4th floor and in the Walker Space will be captured on video. If you do not wish to be filmed, we advise you to sit in the back, or watch the live streams from another location in the venue. 

- Please visit the Welcome Desk in the foyer for further information.

**Comment by gideonthomas** [comment]
@Saallen to review and provide copy by Friday, Sep 7.

**Comment by Saallen** [comment]
@gideonthomas copy below.

Privacy Alert
Please don't photograph people with yellow lanyards

These special lanyards signify that this person does not wish to be captured by the onsite photography and video team.

* If you do not wish to be photographed or recorded on video, please request a yellow lanyard from Registration. 
* Stage activity on the 4th floor and in the Walker Space will be captured on video. If you do not wish to be filmed, we advise you to sit in the back, or watch the live streams from another location in the venue.
* Please visit the Welcome Desk in the foyer for further information.

**Comment by marcwalsh** [comment]
@sabrinang do you having sizing and format for these posters?

**Comment by sabrinang** [comment]
We will have the privacy alert as a floor display size near registration: https://github.com/MozillaFoundation/mozfest-design-2018/issues/44

We will have 2 printed on rigid media 59.4cm x 59.4cm to match https://github.com/MozillaFoundation/mozfest-design-2018/issues/84   as a set behind registration on the grate.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2492510/46889030-2a0f1000-ce17-11e8-8b13-2941d09eb453.png">

The rest of these will be A3 size.

A3, Rigia Media & Floor Display sizes:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/2492510/46889437-8cb4db80-ce18-11e8-9b97-64fe9b19cdab.png">

@Saallen Please review content and design on redpens: https://redpen.io/kvd4c2893f907b9fa0  &  https://redpen.io/bg1b23ed7ae18877e9

Print PDF for A3 and Rigid media square gdrive here: https://drive.google.com/drive/u/1/folders/1U0VsMQTIjX9Q0jnoFVeZrFnrog0zYIn2

**Comment by sabrinang** [comment]
note: I will export House versions as well

**Comment by sabrinang** [comment]
MozFest House privacy alert in A3 size. It also has this privacy alert as a large floor display size also in issue #44

A3 & Floor Display sizes:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/2492510/46893217-11a5f200-ce25-11e8-8d46-47b8d605bf4d.png">

@Saallen A3 Redpen for review here: https://redpen.io/az8834c7ac87ac5679

Print PDF also exported in gdrive here: https://drive.google.com/drive/u/1/folders/1U1mjfCFWFRSmvgpeLAq1isoMYXafjXXG

**Comment by Saallen** [comment]
approved

**Comment by marcwalsh** [comment]
We're changing how this is being printed slightly...

Printed by Pixart
EN A3 Posters - x5 on Foamex
EN Square Posters - x2 on Foamex with Metal Hooks
EN Floor Stands x2 on Cardboard

Printed at Ravensboune
Other LANGs - A3 - x2 of each on heavy matt paper

**Comment by marcwalsh** [comment]
I've sent to print all Pixart assets from this ticket - so removing the Ready to Print label and attaching Printing On-Site

**Comment by sabrinang** [comment]
This privacy alert poster is EN only and doesn't have localized language versions so there is nothing left to print on site.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

At MozFest House, the privacy alert were seen throughout the space A3 and floor displays near entry. 

At the weekend, the registration and level 4 big space had large floor displays. The square signs were displayed across the mesh behind registration.

![img_5487](https://user-images.githubusercontent.com/2492510/48601418-8ab4cf80-e924-11e8-82de-2da9d82cd4fc.JPG)
![dsc02257](https://user-images.githubusercontent.com/2492510/48601544-13cc0680-e925-11e8-8f89-ec9ad3fe6475.jpg)
![img_6080](https://user-images.githubusercontent.com/2492510/48601364-5fca7b80-e924-11e8-9f6d-735afa38190e.JPG)
![dsc02367](https://user-images.githubusercontent.com/2492510/48601451-b0da6f80-e924-11e8-9b5b-607600b5e2cb.jpg)
![img_6132](https://user-images.githubusercontent.com/2492510/48601347-54775000-e924-11e8-9f55-2f95b3ff7e4e.JPG)
![img_5936](https://user-images.githubusercontent.com/2492510/48601480-d5cee280-e924-11e8-8895-e807dc079f8a.JPG)
