### ISSUE TITLE
Poster: Participation Guidelines (en/l10n)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#56]
### Description:
Poster that outlines our participation guideline policy. This is displayed prominently at registration, info booths and throughout the space. This is also on the back of the printed festival guide.

**Content**
TBD
These guidelines will be localized in other languages as well so this poster should accommodate more than English or if there are too many languages then we may need to separate posters.

**Format**
- A2 and A3?

### Previous Applications
- Back of Festival Guide
- Participation EN guides sandwich boards were seen at MozFest House 
![mozfest-house-23](https://user-images.githubusercontent.com/2492510/32524145-335a5da8-c3d3-11e7-85cc-2a080e18086b.jpg)
![mozilla-festival-2017-214](https://user-images.githubusercontent.com/2492510/33098332-e2a88a2a-cec1-11e7-83df-b73cc4a12712.jpg)

### Related L10N Ticket
TBD

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eR2NXM0E0TUlQR2s
Github Issue: https://github.com/mozilla/mozillafestival.org/issues/703
& https://github.com/mozilla/mozillafestival.org/issues/731

**Comment by sabrinang** [comment]
Content dependent on https://github.com/mozilla/mozillafestival.org/issues/1045

**Comment by gideonthomas** [comment]
Localized strings can be found here: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/mozfest_design_assets.lang

**Comment by marcwalsh** [comment]
@sabrinang do you have the sizing and print type you'd like this on?

**Comment by sabrinang** [comment]
We will have the pariticipation guidelines EN as a floor display size near registration: https://github.com/MozillaFoundation/mozfest-design-2018/issues/44

We will have 2 printed on rigid media 59.4cm x 59.4cm to match https://github.com/MozillaFoundation/mozfest-design-2018/issues/84   as a set behind registration on the grate.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2492510/46889030-2a0f1000-ce17-11e8-8b13-2941d09eb453.png">

All versions (EN + 8 languages) will be A3 size.
l10n content: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/mozfest_design_assets.lang&action=translate#string1
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/2492510/46893980-a7428100-ce27-11e8-80b0-8937071f5e13.png">

A3, Rigia Media & Floor Display sizes:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/2492510/46894078-00121980-ce28-11e8-9539-fa11154619fc.png">

@Saallen Please review content, l10n content and design on redpen: https://redpen.io/p/fn229e818c7d103577

Print PDF for A3 and Rigid media square gdrive here: https://drive.google.com/drive/u/1/folders/1SjFOnT4BQZgcimlwQp84qq4A8FfJu5Cl

_________________________

MozFest House participation guidelines in A3 size. It also has this privacy alert as a large floor display size also in issue #44

A3 & Floor Display sizes:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/2492510/46894556-c6daa900-ce29-11e8-905e-992ee1b62ba2.png">

@Saallen A3 Redpen for review here: https://redpen.io/jnad15fe05c682f14d

A3 Print PDF also exported in gdrive here: https://drive.google.com/file/d/1VFXvnMObYchlm7mp03Te6B0CRiVZ9UP2/view?usp=sharing

**Comment by Saallen** [comment]
Looks great @sabrinang 💮

**Comment by marcwalsh** [comment]
We're changing how this is being printed slightly...

*Printed by Pixart*
EN A3 Posters - x5 on Foamex
EN Square Posters - x2 on Foamex with Metal Hooks
EN Floor Stands x2 on Cardboard

*Printed at Ravensboune*
Other LANGs - A3 - x2 of each on heavy matt paper

**Comment by marcwalsh** [comment]
I've sent to print all Pixart assets from this ticket - so removing the Ready to Print label and attaching Printing On-Site

**Comment by sabrinang** [comment]
## Post MozFest Documentation

At MozFest House, the participation guidelines were seen throughout the space A3 and floor displays near entry.

At the weekend, the registration and level 4 big space had large floor displays. The square signs were displayed across the mesh behind registration and EN A3 were seen throughout the space. There were no l10n A3s and this was suppose to be printed at Ravensbourne so unfortunately it was probably forgotten about.

![img_5485](https://user-images.githubusercontent.com/2492510/48601423-91434700-e924-11e8-96cf-43255ac82dc5.JPG)
![dsc02247](https://user-images.githubusercontent.com/2492510/48601531-0a429e80-e925-11e8-8175-0dd6a4067c35.jpg)
![img_5936](https://user-images.githubusercontent.com/2492510/48601487-d9626980-e924-11e8-9a8b-5932047bb794.JPG)
![img_6077](https://user-images.githubusercontent.com/2492510/48601502-ea12df80-e924-11e8-86a1-c0674e53c7cf.JPG)
![dsc02375](https://user-images.githubusercontent.com/2492510/48602007-a9b46100-e926-11e8-9559-2269a60c3a99.jpg)
![img_6074](https://user-images.githubusercontent.com/2492510/48602205-32cb9800-e927-11e8-99e0-6cb03ce0f2ef.JPG)
