### ISSUE TITLE
Swag: Mozilla Festival Stickers

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#57]
### Description:
We want to create some event stickers for MozFest and perhaps for MozFest House too. 

**Main sticker ideas:**
- Mozilla Festival 2018 lockup sticker
- Mozilla Festival Tagline _(Data Done Right)_

**Other ideas include:**
- Generic Mozilla (stickers to reuse at other events)
- 6 MozFest Spaces  
- 3 MozFest Experiences

Sticker supplier: https://www.stickermule.com 

### Previous Applications
We printed on transparent and white stickers for the taglines. The wordmark was transparent. The theme stickers seem to run out quickly. 
![image](https://user-images.githubusercontent.com/2492510/43609503-10b5b528-9659-11e8-8bac-7a65ac687178.png)
![image](https://user-images.githubusercontent.com/2492510/43610357-b12a0878-965a-11e8-9eac-137a6669976c.png)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eZGZTakRTVmF6X2c & https://drive.google.com/open?id=0B4Q8pzCpDS_eanBoNDVaOXc4OVk
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/23

**Comment by sabrinang** [comment]
I made designs for the 6 spaces and 3 experiences as 4cmx4cm square stickers. I also made clear die cut stickers for MozFest 2018, MozFest House and 2 data done right taglines in various sizes around 7cm width. 

@Saallen Please review designs on redpen here: https://redpen.io/p/ome179d47dd8b8e65b

<img width="810" alt="image" src="https://user-images.githubusercontent.com/2492510/46686816-275db200-cbae-11e8-9111-b2829474e9dd.png">

.ai exports on stickermule templates on gdrive here: https://drive.google.com/drive/u/1/folders/1IglhhyENQkdUWQxSaAZzcNkIFtYXAw_5

/cc @gideonthomas

**Comment by Saallen** [comment]
approved

**Comment by sabrinang** [comment]
Note: update Art+Data without space

**Comment by sabrinang** [comment]
Art+Data sticker updated on the same .ai file on gdrive above
![image](https://user-images.githubusercontent.com/2492510/46699890-027a3680-cbd0-11e8-8066-30f090c0bfe1.png)

**Comment by sabrinang** [comment]
@marcwalsh Separate .ai files exported in the folder: https://drive.google.com/drive/u/1/folders/1IglhhyENQkdUWQxSaAZzcNkIFtYXAw_5

### Dimensions

**Clear Die Cut Stickers Folder**

MozFest 2018 Sticker
7.9375 cm x 2.5457 cm

MozFest House
7.4969 cm x 3.7373 cm

Data Done Right Fill
7.0012 cm x 4.3992 cm

Data Done Right Outline
7.0012 cm x 4.3992 cm

**Square Stickers Folder**

Art+Data, Gaming MozFest, Queering MozFest, Decentralisation, Digital Inclusion, Openness, Privacy & Security, Web Literacy, Youth Zone
All are 4cm x 4cm

**Comment by marcwalsh** [comment]
Closing as sent to print - ETA 18th October

Will reopen if the printer requests changes.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

These came in packs and space stickers were distributed to the corresponding wranglers to hand out. I think the extra sets of tagline and lockups were forgotten by swag table people but they have been put out during closing party for people to take.

![dsc02261](https://user-images.githubusercontent.com/2492510/48647761-d6598e80-e9a1-11e8-9951-b2d6a492643e.jpg)
![dsc02263](https://user-images.githubusercontent.com/2492510/48647762-d6598e80-e9a1-11e8-844a-fe61fdd12c9f.jpg)
![dsc02584](https://user-images.githubusercontent.com/2492510/48647782-e40f1400-e9a1-11e8-822b-b497702c5014.jpg)
![45600074342_0761b11b01_z](https://user-images.githubusercontent.com/2492510/48647836-0dc83b00-e9a2-11e8-9875-c3bdc5b9364a.jpg)
![45600542112_84ffc6f6b7_z](https://user-images.githubusercontent.com/2492510/48649662-2cc9cb80-e9a8-11e8-8ebc-09ed0b5674cb.jpg)
