### ISSUE TITLE
Swag: Name Card Stickers (language/pronoun/role/icebreaker)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#58]
### Description:
Create a sticker system that we can use to customize attendee name tags. Decide if these stickers serve as hackable labels or if they are pre-printed. These stickers include:

**Language Stickers**
These help indicate what languages they speak. Having pre-printed languages seemed messy as a lot were not used or participants couldn't find their language and often wrote their own but wanted more space.

**Pronoun Stickers**
This should be an open sticker for participants to fill out

**Role Stickers**
This may be useful at registration to help indicate attendees that are:
Volunteers, Press, Speaker, Wrangler etc. I noticed the press sticker last year.

**Icebreaker Stickers**
Past few years, there have been activities involving stickers for icebreaker games (DNA match, symbol drawing) and they tried to print their labels to match our official ones so let's coordinate our effort here.

### Specifications:
matte (non-glossy) finish so pen/markers can write on them easily and these can be printed on sheets

### Previous Applications
![image](https://user-images.githubusercontent.com/2492510/43610333-a06ffbb4-965a-11e8-9a60-db06d628b76f.png)
![image](https://user-images.githubusercontent.com/2492510/43610398-d2a867ec-965a-11e8-9ec8-85c6a89f8f2a.png)
![image](https://user-images.githubusercontent.com/2492510/43610441-fd5660f2-965a-11e8-82f3-fae26b650b52.png)

### Related Issue
Swag: Name Card ID https://github.com/MozillaFoundation/mozfest-design-2018/issues/62

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eOWIwNnBhSHVrWFk
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/24

**Comment by sabrinang** [comment]
cc/ @acabunoc on this ticket early regarding any sticker related icebreaker activity you might have in mind for this MozFest this year. We can incorporate into planning the design and when we send these to print so you don't have to do it separately?

**Comment by abbycabs** [comment]
Thanks @sabrinang! I'm also open to ideas if you have anything better than DNA matching :)

**Comment by sabrinang** [comment]
@acabunoc I'm working out the sticker system with this year's thematic brand and uniforming the sticker sizes so they can all fit and I thought of an idea of filling out pixels/squares on a 3x3 sticker to match. See below: 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/2492510/45526779-6e15e300-b78d-11e8-99d7-d8325f2f647a.png">

This reminded me of the drawing line icebreaker in 2016 but I don't remember the rules and would need some feedback and help with rules :) Do you have the rules to 2016 line icebreaker game and the poster for reference? Also, what did people win or the CTA for matching?

**Comment by abbycabs** [comment]
@sabrinang I love this! Here's the issue from 2016:
https://github.com/MozillaFoundation/plan/issues/839
We normally offer an amazon gift card - I'll check to see if we can do it again.

I've also started talking with @baricks, hang & ashlyn about tying in with the data game they're running all weekend. I haven't had a chance to dive into what they're doing yet, but maybe they'll see a nice connection?

**Comment by abbycabs** [comment]
@sabrinang - I found the final sticker instruction poster from 2016!

[sticker-instructions-print(1).pdf](https://github.com/MozillaFoundation/mozfest-design-2018/files/2385055/sticker-instructions-print.1.pdf)

**Comment by Saallen** [comment]
@acabunoc  did the gaming team chat with you about incorporating this into their game?
@sabrinang  I am not a fan of the  Role Stickers as it means heirarchy and we are not about that at mozfest- the reason we have press stickers- is so that the participant understands this is a press person who might use their responses

**Comment by gideonthomas** [comment]
@sabrinang, @acabunoc will be the owner of the icebreaker piece so feel free to lean on her for input. 

Related to @Saallen's comment above - let's eliminate the role stickers completely.

**Comment by abbycabs** [comment]
I've read through the Game Design doc from the gaming team (thanks for sending it over @baricks!). 
It was hard to find a nice way to incorporate since the games have different goals. I thought of one option: players are assigned to be a tracker or user based on how they colour in the squares on the icebreaker. This way, players are entered into both games when they pick up an icebreaker sticker. Thoughts @baricks & crew?

For @sabrinang - here are my suggested rules for the poster (open to input)
* Take a sticker
* Colour in **4 squares** (or whatever we think will work. maybe 3?)
* Find a match, get to know them
* Come to the **Open Leadership Zone** with your match to enter the raffle

**Comment by Saallen** [comment]
to confirm- we will reuse press stickers we have in the Moz London office

**Comment by baricks** [comment]
@acabunoc Thanks for taking a look at our doc! I agree that it might be difficult to integrate the games since they have different goals. I like the idea you mentioned, but I do want to make sure people aren't signed up for the game automatically, since this will be entirely an opt-in game.

**Comment by abbycabs** [comment]
Thanks @baricks - that makes sense!

@sabrinang let's move forward with this as a separate game

**Comment by sabrinang** [comment]
**Language stickers**
I have used content from last year https://github.com/MozillaFoundation/mozfest-design-2017/issues/24#issuecomment-334617333  DE, ES, FR, hi-IN, IT, pt-BR & zh-TW. Do you want to include SW this year? I do not have the localized string for "I speak Swahili" if so, we would need to file a l10n issue (greyed out in mockup). They are designed larger as we got feedback it was hear to read/not enough space to write.

**Pronoun stickers**
I did not have content for this but I heard on a wrangler call we'd like prefilled labels instead of just blank ones like last year. I mocked up she/her, he/him, they/them, ask me and blanks.

**Icebreaker sticker**
Thanks for the feedback Abby & Becca, it will be a 3x3 grid sticker.

**Role stickers**
Sarah you mentioned we have press stickers already so I didn't make any.

@Saallen Can you please review these designs and the language/pronoun content you want? Redpen here: https://redpen.io/az1cf1b073e8152f0e

<img width="654" alt="image" src="https://user-images.githubusercontent.com/2492510/46303671-51d1be80-c561-11e8-82e1-d8e91a8a4988.png">


related to issue: https://github.com/MozillaFoundation/mozfest-design-2018/issues/62
/cc @gideonthomas

**Comment by abbycabs** [comment]
Nice, thanks @sabrinang!

For the language stickers, are you planning on printing "I Speak English" ones? I remember last year a bunch of people used the blank ones and wrote it in

**Comment by Saallen** [comment]
Lets not make I speak English but let people edit that themselves @sabrinang

**Comment by gideonthomas** [comment]
@sabrinang Swahili translation for "I speak Swahili" - Nazungumza swahili

**Comment by sabrinang** [comment]
I have exported the designs to include a 1/8" bleed for stickermule but they didn't have a specific label template. I would prefer these designs to be label rolls:

**Rectangle roll labels**
Custom size: 60mm x 30mm
9 designs for language stickers

**Square roll labels**
Custom size: 30mm x 30mm
5 designs for pronoun stickers
1 design for icebreaker sticker

@Saallen Please review the content to ensure it represents the translations correctly and the designs on redpen here: https://redpen.io/jz55dedb48e92c11fd
<img width="335" alt="image" src="https://user-images.githubusercontent.com/2492510/46567864-1ed85380-c8f0-11e8-8b30-582a42a5e293.png">

I've exported these as an .ai files with a stickermule template for printing here: gdrive: https://drive.google.com/open?id=1E82FDDwXMHCpkHsyNehdFZv_jUFVJYrk

**Comment by Saallen** [comment]
Approved

**Comment by sabrinang** [comment]
@marcwalsh Separate .ai files are updated in the folder : https://drive.google.com/drive/u/1/folders/1E82FDDwXMHCpkHsyNehdFZv_jUFVJYrk

### Label Dimensions
**Rectangle roll labels** (All in Rectangle Labels folder)
Custom size: 60mm x 30mm
9 designs for language stickers

**Square roll labels** (All in Square Labels folder)
Custom size: 30mm x 30mm
5 designs for pronoun stickers
1 design for icebreaker sticker

**Comment by marcwalsh** [comment]
Sent to print! ETA - Oct 23rd delivered to Ravensbourne.

Closing ticket and will reopen if printer requires changes.

**Comment by marcwalsh** [comment]
Just an FYI due to time restriants I'm printing standard rectangle / square single versions (not on rolls) of these for MozFest House.

**Comment by sabrinang** [comment]
Ok thanks Marc, I'm glad these will be at MozFest House as well this year!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The name card sticker labels came on rolls they were easier to look for a specific stickers than single die-cut but the dowel/paper towel system didn’t get figured out until later. They had a student make dowel holders but it was more effective if we locked them in horizontally which we fixed later on. 

There was often a volunteer or trash can near by to keep the space a bit tidier.

![20180928-mozfest-sunday-47](https://user-images.githubusercontent.com/2492510/48647583-3d2a7800-e9a1-11e8-844e-407105ee3c0c.jpg)
![44736162885_aca580b866_z](https://user-images.githubusercontent.com/2492510/48647387-a3fb6180-e9a0-11e8-91dc-8deafa384773.jpg)
![img_6081](https://user-images.githubusercontent.com/2492510/48647446-db6a0e00-e9a0-11e8-80e5-aa4ec36f6052.JPG)
![img_6056](https://user-images.githubusercontent.com/2492510/48647466-e45adf80-e9a0-11e8-9755-f26cefdbcb12.JPG)
