### ISSUE TITLE
Swag: Privacy Screen Stickers

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#59]
### Description:
Sticker Mule provided some stickers that cover device cameras for privacy and we should ask if they can provide some again.

Sticker supplier: https://www.stickermule.com 

### Previous Applications
![image](https://user-images.githubusercontent.com/2492510/43610810-0c1d32d6-965c-11e8-9b9d-34a7773d7ba2.png)

**Comment by sabrinang** [comment]
@marcwalsh Can you let me know if StickerMule has a template for these privacy screen stickers? or if they are making themselves then I can prepare some assets for them?

**Comment by marcwalsh** [comment]
@sabrinang - I will send them the style guide and see if they need any more input. Is that okay?

**Comment by sabrinang** [comment]
Sounds great. You can link their proof here if they need input 👍

**Comment by marcwalsh** [comment]
I'm going to close this, and will reopen if a proof is sent through. 👁
