### ISSUE TITLE
Swag: Volunteer T-Shirts

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#61]
### Description:
Design t-shirts for the lovely volunteers so they can be easily spotted by attendees at MozFest and at MozFest House. The front of the shirt may contain this year's branding and tagline. The back will have the #MozFest and it has been preferred to have the date present (example: MozFest 2017 or Mozilla Festival 2017) as it is seen as a collectable by volunteers. :) 

### Format
- Mozilla Festival: Front and Back of T-shirt A4 size (printable area)
- Mozilla Festival House: Front of T-Shirt only and A4 size (printable area)
- Sponsorship - Presenting Festival Partner (location TBD)
- Make sure we can get the quantity in the colour we want early, last year we couldn't get the colour we initially wanted in the amount we needed.

### Previous Applications
https://github.com/MozillaFoundation/mozfest-design-2017/issues/42#issuecomment-342660871
![20171027-mozfest-221](https://user-images.githubusercontent.com/2492510/32968723-1e0f7f52-cb97-11e7-9716-8bdfe6bec7f9.jpg)
![mozfest-house-42](https://user-images.githubusercontent.com/2492510/32522777-86ffb292-c3cd-11e7-9c8d-3bd30a3cd6b6.jpg)

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eSUhZMUZjU0ZRWlE
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/42

**Comment by marcwalsh** [comment]
I'm looking into have two types of t-shirt cuts this year. One is [unisex](https://www.xamax.co.uk/products/tops-trousers-accessories/tops/t-shirts/gildan-softstyler-adult-t-shirt.html) and the other is for [women](https://www.xamax.co.uk/gildan-softstyler-ladies-t-shirt.html).  The delivery spec remains the same. 

Color options that are consistant for both are listed in the image below.

![coloroptionsfortshirts](https://user-images.githubusercontent.com/30226684/43776886-3191aaec-9a49-11e8-9023-e996acf20aa7.png)

**Comment by sabrinang** [comment]
**Sponsorship Update:**

We have a Presenting Festival Partner at MozFest this year and we will need to incorporate their logo. @Saallen has suggested to print the logo on the sleeve of the t-shirt, @marcwalsh can this be done? If so, what are the dimensions of the printable area of the sleeve?

**Comment by sabrinang** [comment]
@Saallen Please review redpen with your preference for 1 weekend (blue) and 1 house (orange) design: https://redpen.io/p/uo05d39f569ed7aa66

I made two designs for the front weekend shirt and two colour options for MozFest House. I don't have details on sleeve printing size for sponsorship but included it along with a back version as an alternative option. The designs front and back are on a A4 print area. PDFs on gdrive here: https://drive.google.com/open?id=1BqUBk5cRtDvx_WP07QHHWGkJTJtFuUt6

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/2492510/46560056-258ea880-c8a7-11e8-9c62-211dfbe62304.png">

**Comment by sabrinang** [comment]
note: export back for A3 as well

**Comment by sabrinang** [comment]
On redpen the following designs received positive feedback:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/2492510/46700703-66056380-cbd2-11e8-96df-19415232d18e.png">

These designs A4 front and back are exported along with A3 back versions for weekend and house. T-shirt colours are Royal Blue and Heather Orange. 

PDFs are exported here: https://drive.google.com/drive/u/1/folders/1BqUBk5cRtDvx_WP07QHHWGkJTJtFuUt6

**Comment by marcwalsh** [comment]
Sent to print!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The shirts turned out to have colour print (seen on the sponsorship logo). The orange and blue shirts stood out in the corresponding venues.

![dsc02255](https://user-images.githubusercontent.com/2492510/48647263-5121aa00-e9a0-11e8-81b7-e160e5acaf8f.jpg)
![20181022-mozhouse-monday-11](https://user-images.githubusercontent.com/2492510/48647232-3d764380-e9a0-11e8-99fa-5e67698c8bb0.jpg)

![dsc02235](https://user-images.githubusercontent.com/2492510/48647250-49620580-e9a0-11e8-97dd-8dbd50a26349.jpg)


![44736604415_463a2ee5b9_z](https://user-images.githubusercontent.com/2492510/48647105-cfca1780-e99f-11e8-8b7f-e5ca52a0a7d5.jpg)

![43832428370_8e8779d36b_z](https://user-images.githubusercontent.com/2492510/48647238-436c2480-e9a0-11e8-803a-dd2b96a9bcb0.jpg)
