### ISSUE TITLE
Swag: Name Card ID

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#62]
### Description:
Refresh the design of the name card ID that participants will wear on their lanyard. From previous year, many people customize their name tag a lot so they may need more "hackable" space. TBD how many versions of the name card we need as we have day tickets and MozFest House.

**Versions TBD**
- Full festival weekend card
- MozFest House card
- Science fair only card
- Saturday only card?
- Sunday only card?

**Front:**
- Mozilla Festival 2018 wordmark and or Tagline
- Empty area (for name, social media handles, stickers etc.)

**Back - subject to change depending on version**
* WiFi: [network name and password]
* Help: Tweet #MozHelp or visit the Info Desk on floors X, X and X.
* Schedule: [schedule shortlink]
* Lunch: From 12:30 - 14:00 on floors X, X and X.
* Coffee: Always hot on Floors X, X and X.
* Connect: #MozFest on Twitter, Instagram, Flickr and [Network Pulse shortlink]
* Safety: Approach the Info Desk on Level 5, email festival@mozilla.org or call [number] (all reports will be held in the strictest confidence)

### Previous Applications
https://github.com/MozillaFoundation/mozfest-design-2017/issues/42
![mozilla-festival-2017-195](https://user-images.githubusercontent.com/2492510/32971892-45cfa7c6-cba4-11e7-9588-cb558197fb6d.jpg)
![mozfest-house-1](https://user-images.githubusercontent.com/2492510/32525454-64bf862e-c3d9-11e7-9450-3669f69ce7e6.jpg)

### Reference from Last Year: 
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/21
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eaGVLSVBua1o5a1k

**Comment by gideonthomas** [comment]
@Saallen to clarify by Friday, Sep 7, if the content on the cards need to be revised.

**Comment by Saallen** [comment]
For 2018 

Versions 

    Full festival weekend card
    MozFest House card
    Science fair only card
    Saturday only card
    Sunday only card

Back - 
    WiFi: [network name and password]
    Help: Tweet #MozHelp or visit the Info Desk on floors X, X and X.
    Schedule: [schedule shortlink]
    Lunch: From XXXX - 14:00 on floors 0, 4, 7 and 9.
    Coffee: Always hot on Floors 0, 5 and 9.
    Connect: #MozFest on Twitter, Instagram, [Foundation.Mozilla.org] and [Network Pulse shortlink]
    Safety: Approach the Info Desk on Level 5, email xxxxx@mozilla.or or call [number] (all reports will be held in the strictest confidence)

The following will not be tolerated at MozFest: violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.
If you don’t respect these guidelines you understand that you will be asked to leave the venue and will not recieve a refund for any ticket purchased.

**Comment by Saallen** [comment]
Need to connect with other teams to confirm
Connect: what are the best re-directs here
Lunch- need to confirm time
Design team- can decide whats on the front

**Comment by sabrinang** [comment]
@Saallen Can you please indicate specific back copy for the 5 specific cards? 

See last year's example below: 2017 Friday card ID excluded points and 2017 House was different. Also please note the back will not be able to fit the 7 points and the guideline paragraph in one.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/2492510/45524868-6c482180-b785-11e8-8eff-d059b4e58dde.png">

**Comment by Saallen** [comment]
Feedback regarding cards
For me this year the CPG are the most important piece to have on the card.

MozFest house is approved.

Is there a different layout we can work with on the fri/weekend piece?

**Comment by Saallen** [comment]
@sabrinang see comment above

**Comment by gideonthomas** [comment]
@Saallen, @sabrinang is going to try to create a layout that includes the cpg in the friday/weekend cards, however, it will definitely look very cramped with all of that info. Will request your approval for that once it is ready.

@Saallen another point of clarification - none of the design for any of these cards are ready yet. The designs you see above are from last year and are going to change for this year. They will require approval once they're done. 
The question is - are we using the same copy for Saturday/Sunday/Full Festival and the same for Science Fair (without coffee and lunch?)?

**Comment by Saallen** [comment]
@gideonthomas 
yes weekend and day tickets (apart from science fair) will contain the same info
Science  fair is with out coffee and lunch

**Comment by gideonthomas** [comment]
@sabrinang here's the info that we condensed so that the CPG guidelines can be added. I think it still might be easier to have them be tiles as opposed to rows on the card so that there is enough space for the CPG, but it's totally up to your discretion.

### Weekend card back

**WiFi**
Network - MozFest2018
Password - Mozfest18

**Help & Safety**
Visit #MozHelp on level 0 and 4
Tweet #MozHelp
Email us at xxxx@mozilla.org

**Coffee**
Always hot on levels 0, 5, and 9

**Lunch**
From 12:00 - 14:00
Served on levels 0, 4, 7, and 9

The following will not be tolerated at MozFest - violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.
If you don’t respect the Mozilla Community Participation guidelines you understand that you will be asked to leave the venue and will not receive a refund for any ticket purchased.

### Friday card back

**WiFi**
Network - MozFest2018
Password - Mozfest18

**Help & Safety**
Visit #MozHelp on levels 0 and 4
Tweet #MozHelp
Email us at xxxxxx@mozilla.org

The following will not be tolerated at MozFest - violence and threats of violence; personal attacks; derogatory language; unwelcome sexual attention or physical contact; disruptive behaviour; influencing unacceptable behaviour.
If you don’t respect the Mozilla Community Participation Guidelines you understand that you will be asked to leave the venue and will not receive a refund for any ticket purchased.

### All cards front

Should include (probably in a corner):

Twitter/Instagram: #MozFest
Pulse: mzl.la/pulse
Mozilla Foundation: mzl.la/foundation

---

By September 25, we should have the following info:
~1. WiFi SSID~
2. Help and safety email address

@Saallen to provide final review for copy

**Comment by Saallen** [comment]
For help and safetly 
amend 
Info desk to  #MozHelp -  0, 4
As we have info desk on all floors and on the main location piece we call it MozHelp

**Comment by Saallen** [comment]
@gideonthomas I amended within your comment.

email address and wifi coming tomorrow

@sabrina we need to be consistant about using floors versus levels. Ill let you decide

**Comment by marcwalsh** [comment]
@sabrinang I'm getting a quote on these from Aspect again this year. I'm going for the dual hooks for the lanyards again, so there will be two holes punched at the top.

**Comment by Saallen** [comment]
@gideonthomas email address they gave me was already taken- just waiting for an update

**Comment by Saallen** [comment]
@gideonthomas does this sound right "If you don’t respect the Mozilla Community Participation Guidelines you understand that you will be asked to leave the venue and will not receive a refund for any ticket purchased"

I think we should amend to 
If you don’t respect the Mozilla Community Participation Guidelines you will be asked to leave the venue and will not receive a refund for any ticket purchased. 

@zee-moz for input- please note they have already agreed to the guidelines when they signed up for a ticket. and it will be at the front desk

**Comment by gideonthomas** [comment]
yeah the second one makes more sense - I'll update if it's not too late for design.

We can't make any changes after this, i.e. let's keep this as the finalized change.

**Comment by sabrinang** [comment]
@Saallen @gideonthomas I've designed the front and the back of the name card for Friday, Saturday, Sunday, Weekend & House. 

The Friday, Saturday, Sunday & Weekend cards have a subtle title to indicate day at the top and features the data done right tagline discretely in the hackable area. I have updated the participation guideline issue but I am still missing network info and email.

I also removed oxford commas to save some space and made `Help & Safety` to `Help/Safety` and `Mozilla Foundation` to `Foundation` to save space as well. Please review if text is ok and the design on redpen: https://redpen.io/p/dg47af378962a0b9fc
![image](https://user-images.githubusercontent.com/2492510/46242308-188c2980-c37c-11e8-98a6-0395b004f6c6.png)


Can you confirm if all other assets are using the term "level" in their assets. I noticed levels are used in https://github.com/MozillaFoundation/mozfest-design-2018/issues/87 so will the schedule use this? If so I can change your floor copy to level.

The large hackable space will accommodate stickers which I will post next week. Example:
![image](https://user-images.githubusercontent.com/2492510/46238703-b6afcd80-c343-11e8-8288-d7c0f365db56.png)

**Comment by Saallen** [comment]
Designes look awsome- thank you

Still waiting on confirmation from Ravensbourne on ssid,
waiting on Mozilla IT to confirm our email address 

The term level comes from @mmmavis locations on schedule. We should agree across all platforms which term to use. Can you both connect and decide, and let us know?

cc @marcwalsh and @gideonthomas

**Comment by mmmavis** [comment]
> The term level comes from @mmmavis locations on schedule. We should agree across all platforms which term to use. Can you both connect and decide, and let us know?

Hey @Saallen ,

I wasn't involved in the location list discussion and I haven't started porting things over to Guidebook yet so I'm assuming when you said "@mmmavis locations on schedule" you meant the location labels we were using **last year**.  The list I was given for this year uses "level". I'll connect with @gideonthomas and @sabrinang on this then.

**Comment by gideonthomas** [comment]
@sabrinang I updated the copy with the WiFi SSID and password and changed "floors" to "levels" and updated the #MozHelp location. Still waiting on the email address.

**Comment by sabrinang** [comment]
@Saallen @gideonthomas I just want to double check that the WiFi SSID for MozFest House is the same as last year (RWNET  1986759)?

**Comment by gideonthomas** [comment]
@mozfesthouse and @marcwalsh  would you be able to confirm the WiFi SSID and password? It's currently blocking design.

@Saallen any updates on the MozHelp email?

**Comment by gideonthomas** [comment]
@sabrinang I updated the copy above with the safety email.

**Comment by sabrinang** [comment]
@gideonthomas I can't find the email in the copy above (I still see xxxx@mozilla.org). Can you please paste the email as a new comment?

**Comment by gideonthomas** [comment]
Hmm weird - ok, the email is festivalsafety@mozilla.org

**Comment by sabrinang** [comment]
Sarah has confirmed the MozFest House WiFi SSID/Password:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/2492510/46553079-6380d200-c891-11e8-9b95-8a92e369dd84.png">

I've exported all name cards with 5mm bleed on each and please punch holes similarly to last year (25mm from side, 10mm from top, 5mm diametre) the position is not indicated on graphic itself:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/2492510/46553405-43054780-c892-11e8-9740-15ae0a1cff44.png">

@Saallen @gideonthomas Please review content on the Print PDF on gdrive here: https://drive.google.com/open?id=1BHA9TYFYjVG6rh3-gHiv1sfxIygb5vAL

If you have any comments you can leave them here or on [redpen](https://redpen.io/p/dg47af378962a0b9fc) for any specific sections.

**Comment by Saallen** [comment]
@sabrinang all designs look really great- We should include data done right at MozFest house too as all event managers have been told about this theme and it should show up here too

**Comment by sabrinang** [comment]
@Saallen Thanks for the review! I didn't know data done right appears at MozFest House too so I have exported the revised MozFest House front in the PDF now to the same Print PDF folder on gdrive here: https://drive.google.com/open?id=1BHA9TYFYjVG6rh3-gHiv1sfxIygb5vAL

**Comment by mozfesthouse** [comment]
@sabrinang these look great!

**Comment by Saallen** [comment]
Awesome- looks so great @sabrinang

**Comment by Saallen** [comment]
Hey @sabrinang just noticing the safety number is not on there- it needs to go under safety email address. Please add to Weekend, Sat and Sun name tags
Phone- +44 (0) 207 855 3030

**Comment by Saallen** [comment]
Plus the email is not right. It should be ...
festivalsafety@mozilla.com

**Comment by sabrinang** [comment]
Email has been updated on fri/sat/sun/weekend cards.
Number has been added to sat/sun/weekend cards.

Updated Print PDF in gdrive folder: https://drive.google.com/open?id=1BHA9TYFYjVG6rh3-gHiv1sfxIygb5vAL

**Comment by gideonthomas** [comment]
@Saallen would you be able to quickly just double check that your review comments were addressed? Otherwise, this is ready to print.

**Comment by Saallen** [comment]
Approved

**Comment by Saallen** [comment]
Hey @sabrinang and @makikoumezawa the printer has requested you add a bleed on the back of each name tag

**Comment by Saallen** [comment]
@gideonthomas adding you in to help get this done asap

**Comment by gideonthomas** [comment]
@natalieworth will be taking this on

**Comment by sabrinang** [comment]
Exported as separated PDFs: https://drive.google.com/drive/u/1/folders/1BHA9TYFYjVG6rh3-gHiv1sfxIygb5vAL

All files have a 5mm bleed with trim marks exported. Regarding the back of name tags, they all have extended artwork on the bleeds just note only house has coloured artwork to the edge while all weekend cards has white artwork to the edge since it has a white border design throughout the design. See below:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/2492510/46887082-8838f480-ce11-11e8-90b1-aa4d82820c7a.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/2492510/46886926-27112100-ce11-11e8-9464-f7dac90bbd91.png">

<img width="738" alt="image" src="https://user-images.githubusercontent.com/2492510/46887034-68a1cc00-ce11-11e8-95f9-f34be7e4b4db.png">

**Comment by gideonthomas** [comment]
Sent to printer. Will reopen if anything else pops up.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

These were distributed at registration and it looks like the the volunteers at sign-up desk had printed a guide for the day passes colours etc. The design had plenty of space for stickers and names. I didn’t hear any feedback on the colour system for day passes so I assume it worked well.

![44736312345_cb79ca9a00_z 1](https://user-images.githubusercontent.com/2492510/48647045-9e514c00-e99f-11e8-9759-a9dd422aff70.jpg)

![dsc02249](https://user-images.githubusercontent.com/2492510/48646864-f20f6580-e99e-11e8-9b5b-20f5f3b32f08.jpg)

![30709684727_ab180f0287_z](https://user-images.githubusercontent.com/2492510/48646777-a957ac80-e99e-11e8-9ee8-7c3d72e8c230.jpg)
![43832423070_b9ed2ed8f5_z](https://user-images.githubusercontent.com/2492510/48646778-ab217000-e99e-11e8-9cef-4f7af40e406f.jpg)
