### ISSUE TITLE
Swag: Lanyard

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#63]
### Description:
Decide on the colour of the lanyard for attendees as well as a colour for attendees who do not want to be on video or photographed. 

**Format**
Last year, we had lanyards with 2-point metal swivel lobster clasp style clip were the main style. Yellow lanyards were used to indicate they did not want photo/video taken of them. Both lanyards have a safety release in the center.

Previous lanyard supplier: https://www.aspinline.co.uk/lanyards/double-ended-lanyards/double-ended-lanyards-15mm-1-colour

### Previous Applications
At registration you can pick up your lanyard with either a purple or yellow lanyard:
![mozilla-festival-2017-195](https://user-images.githubusercontent.com/2492510/32971892-45cfa7c6-cba4-11e7-9588-cb558197fb6d.jpg)
![mozfest-house-1](https://user-images.githubusercontent.com/2492510/32525454-64bf862e-c3d9-11e7-9450-3669f69ce7e6.jpg)

### Reference from Last Year: 
Google Drive Files: n/a
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/45

**Comment by sabrinang** [comment]
@marcwalsh Can the printer make 2-point lanyards with graphics on a flat smooth material? See examples below:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/2492510/45525667-cf878300-b788-11e8-8605-a0512a746889.png">

**Comment by gideonthomas** [comment]
@marcwalsh to mention if this is possible by Sep 20.

**Comment by marcwalsh** [comment]
@sabrinang @gideonthomas - I think budget wise we should stick to plain lanyards again this year as we have a fair amount of additional sponsorship requirements. 

I can get these in any Pantone swatch, let me know what you would colour you would like.

**Comment by sabrinang** [comment]
@marcwalsh 
**Lanyard Colours:** Black & PANTONE Yellow U

Let's go with the black standard plastic hook style with a safety breakaway release in the center. 

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/2492510/46242821-fa292c80-c381-11e8-91a0-d288b706a561.png">

**Comment by gideonthomas** [comment]
@marcwalsh does that work / can this go out to order?

**Comment by marcwalsh** [comment]
Sent to print on Oct 4th.

Closing ticket and will reopen if the printer comes back with comments.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

We had black and yellow lanyards for the weekend and house. Marc has mentioned lanyards are one of the more costly assets we purchase and suggested we could have some collection process at the end for them to be reused or returned. Unsure if this is a common practice or if there are any sanitary concerns but would be a nice way to reduce potential waste.

![dsc02250](https://user-images.githubusercontent.com/2492510/48646084-8fb56580-e99c-11e8-9ebc-0fe0ff9e63fe.jpg)
![dsc02251](https://user-images.githubusercontent.com/2492510/48646088-9217bf80-e99c-11e8-9ab1-c594aa0fa5e1.jpg)
![44736312345_cb79ca9a00_z 1](https://user-images.githubusercontent.com/2492510/48646699-77464a80-e99e-11e8-851d-7052f1595484.jpg)
![45650700811_3a4b886db7_z](https://user-images.githubusercontent.com/2492510/48646703-7b726800-e99e-11e8-9ece-06511e562617.jpg)
