### ISSUE TITLE
MozFest House: Event Wristbands

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#64]
### Description:
Choose various colours for different events and main ones can include the House lockup or type uses Zilla Slab.

### Supplier
https://www.aawristbands.co.uk/?gclid=CM-E94WWk9YCFU-17QodWvYGUw

### Previous Applications
![mozfest-house-21](https://user-images.githubusercontent.com/2492510/32469111-0e3e8de6-c306-11e7-9282-08f96e91bd2a.jpg)

### Reference from Last Year:
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/68

**Comment by sabrinang** [comment]
@mozfesthouse Which events will need individual bands? and how many general/all-purpose wristbands are needed?

@marcwalsh If we are going with https://www.aawristbands.co.uk/?gclid=CM-E94WWk9YCFU-17QodWvYGUw supplier like last year, please use:

- 1" width
- Logo Left of Text
- Using Arial Black text on the Wristband Customiser on aawristbands.co.uk (no custom font option)
- The only design file needed from me is the Mozilla Festival House lockup file:
  - black svg: https://drive.google.com/open?id=1Rnq0DHWm9GHWrvIP31qHtpEpP2TaFgsY
  - white svg: https://drive.google.com/open?id=1RymLkIpvfeWRCwUNMUu0FR1dxci39zjI
- We can make another design for all purpose bands if needed

If you have the event names and any desired corresponding colours I can create a mockup.

**Comment by mozfesthouse** [comment]
@sabrinang @marcwalsh 
The following need individual ones - can keep colours the same as last year for the ones we did before (viewsource etc) and not worried about the colours of the others if they are suitably different.
Modern Campaign Fundamentals - x60
Public Service & Internet Health - x60
Mozilla (we can use these for MoFo internal meetings/Mozilla staff) - x200 - maybe in black to match the logo?
#causeascene conf - x80
#causeascene coaching fair - x80
MisInfocon - x130
OpenNews -x130
Viewsource - x170
Ushahidi - x60
MozFest House - @marcwalsh do you know how many generic ones we had printed last year? my feeling is to go for about 2000 having very roughly counted up all events and their predicted (max) numbers.

**Comment by sabrinang** [comment]
@mozfesthouse Please review band colour and design

- Mozilla internal usage band is black using white Mozilla logo
- MozFest House generic bands are either neon orange or neon pink (in case you need two unique ones)
- MisInfocon, Open News, View Source are the same
- Note: The #causeascene bands are different (red and purple) but if they need to be more similar it can be red and warm red but they would look very similar

Please see image mockup for reference:
<img width="1330" alt="mozilla-festival-house-2018_wristbands-colours 2x" src="https://user-images.githubusercontent.com/2492510/45978969-7b8b6280-c002-11e8-8fd0-386fc3a5b086.png">

**Wristband Customiser preferences:**
- 1" width
- Logo Left of Text
- Using Arial Black text on the Wristband Customiser on aawristbands.co.uk (no custom font option)
- Assets are here (BW MozFest House lockup, W MozFest House text, W Mozilla Logo): https://drive.google.com/open?id=1t2hPIzpzcTiX2zTn7xyb8DmPsUsi72uK

/cc @marcwalsh @gideonthomas

**Comment by gideonthomas** [comment]
@marcwalsh do the guidelines provided above work?

**Comment by marcwalsh** [comment]
@gideonthomas @sabrinang - these look good to me. I need to check if they are able to print white. If not are we okay to go with black for the standard MozFest House bands?

**Comment by sabrinang** [comment]
@marcwalsh If black will not work can we go with silver? (a bit more distinct than white)
<img width="141" alt="image" src="https://user-images.githubusercontent.com/2492510/46029757-22c2d500-c0a9-11e8-9b32-a4cf10b3b8cc.png">

**Comment by marcwalsh** [comment]
@sabrinang sorry I mean for the orange and pink wristbands - we probably will not be able to print using white ink. Can these be printed in black instead?

**Comment by sabrinang** [comment]
@marcwalsh Yes black ink for orange and pink wristbands will work fine 👍

**Comment by gideonthomas** [comment]
@marcwalsh this is ready for print right?

**Comment by marcwalsh** [comment]
SENT TO PRINT!

🕺

**Comment by sabrinang** [comment]
## Post MozFest Documentation

There was some additional colours like white and gold wristbands with the mozilla wordmark. The wordmark didn't have the highlight box. The festival house word marks also didn’t have the highlight box on them either.

![dsc02252](https://user-images.githubusercontent.com/2492510/48645916-fbe39980-e99b-11e8-8310-09c0f5647806.jpg)
![img_5515](https://user-images.githubusercontent.com/2492510/48645990-3cdbae00-e99c-11e8-8272-2ebdcf2d7300.JPG)
