### ISSUE TITLE
MozFest House: Customizable Letter Poster Signage

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#65]
### Description:
Make a pattern/textured pattern in Google Slides that can be remixed to make letter size posters. This is a generic template to be remixed by Lucie and Marc. This is printed on site.

### Previous Applications
<img width="953" alt="image" src="https://user-images.githubusercontent.com/2492510/31746233-25f57e94-b41b-11e7-8090-0201c5d1710e.png">

![mozfest-house-36](https://user-images.githubusercontent.com/2492510/32518529-b2823c3c-c3be-11e7-8998-b82c821ed131.jpg)

### Reference from Last Year
Github issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/65
GSlides: https://docs.google.com/a/mozilla.com/presentation/d/10EvyxVRryx9i1VPNIaexpy_49SwuOAHx4_h6KcA0Xt8/edit?usp=sharing

**Comment by sabrinang** [comment]
@mozfesthouse I designed two styles of customizable letter size (8.5"x11") signs for MozFest House events to be used in frames by doors and free standing signs at RSA. The border is thicker as the metal frame covers ~1cm of it. 

I made it a template on google slides so you can type in the name of the event and print it on site similarly to last year. Gslide template here: https://docs.google.com/presentation/d/1-b3PnA5Q-sQo-gWBaSaV8PJYOX8OgwFxBPnAP8IgGAU/edit?usp=sharing

<img width="881" alt="image" src="https://user-images.githubusercontent.com/2492510/45986280-6bce4700-c01f-11e8-9caa-62f93552a0ed.png">

Lucie please review the doc, confirm dimensions are correct and let me know if it fits your needs for this year.

/cc @gideonthomas

**Comment by gideonthomas** [comment]
@mozfesthouse can you review this?

**Comment by mozfesthouse** [comment]
@gideonthomas yes this works  -thats perfect, thank you

**Comment by gideonthomas** [comment]
@mozfesthouse would you prefer to leave this open for reference, or can we close this?

**Comment by mozfesthouse** [comment]
@gideonthomas hi - actually would you leave open - just for reference only though is fine!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

Both templates were used and it looked like it was well used in the space in bus stop signs and mounted frames at the RSA.

![img_20181027_232458](https://user-images.githubusercontent.com/2492510/48650243-41a75e80-e9aa-11e8-829b-4cc36757d4e4.jpg)
![dsc02224](https://user-images.githubusercontent.com/2492510/48650247-4704a900-e9aa-11e8-876b-a0114946ed2f.jpg)
![dsc02228](https://user-images.githubusercontent.com/2492510/48650248-4704a900-e9aa-11e8-8c49-8724f9c582dc.jpg)
![dsc02229](https://user-images.githubusercontent.com/2492510/48650249-4704a900-e9aa-11e8-8105-ee0089030a7b.jpg)
![dsc02211](https://user-images.githubusercontent.com/2492510/48650253-4a983000-e9aa-11e8-9ae4-d2cbe21c71f0.jpg)
