### ISSUE TITLE
MozFest House: Branded Pillar Totems & Folding Screen

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#66]
### Description:
Incorporate colour and house lockup to bring in some branding into the space. This can coordinate with the palette of the coups and lighting for the pillars. We used the vertical lockup for these last year.

### Format
- 2x [Totem 3 XL](https://www.pixartprinting.co.uk/displays/point-of-sale-displays/totem-3-xl/)
- 8x [Totem 3](https://www.pixartprinting.co.uk/displays/point-of-sale-displays/totem-3)

### Previous Application
![mozfest-house-39](https://user-images.githubusercontent.com/2492510/32509491-4f55c74e-c3a2-11e7-8385-d2a044bb99fb.jpg)

### Reference from Last Year
Google Drive: https://drive.google.com/open?id=0B4Q8pzCpDS_ecmFEM3dyZjlqdFE
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/66

**Comment by sabrinang** [comment]
After chatting with @marcwalsh @gideonthomas, we will be going with a large folding screen style https://www.pixartprinting.co.uk/wide-format/printing-flat-bed-rigid-materials/folding-screen/ and small 3 side totem https://www.pixartprinting.co.uk/displays/point-of-sale-displays/totem-3/

@marcwalsh Since the folding screen is custom, can you provide the widthxheight and fold layout to generate a template for me?

@mozfesthouse Please confirm these are the two styles of branded stands we are going with?

**Comment by sabrinang** [comment]
**Totem Design**
I used the lockup, logo and wordmark each on a separate side for variety:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/2492510/45971257-77a11580-bfed-11e8-863d-68dbbf3fb30a.png">

PDF on gdrive here: https://drive.google.com/file/d/1sx4HXwSQTp5dqVM9M8vTVNjulTPFGEkM/view

@mozfesthouse Please review

@marcwalsh & @mozfesthouse Please confirm if we are doing a folding screen since I heard we are not doing TotemXL this year and provide dimensions/template from PixArt if so as it is a custom size.

/cc @Saallen @gideonthomas

**Comment by marcwalsh** [comment]
@sabrinang we won't need the Totem XLs this year, I may order a couple of extra of these just incase.

**Comment by sabrinang** [comment]
@marcwalsh Can you confirm that we do not need a [ folding screen](https://www.pixartprinting.co.uk/wide-format/printing-flat-bed-rigid-materials/folding-screen/) design for MozFest House?

**Comment by marcwalsh** [comment]
@sabrinang sorry, misread your comment. We will do the folding screen instead.

[Template available here](https://github.com/MozillaFoundation/mozfest-design-2018/files/2416253/pixartprinting-template-large-format-folding-screen-2.pdf)

**Comment by sabrinang** [comment]
**Folding Screen Design**
I iterated on the folding screen design and having variations of the logo or lockup in the centre panel. If this folding screen is behind the table again having just the logo might be nice if it is surrounded by the lockups elsewhere etc. 

@mozfesthouse Please review which folding screen design logo you prefer?

redpen here: https://redpen.io/p/zqd51853a81db0640e
PDFs on gdrive here: https://drive.google.com/drive/u/1/folders/1w2KYDBK9po70zY18rh_uvzzrsx4oL0Fb
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/2492510/46105708-93422280-c18b-11e8-8d7b-8882a9b045c0.png">

/cc @gideonthomas

**Comment by gideonthomas** [comment]
@mozfesthouse throwing this on your radar again for review

**Comment by mozfesthouse** [comment]
Hi @gideonthomas  - I like the middle one best - no.2

**Comment by mozfesthouse** [comment]
@gideonthomas @sabrinang re: the totems - these are great so @marcwalsh  - just the size L ones instead to go in the individual rooms - was that the size we had last year?

**Comment by sabrinang** [comment]
@mozfesthouse regarding totems @marcwalsh mentioned https://github.com/MozillaFoundation/mozfest-design-2018/issues/66#issuecomment-424417013 previously we are not going with XL totems the design above is just Totem 3.

**Comment by gideonthomas** [comment]
@mozfesthouse can you also approve the totem design: https://drive.google.com/file/d/1sx4HXwSQTp5dqVM9M8vTVNjulTPFGEkM/view

**Comment by mozfesthouse** [comment]
@gideonthomas Totem design approved

**Comment by marcwalsh** [comment]
Sent to print! 🕺

Closing and will reopen if there are any changes required.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

Sadly, the totems never arrived (stuck in customs or lost at airport?). The folding screens were printed incorrectly (mozilla wordmark should be white) and the lockup somehow got positioned on the fold differently for each folding screen. I’m unsure what went wrong here and how this could of been fixed?

![dsc02246](https://user-images.githubusercontent.com/2492510/48650098-bfb73580-e9a9-11e8-8f57-2e1308dc938a.jpg)
![img_20181027_214322](https://user-images.githubusercontent.com/2492510/48650162-f8570f00-e9a9-11e8-8119-8bf6b6815c5e.jpg)
