### ISSUE TITLE
MozFest House: Table Cloths

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#67]
### Description:
We may reusable the ones from last year if we still have them. These are found in the coffee area and registration table.

### Previous Application
![mozfest-house-39](https://user-images.githubusercontent.com/2492510/32521579-d16cdb70-c3c8-11e7-96ef-434cb927875c.jpg)

### Related Issue
Wayfinding: Registration Table Banner (or Table Cloth) #43

### Reference from Last Year
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/64

**Comment by sabrinang** [comment]
@marcwalsh @mozfesthouse 
If these table cloths are still around can we reuse them? If not the white logo file can be found here for reprint: https://drive.google.com/open?id=1RymLkIpvfeWRCwUNMUu0FR1dxci39zjI

**Comment by sabrinang** [comment]
@marcwalsh @mozfesthouse
Have these table cloths been found or sent to print?

/cc @Saallen @gideonthomas

**Comment by marcwalsh** [comment]
@sabrinang @gideonthomas  We're getting these into the office next week. If we're using the same as last year, I can reorder the same again if we were happy with those. 

Either way, I think you can stand down on this and I'll order if required.

Cheers!

**Comment by marcwalsh** [comment]
Sent to print as we couldn't find them in storage!
 
Closing.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

These were reprinted and I hope we save them for next year!

![dsc02241](https://user-images.githubusercontent.com/2492510/48650037-8d0d3d00-e9a9-11e8-93f1-0d69db158dd9.jpg)
![dsc02258](https://user-images.githubusercontent.com/2492510/48650038-8d0d3d00-e9a9-11e8-8d44-87c72679de13.jpg)
