### ISSUE TITLE
MozFest House: Welcome & Sponsors Screens

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#68]
### Description:
Screen in main entrance that displays welcome, lockup and sponsors. If we want something on all 3 screens it can only be a static picture. We can put slides or video on the screens, however this will only appear on one screen not all three.

### Previous Application
![mozfest-house-47](https://user-images.githubusercontent.com/2492510/32470124-e4396822-c30a-11e7-90b7-20b729108d82.jpg)

### Reference from Last Year
Google Drive: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eekpfcWQ3eHZRdVk?usp=sharing
GIthub Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/67

**Comment by sabrinang** [comment]
@mozfesthouse Do we have a sponsor to display at MozFest House this year? and what would you like to be displayed on the other screens?

**Comment by mozfesthouse** [comment]
@sabrinang  - I have just asked the RSA and I'll come back to you asap

**Comment by sabrinang** [comment]
@gideonthomas This would be the location of sponsorship if we have it at MozFest House

**Comment by mozfesthouse** [comment]
@sabrinang @gideonthomas - hi, we have the screen for the Saturday night only. It is x2 separate screens so we need x3 powerpoint files of either one design or x3. If there is no sponsor we could have the central one with "Welcome" and the x2 either side with the designs.

**Comment by gideonthomas** [comment]
The sponsor would be our Presenting Festival Partner - Private Internet Access
Their logo can be found here: https://drive.google.com/open?id=1-qpa-oANqW6xFgtitQc2VZyUlSTpRihe
Link: privateinternetaccess.com

The screen can probably say something like:
Presenting Festival Partner
\<logo\>
\<link\>

**Comment by sabrinang** [comment]
@mozfesthouse I've designed it similarly to last year with a welcome, lockup and sponsor screen. Please review designs.

@gideonthomas For last year's slide we had "sponsored by" so I thought to include "sponsored by our Presenting Festival Partner" for this year with logo + url. Please review does this work for sponsors?

redpen here: https://redpen.io/p/kn2a6fd97d70c7319c
gdrive JPGs here: https://drive.google.com/open?id=1uGkqmKFjcH7mNO7X4rU8HTBAqQhse6NK
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/2492510/46050040-a64ee700-c0e6-11e8-946f-c859c0f494ad.png">

**Comment by gideonthomas** [comment]
That looks fine to me @sabrinang (one small nit - the title doesn't contrast well with the background so might not be great for accessibility, but not critical to fix at all)! 

Tagging @Saallen for approval of the sponsor screen above.

**Comment by Saallen** [comment]
looks great to me

**Comment by gideonthomas** [comment]
@mozfesthouse are the files above good to go (can I mark this as done)?

**Comment by gideonthomas** [comment]
@mozfesthouse checking in again on this, can we close this ticket?

**Comment by mozfesthouse** [comment]
@gideonthomas good to close :)

**Comment by sabrinang** [comment]
## Post MozFest Documentation

Did these get displayed?
I was late to the Saturday night party so I didn't take photos of it

**Comment by gideonthomas** [comment]
@Saallen do you happen to know about this ^

**Comment by Saallen** [comment]
Yes, I think so..let me check photos
