### ISSUE TITLE
MozFest House: Coffee Cups

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#69]
### Description:
We will have thousands of branded cups at MozFest house since the space can't have branding on walls the cups are an opportunity to have it showcased.

### Previous Applications
![mozfest-house-5](https://user-images.githubusercontent.com/2492510/32521940-359f3b6e-c3ca-11e7-843e-a994c3c8de8a.jpg)

### Reference from Last Years
Google Drive: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eTnpDVHRoZnJLXzQ/view?usp=sharing
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/54

**Comment by sabrinang** [comment]
@marcwalsh Can you supply a cup template from the printer if it is different this year?

**Comment by marcwalsh** [comment]
@sabrinang sorry for the delay. The artwork template is attached. 

[8oz-Double-Wall.pdf](https://github.com/MozillaFoundation/mozfest-design-2018/files/2392528/8oz-Double-Wall.pdf)

**Comment by sabrinang** [comment]
@mozfesthouse I designed a coffee cup that features the logo in the centre and mozilla festival house repeats along the bottom black border. 

Redpen here: https://redpen.io/p/vr6d2faaae3725217e
Gdrive file here: https://drive.google.com/open?id=1rgzuO7ljsuHYgymZ7cXVRLbqJZWcl7-q
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/2492510/46048504-8ddace80-c0de-11e8-8468-730a893a7bc3.png">

Lucie, please review design.

/cc @gideonthomas

**Comment by mozfesthouse** [comment]
@sabrinang these look great to me @marcwalsh assuming they are the same size as last year?

**Comment by marcwalsh** [comment]
@mozfesthouse yes they are 8oz :)

**Comment by marcwalsh** [comment]
Sent to print on Oct 4th.

Closing ticket and will reopen if the printer comes back with comments.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

Coffee cups had white lids instead of black and was a good conversational piece while being additional decor in the space. From the photos, it looked like these cups were delivered on or used on Wednesday onwards.
![45650491411_78fca1e22c_z](https://user-images.githubusercontent.com/2492510/48291535-b539f080-e42b-11e8-8c23-77085f5a9e0e.jpg)
![45650488111_534bc56a65_z](https://user-images.githubusercontent.com/2492510/48291536-b66b1d80-e42b-11e8-9b85-c957063a9a20.jpg)
![31778091718_a8cc037c20_z](https://user-images.githubusercontent.com/2492510/48291543-bbc86800-e42b-11e8-9683-8310daed9a24.jpg)
![dsc02245](https://user-images.githubusercontent.com/2492510/48291594-e6b2bc00-e42b-11e8-88d7-1991f428b6a7.jpg)
