### ISSUE TITLE
Swag Ideas

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#7]
### Description:
Brainstorm what we want to give as swag. We can consider physical swag (favouring more minimal or sustainable options) and consider digital swag (reducing environmental impact and depends on the sponsors). Also, consider how much effort it may require for our volunteer to assemble or organize it together and reduce this dependency when possible. We will start from what we had last year and the feedback received.

Google Doc here: https://docs.google.com/document/d/1DEPZuepkichBzHHmM87zH7fkqBKAgoAAY9rrrNz2s-A/edit?usp=sharing

### Reference from Last Year: 
https://github.com/MozillaFoundation/mozfest-design-2017/issues/3

**Comment by bunnybooboo** [comment]
Seeds. Seeding ideas. Growing networks. eg: https://www.totalmerchandise.co.uk/products/details/Kraft-Paper-Seed-Pockets and https://www.totalmerchandise.co.uk/products/details/5-Stick-Seed-Packs

EDIT: this may be a terrible idea for international travel!

**Comment by bunnybooboo** [comment]
Cloth fabric frisbees.

**Comment by bunnybooboo** [comment]
Shoe laces.

**Comment by bunnybooboo** [comment]
Option to forego swag and donate to a marginal/diversity/privacy initiative instead.

**Comment by bunnybooboo** [comment]
Artisanal tea bags.

**Comment by plwt** [comment]
Hi.  I am working on a Mozilla Festival swag idea with some people in MoCo, but so that we can consider the costs/implementation, what is the expected number of attendees at MozFest this year?

**Comment by sabrinang** [comment]
@marcwalsh do you know the max number of tickets on sale for MozFest weekend this year? Just wondering how much swag we accommodate for the weekend (I'm guessing around 2000)?

**Comment by sabrinang** [comment]
@consuelamckenzie @marcwalsh
We can refer to the [google doc](https://docs.google.com/document/d/1DEPZuepkichBzHHmM87zH7fkqBKAgoAAY9rrrNz2s-A/edit?usp=sharing) and any comments on this issue for Thursday's swag meeting. 

Please come with ideas or add to the doc before the meeting for swag so we can consolidate ideas and issues can be filled once we have decided what we want.

**Comment by plwt** [comment]
It would be great if you get some idea of how many people are expected at the weekend part of MozFest.  Time is starting to get a bit tight, but hopefully the idea that is being looked into may still be very much on the table.

**Comment by kgiori** [comment]
If there is any budget available to buy Mozilla branded uSD cards, I would be happy to place the order for them, pre-loaded  with a Raspberry Pi image to turn an RPi into a Mozilla Things Gateway (private IoT gateway for your smart home).

**Comment by marcwalsh** [comment]
Hey @kgiori I'm afraid this isn't something we can cover in the MozFest budget, however if the ET team have the budget for it, we're happy to facilitate it once it arrives at the festival.

**Comment by gideonthomas** [comment]
Finalized https://github.com/MozillaFoundation/mozfest-design-2018/issues/90
