### ISSUE TITLE
MozFest House: Window Vinyls

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#70]
### Description
Last year the contractor made a large vinyl on the back window and in the narrow windows on the bottom floor.

### Previous Applications
![mozfest-house-19](https://user-images.githubusercontent.com/2492510/32969513-4636d5cc-cb9a-11e7-881b-366106676a4c.jpg)
![mozfest-photos-1](https://user-images.githubusercontent.com/2492510/32970094-63db9b24-cb9c-11e7-8bcb-d870db0a3ed4.jpg)

### Reference from Last year
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/69

**Comment by sabrinang** [comment]
**Window Branding Concepts**
I have used last years file dimensions and generated concepts for windows that you can pass on to your contractor to export. PDF on gdrive here: https://drive.google.com/open?id=1sIhXcC_2TYfApeteX9g3J4TegZLIVXD2

AI file here: https://drive.google.com/open?id=1s5KYSoGznyyoMqUQyGklqWW_XHqG9Wx0

Please download fonts and other reference from the style guide: https://docs.google.com/presentation/d/1o7jM58fhQEcLH-Y6JuUq2XqoJ5vCqXxEvdnGCT1JYpc/edit?usp=sharing

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/2492510/45970337-16784280-bfeb-11e8-9ebf-6bca278979c1.png">

@mozfesthouse Please review and pass on to contractor when ready

/cc @Saallen @gideonthomas

**Comment by mozfesthouse** [comment]
@sabrinang this is with the signage company for an approval for your review - thanks!

**Comment by gideonthomas** [comment]
@mozfesthouse would you be able to clarify your comment above? Who is going to approve this design (slash when will it be approved by)? Once it's approved, is there anything else @sabrinang needs to do?

**Comment by mozfesthouse** [comment]
@sabrinang @gideonthomas  -hi sorry for pack of Clarity - the designs Sabrina has done are with our signage printer  - before they print anything, they always send back a final proof for @sabrinang's review, so I'll do this next week when I receive them. This will be firstly the window vinyls and then later the wayfinding for the Saturday night party.

**Comment by mozfesthouse** [comment]
HI @sabrinang @gideonthomas    - the signage provider is struggling to download the ai/illustrator files for the vinyls and the wayfinding - is there a chance you could share these with him directly ? His email is  ben@blueantdesign.com?

**Comment by sabrinang** [comment]
I shared access with that email on the gdrive folder as well as sent him an attached link to the email just in case.

**Comment by sabrinang** [comment]
@mozfesthouse the .ai files also has been shared with you in a previous comment https://github.com/MozillaFoundation/mozfest-design-2018/issues/70#issuecomment-424081216 

Here is the link again: https://drive.google.com/file/d/1s5KYSoGznyyoMqUQyGklqWW_XHqG9Wx0/view?usp=sharing

The folder is shared with Ben's gmail too so he is able to access it. If he isn't able to, please download and forward it to him.

**Comment by gideonthomas** [comment]
@mozfesthouse once this has been ordered, let me know so I can close this ticket.

**Comment by mozfesthouse** [comment]
@sabrinang would you just approve the window vinyls - 
![mfhouse_window_vinyls_2018](https://user-images.githubusercontent.com/40634524/46953530-056c9f80-d086-11e8-9583-b7febd7e93d1.png) - the window pane measurements needed to be adjusted slightly (my fault - they were measured wrong last year and needed to be updated on github), but they have kept the proportions the same on the design, just need to check you are happy with it before its printed?
Lucie

**Comment by sabrinang** [comment]
@mozfesthouse Thanks for clarifying the panes are not squared proportion. For this context only, it's fine it doesn't have the squared design then and looks fine as the logo is not stretched. Note the screenshot has a square selected/blue border on the left just check it isn't on the final design. 

When possible, can you include the finalized print files and dimensions so we have the correct reference for the next year? Thanks Lucie!

**Comment by marcwalsh** [comment]
(Just changing labels over to see where I'm still requiring items to print)

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The main window design had adjusted proportions. We should include the finalized print files and dimensions so we have the correct reference for the next year. https://github.com/MozillaFoundation/mozfest-design-2018/issues/70#issuecomment-429903180

One of the window designs got printed on vinyl banner similar to the floor banners for the stairwell.

![dsc02240](https://user-images.githubusercontent.com/2492510/48650997-b203af00-e9ad-11e8-9bc7-54ac32c0327e.jpg)
![img_20181027_214735](https://user-images.githubusercontent.com/2492510/48651023-d5c6f500-e9ad-11e8-9f51-bb744becb52e.jpg)
![img_20181027_232007](https://user-images.githubusercontent.com/2492510/48651027-d95a7c00-e9ad-11e8-90b1-af9d20736c78.jpg)
![20180926-mozfest-saturday-107](https://user-images.githubusercontent.com/2492510/48651057-f0996980-e9ad-11e8-90c1-12f644544940.jpg)
![img_20181027_231857](https://user-images.githubusercontent.com/2492510/48651634-aa91d500-e9b0-11e8-8766-6a10c80660d5.jpg)
![img_20181027_214313](https://user-images.githubusercontent.com/2492510/48651017-cc3d8d00-e9ad-11e8-8072-12631ef80da1.jpg)
![img_20181027_214653](https://user-images.githubusercontent.com/2492510/48651690-f5135180-e9b0-11e8-934e-6d7a1d70d84b.jpg)
