### ISSUE TITLE
MozFest House: Printed Backdrops, Podiums and Schedule

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#71]
### Description
The MozFest House contractor made backdrops, podium covers and standing schedule last year.

### Previous Applications
![mozfest-house_podium](https://user-images.githubusercontent.com/2492510/33190733-fd7dd374-d064-11e7-90ca-842505f0da6c.jpeg)
![image](https://user-images.githubusercontent.com/2492510/43614642-183a87be-9669-11e8-9cf0-12afb5e818b8.png)
![mozfest-photos-1](https://user-images.githubusercontent.com/2492510/32970094-63db9b24-cb9c-11e7-8bcb-d870db0a3ed4.jpg)

**Comment by sabrinang** [comment]
**Backdrop, Podium, Panel & Doors Concept**
I have used last years file dimensions and generated concepts for environmental branding that you can pass on to your contractor to export. PDF on gdrive here: https://drive.google.com/open?id=1sCM7Gp8dkbypc-gaERyA0T-MFY8hPzBj

I don't have the standing schedule file but your contractor can use the textures and type to create one. AI file here: https://drive.google.com/open?id=1s5KYSoGznyyoMqUQyGklqWW_XHqG9Wx0

Please download fonts and other reference from the style guide: https://docs.google.com/presentation/d/1o7jM58fhQEcLH-Y6JuUq2XqoJ5vCqXxEvdnGCT1JYpc/edit?usp=sharing

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/2492510/45970854-686d9800-bfec-11e8-8af5-b41b3a0f3379.png">

@mozfesthouse Please review and pass on to contractor when ready

/cc @Saallen @gideonthomas

**Comment by gideonthomas** [comment]
@mozfesthouse can you review this please?

**Comment by gideonthomas** [comment]
@mozfesthouse has this been ordered for print? If so, can we close?

**Comment by mozfesthouse** [comment]
@gideonthomas yes pls close!

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The backdrops didn’t get printed for the stage space but it looked good without it. The podium added nice colour to the space. They made a schedule on foamex displayed on an easel. 

![dsc02217](https://user-images.githubusercontent.com/2492510/48650974-9b5d5800-e9ad-11e8-8214-3a40c87a73a8.jpg)
![20180922-mozhouse-wednesday-12](https://user-images.githubusercontent.com/2492510/48651311-2b4fd180-e9af-11e8-8f30-3be8b0ea66fb.jpg)
![img_20181027_214653](https://user-images.githubusercontent.com/2492510/48651019-cfd11400-e9ad-11e8-834c-98ec7e910fe8.jpg)
![20180926-mozfest-saturday-106](https://user-images.githubusercontent.com/2492510/48651058-f2632d00-e9ad-11e8-9fa5-19e56df917dc.jpg)
