### ISSUE TITLE
MozFest House: Lighting and Decor

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#72]
### Description
Give colour palette documentation for this year's visual direction to inform the lighting and decor of the RSA space.

**Comment by sabrinang** [comment]
@mozfesthouse Please use warm palette (orange, yellow and pinks from [style guide](https://docs.google.com/presentation/d/1o7jM58fhQEcLH-Y6JuUq2XqoJ5vCqXxEvdnGCT1JYpc/edit#slide=id.g40cb16b354_0_49)) for lighting and furniture.

They can be similar to last year: 

![image](https://user-images.githubusercontent.com/2492510/45970593-cbaafa80-bfeb-11e8-8e59-e37536e0388a.png)
![image](https://user-images.githubusercontent.com/2492510/45970617-d49bcc00-bfeb-11e8-97d4-41b34f7c58ca.png)
![image](https://user-images.githubusercontent.com/2492510/45970632-dfeef780-bfeb-11e8-88eb-ef12a3365b1b.png)

**Comment by mozfesthouse** [comment]
thanks @sabrinang - if I was to pick x2 colours for the cushions (and do a few black) - which pantone colours would you suggest?

**Comment by sabrinang** [comment]
@mozfesthouse Last year's colours were nice too if that is what's available. If you want to match the orange and pink in the style guide it would be Pantone 137 U + Pantone 232 U but I don't know how that will translate to fabric instead of uncoated paper but as long as it is in the spectrum of pink and orange it will tie in just fine 👍 Nice, black cushions would be a great accent too! 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2492510/45980805-db383c80-c007-11e8-84a6-944f62b7d3b0.png">

**Comment by mozfesthouse** [comment]
@sabrinang this is great :)

**Comment by mozfesthouse** [comment]
@sabrinang please can I have the MF House logos as .eps and .pdf files?
Thanks!

**Comment by mozfesthouse** [comment]
@sabrinang  - just been chased to get the files for the house as .eps and .pdf so they can move forward for with the cushions - I know you are super busy but let me know if its possible to get these? Thanks!

**Comment by sabrinang** [comment]
@mozfesthouse Logos exported in [MozFest House lockups folder](https://drive.google.com/open?id=1Hn8HJIcdfnoUnwF1NtI9O2xZa1W8XQ3x):

EPS folder: https://drive.google.com/drive/folders/10xAe82YN7R2uURGQ4nwHukWCvrmEuzN-?usp=sharing
PDF folder: https://drive.google.com/open?id=10LqXhJ5Cd8V0q3-GaqtOXRKzy35IyhEK

**Comment by gideonthomas** [comment]
@mozfesthouse do you need any other decor designs or what @sabrinang has provided is sufficient?

**Comment by mozfesthouse** [comment]
@sabrinang @gideonthomas - I have everything now thank you. I shall keep the furniture plain - in black and white so the colours stand out. As per last year I shall do a few of the small poofs in the same oranges and pinks as the cushions.

The cushions proof is here - are you OK with this  - also adding @Saallen 
https://drive.google.com/file/d/1fvgH2AlMq-sNWcCVhcEkPlXvykWfUmsY/view?usp=sharing

**Comment by sabrinang** [comment]
@mozfesthouse Yes, the placement of the logo and 3 cushion design colours look good. 👍

**Comment by gideonthomas** [comment]
@mozfesthouse are we good to close this ticket?

**Comment by sabrinang** [comment]
## Post MozFest Documentation
Throughout the RSA space, we had custom decor that included cushions, ottomans, lighting and flowers since we can not post anything on the walls of the venue.

Cushions came in orange, pink and black. They had plump filling with a velvet finish and good quality overall.
![dsc02212](https://user-images.githubusercontent.com/2492510/48290138-bb799e00-e426-11e8-896d-ca1c7d5b49bc.jpg)
![31777778478_547f59eb34_z](https://user-images.githubusercontent.com/2492510/48290120-b3b9f980-e426-11e8-9221-4042fdc72aad.jpg)
![45599596752_8fbbd5214b_z](https://user-images.githubusercontent.com/2492510/48290126-b61c5380-e426-11e8-8bb5-afd4c5d24a43.jpg)

Ottomans came in deep orange and fushia and there was plenty more than last year.
![dsc02238](https://user-images.githubusercontent.com/2492510/48290174-d5b37c00-e426-11e8-931c-dd8aa815f980.jpg)

Lighting and sconces were warm hues of orange and pink as well throughout the spaces. One of the large rooms and ceiling lights in blue and it would be cool if we can customize that as well.
![dsc02215](https://user-images.githubusercontent.com/2492510/48290141-bcaacb00-e426-11e8-9685-b0c39000a15a.jpg)
![dsc02216](https://user-images.githubusercontent.com/2492510/48290148-c5030600-e426-11e8-9b62-e46fe144c278.jpg)

There were plenty of flowers that added a beautiful natural touch to the space in tones of oranges and pinks too.
![dsc02236](https://user-images.githubusercontent.com/2492510/48290169-d0563180-e426-11e8-8d95-ba456076f17e.jpg)
![dsc02246](https://user-images.githubusercontent.com/2492510/48290204-e82db580-e426-11e8-8527-d1887e0da9ca.jpg)
![dsc02237](https://user-images.githubusercontent.com/2492510/48290172-d2b88b80-e426-11e8-992e-c2cf7acbb086.jpg)
![dsc02244](https://user-images.githubusercontent.com/2492510/48290201-e49a2e80-e426-11e8-9a54-3b3d4abff0fd.jpg)
![img_20181027_231915](https://user-images.githubusercontent.com/2492510/48650954-75d04e80-e9ad-11e8-8b24-e97bdee9189f.jpg)
