### ISSUE TITLE
Swag: Festival Guide

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#73]
### Description:
The festival guide is a key and informative part of the MozFest swag. Last year's festival guide included a pocket for a separate map.

**Format:**
This year we can decide on a format and consult https://aspectpress.co.uk/

**Timeline:**
[Aug 13-Sept 7] Creating content and writing copy
[Sept 7] Content deadline and copy draft
[Sept 14] Print Concept Specifications + Pagination Outline
[Sept 21] Copy revisions & Design draft version 1
[Sept 28] Copy editing & Design revision version 2
[Oct 5] Final review and export finalized files 
[Oct 8] Send to print

### Content
All content will be linked to: https://github.com/mozilla/mozillafestival.org/issues/1031

### Previous Applications
![image](https://user-images.githubusercontent.com/2492510/43616461-757c5846-9671-11e8-8f2b-9cdcb643eafe.png)
![image](https://user-images.githubusercontent.com/2492510/43616450-639be6fa-9671-11e8-9955-fe1940c1f527.png)

### Related Issue
Notebook? Map? TBD

### Reference from Last Year: 
Google Drive Files: https://drive.google.com/open?id=0B4Q8pzCpDS_eaVE4RWhndUFBcTQ
Github Issues: https://github.com/MozillaFoundation/mozfest-design-2017/issues/43
Github Issue Cover: https://github.com/MozillaFoundation/mozfest-design-2017/issues/71

**Comment by sabrinang** [comment]
Update we met to chat about the content for the festival guide and outlined it in google doc here: https://docs.google.com/document/d/1_VQ4ye6r_8JJ6RAXhATcMXOTciUq0owStN-tkPPEPms/edit

@makikoumezawa and I can work on a rough pagination outline for @zee-moz to refer to as she writes.

**Comment by makikoumezawa** [comment]
Here's the Google slide link for the flat-plan overview (pagination outline) that we are referring to:
https://docs.google.com/presentation/d/1a9Ejiayb9lk_RCb6Hr6DLRtFCBPDuEzBdzZp4NKHbo4/edit?usp=sharing

**Comment by makikoumezawa** [comment]
Here is the revised version for @zee-moz based on our meeting we had this afternoon:
https://docs.google.com/presentation/d/1a9Ejiayb9lk_RCb6Hr6DLRtFCBPDuEzBdzZp4NKHbo4/edit?usp=sharing

**Comment by makikoumezawa** [comment]
### **Printing Concept Specifications (Festival Guide 2018)**


![screen shot 2018-09-13 at 3 36 38 pm](https://user-images.githubusercontent.com/41972873/45521271-1ddd5780-b772-11e8-8b06-f7b9fb6c2d2c.png)


I would need some confirmation about paper stock and printing method and would like to stick to a similar format as 2017 Festival Guide. Please feel free to add or adjust for the quote request. 

Festival guide will have more pages than past years (+40pp). There is also more inserts that will add on to the bulkiness so keep in mind there is not much space in the back pocket. 

**Product Type:** Booklet

**Size:** A5 148 x 210 mm (5.8 x 8.3 in)

**Paper Count:** 40 pages total (including cover) 10 sheets

**Paper Stock:** 

- Cover: 200 gsm (Please confirm if this is the same paper stock from 2017 Festival Guide)

- Main pages: 120 gsm (Please confirm if this is the same paper stock from 2017 Festival Guide)

- Paper should be uncoated

**Printing Method:** Digital Printing

- Same printing method from 2017 Festival Guide

- Aspect Press: Digital Xerox 770 or Perfect CPC 2000

**Finish/ Bindery:** Saddle-stitched

**Quantity:** 2600

**Cover:** Built-in pocket for Inserts (Map, MozFest House, Facilitators, Fellowship & Awards). Please stick with the same dimensions for the pocket as 2017 Festival Guide. 


![screen shot 2018-09-13 at 3 31 20 pm](https://user-images.githubusercontent.com/41972873/45521349-672da700-b772-11e8-9931-d89aa0990fdd.png)


### **Printing Concept Specifications (Inserts)**

There will be possibly 4 inserts that will be included in the back pocket of the festival guide. The 4 inserts include:

1. Map
2. MozFest House Guide
3. Facilitators
4. Other Inserts (Fellowship & Awards)

### **Requirements**

- Inserts must be smaller than the festival guide. 

- Maximum size to fit in pocket should be 117 x 200 mm (tucks in nicely and won’t stick out from the guide.)

- Folded map can be expanded from a pocket-friendly A6 size to an A3 sheet. They will be the same size as the A6 Notebooks. 

- MozFest House content is still in the works. Mozfest House insert need two options depending on how much content will be included. First option is a booklet guide (heavy content and word count). Second option is a single page postcard insert (less content and word count). 

- Facilitators and Fellowship & Awards can be single page postcard inserts if they only include a name list data and word art. These inserts need two options also depending on how much or little content. First option is for a maximum size and will be in the middle height size and stack nicely in between the Folded map and MozFest House Insert. Second option is for a minimum size and will be A6 size. 


![screen shot 2018-09-13 at 3 31 36 pm](https://user-images.githubusercontent.com/41972873/45521461-defbd180-b772-11e8-9d88-39d2def9a5e0.png)


**1. Map:** Folded Map (Same size as notebook)
- **Folded Size:** A6 105 x 148 mm (4.13 × 5.83 in)
- **Unfolded Size:** A3 297 x 420 mm (11.69 x 16.53 in)
- **Printing Method:** Litho-printing on recycling paper? (if possible)
- **Paper Stock:** 120 gsm (same weight as main pages and not too flimsy when folded)



![printing_concept_specifications__festival_guide_2018__-_google_docs](https://user-images.githubusercontent.com/41972873/45522180-4cf5c800-b776-11e8-9c77-532b86e75ca5.png)



**2. MozFest House:** Booklet Guide or Single Page Postcard Insert
(Please stick with the same size as 2016 Space Wranglers Bios Booklet)
- **Booklet Guide Size:** 117 x 200 mm (4.6 x 7.9 in) 
- **Single Page Postcard Size:** A6 105 x 148 mm (4.13 × 5.83 in)

**3. Facilitators:** Single Page Card Stock Insert (Large or Small)
- **Single Page Postcard Maximum Size:** 117 x 174 mm
- **Single Page Postcard Minimum Size:** A6 105 x 148 mm (4.13 × 5.83 in) 

**4. Fellowship & Awards:** Single Page Postcard Insert (Large or Small)
- **Single Page Postcard Maximum Size:** 117 x 174 mm
- **Single Page Postcard Minimum Size:** A6 105 x 148 mm (4.13 × 5.83 in)

**Comment by sabrinang** [comment]
@Saallen Please see and review Makiko's comment above for print concept specifications for the festival guide.
@marcwalsh Please let us know if this is enough information you need to get a quote from Aspect Press and if they are also doing the inserts as well or if it is through a separate printer.

/cc @gideonthomas

**Comment by Saallen** [comment]
@sabrinang and @makikoumezawa Working on the mozfest house insert and it will contain a list of 23 events. So I imagine it will be content heavy. Who requested the fellowship and awards insert?
I can chase them for an update on content specs.

**Comment by sabrinang** [comment]
@Saallen The fellowship & award insert is a request here: https://github.com/MozillaFoundation/Design/issues/280#issuecomment-420763584 

The design team is responsible for creating it but we want to set the standard for dimensions for any insert included so once ours concept is confirmed we can let them know about dimensions.

**Comment by Saallen** [comment]
Great- do you need anything from me here now to continue? @sabrinang

**Comment by gideonthomas** [comment]
Content is ready for this here: https://docs.google.com/document/d/1E7hHGmiqRS9ggZR71TQPNEpdY0BlNfi7IiaQTyO4Abk/edit#.

Couple of important notes about the content:
1. ~Skip the sponsors section for now (or design based on existing sponsors). We're updating the list and the final list to print will be ready by September 28 latest.~
2. The insert content is still TBD I believe. Will update asap.

**Comment by sabrinang** [comment]
@makikoumezawa 

After chatting with @marcwalsh the print specifications (stock, format, size, method) are fine and he mentioned a few things to note:
- **Cover:** It should be prioritized, delivered first since the custom pocket and gluing process may take more time
- **MozFest House insert:** Since this content comes late, it can be done in a different paper stock than the guide (lighter) so it can be done at a separate printer independent of the main guide’s print deadline
- **Map:** Provide folding instructions/guidelines for how it should be folded by the printer
  - FYI Map content still needs to be confirmed but since this is done by Aspect Printer we need it earlier than later

**Comment by gideonthomas** [comment]
Location information that will be needed for the map will be provided latest by Tuesday Sep 25.

**Comment by makikoumezawa** [comment]
Here is a rough pagination draft including all the copy and content. 

https://docs.google.com/presentation/d/1bvVxf2aCBNS8CdUjWk-cYxwxdnEKnAe1GxssPhn0G7A/edit?usp=sharing

@zee-moz, I would like to get some feedback about the order set up and page pacing. Please review and add comments to the doc.

/cc @gideonthomas, @sabrinang, @Saallen

**Comment by makikoumezawa** [comment]
@marcwalsh please review this Map Folding Instructions

![screen shot 2018-09-21 at 1 00 38 pm](https://user-images.githubusercontent.com/41972873/45903527-de7cbf80-bd9e-11e8-86e4-e39556965dd4.png)

Use an A3 (297 x 420 mm) paper size sectioned into an 8-page fold.

1. Start with an accordion fold with the front cover and back cover panel. Each panel will be 105 mm wide sectioned to 4 panels. 

2. Fold in behind from half point

3. Map will be folded into an A6 size (148 x 105 mm)

**Comment by gideonthomas** [comment]
Hi @makikoumezawa, on page 38 - the last page facing the back cover, we want to include the Presenting festival partner.

Would you be able to add that to that page on its own?

So that page would simply have the following content:

---

Presenting Festival Partner
<logo: https://drive.google.com/open?id=0B0_l7CrAmxgBVWQ2OHpzZkhZTE1HT1JlbFNwV2NOczkzaWJn>

---

Let me know if you have any questions or concerns. Thanks!

**Comment by marcwalsh** [comment]
Hi @makikoumezawa - great to be working with you! :) @sabrinang @gideonthomas - FYI as well!

I've requested the deadlines for the festival guide booklet and maps for tomorrow so will update you once I have those. 

For the MozFest House, Facilitators and Fellowships / Awards - as we're getting tighter on deadlines and I'd rather Aspect focus on the the critical elements (Name Tags, Guide Booklet and Map). We should use [Pixart Small Custom Format prints](
https://www.pixartprinting.co.uk/digital-litho-printing/printing-other-formats/) for the inserts instead. They have a 300GSM recycled card which I have a sample of and it's pretty nice!

I'm afraid there isn't a template for custom sizes but here is an [instruction sheet here](https://github.com/MozillaFoundation/mozfest-design-2018/files/2416097/instruction_172_en.pdf) and an [A6 template is available here](https://github.com/MozillaFoundation/mozfest-design-2018/files/2416111/pixartprinting-template-small-format-custom-formats.pdf).

Deadlines for PIxart ideally will be 10 days prior - so around the 11th October, however I can do it with 4 working days at a push, but ideally I wouldn't leave anything MozFest House that close.

**Comment by zee-moz** [comment]
@gideonthomas @sabrinang @makikoumezawa 

I've added the following comments/changes to the festival content doc, and discussed with Sabrina and Makiko:

- A couple of lines explaining wranglers in the Explore MozFest Spaces section, to provide context for the people you see on the space pages. We also discussed adding some copy to those pages, small, next to the page number: Wranglers & Spaces or something like that. 

- Swapped the order of the "next steps" and "thanks" copy on the last page.

- We also chatted about further ideas for the "activity pages:" sticker passport, can't miss sessions, post-it note HQ and doodle page... We decided to distribute throughout to break up text heavy sections. 

@gideonthomas see the doc for a question for you about the 20 graphic in the addendum section. 

It's shaping up great, thanks everyone for working on this! 💯

**Comment by marcwalsh** [comment]
Hi @sabrinang @makikoumezawa @gideonthomas deadlines listed for all elements below (dates listed are EOP UK Time):

I've pushed as much as possible, if I can get the cover before that date, I might be able to push the internal content by a day. 

- Festival Guide - 11th October 
- Folding Map - 18th October 
- MozFest House Insert - 11th October 
- Facilitators Insert - 18th October (19th at a push)
- Fellowships / Awards - 18th October (19th at a push)

Also FYI the stock for the festival guide is the following:
Cover: Vision 250 gsm Text: Vision 120 gsm

**Comment by gideonthomas** [comment]
@sabrinang and @makikoumezawa - the content for the MozFest House insert is ready here - https://docs.google.com/document/d/1_U-psv7RO6BaRpu3s58L1iDivh3pH5lgzVKZAUw7Fbc/edit#

**Comment by gideonthomas** [comment]
I've separated out the map and inserts into separate tickets to keep track of deadlines better. This ticket is now mainly for the festival guide itself.

**Comment by gideonthomas** [comment]
@Saallen could you review the festival guide (minus the inserts/map): https://docs.google.com/presentation/d/1bvVxf2aCBNS8CdUjWk-cYxwxdnEKnAe1GxssPhn0G7A/edit#slide=id.g435dacd56d_0_0

**Comment by makikoumezawa** [comment]
@Saallen Here is the pdf draft 2 version: https://drive.google.com/open?id=1prSFOdTI20Gxrjp8GOu-hWgmV6JU8iSV

If you have any comments or feedback please add them to the google doc

/cc @gideonthomas, @sabrinang

**Comment by sabrinang** [comment]
@makikoumezawa Kevin has made an update to the speakers https://github.com/mozilla/mozillafestival.org/issues/1124 `Remove Ramy Raoof as MozFest speaker`

**Comment by Saallen** [comment]
Hey- the design is gorgeous- looks really great- thank you

I added comments to the document @makikoumezawa

**Comment by sabrinang** [comment]
@makikoumezawa I forwarded you an email with Kristine Grivcova's photo. Please let us know if you any other outstanding content.

**Comment by sabrinang** [comment]
@makikoumezawa https://github.com/mozilla/mozillafestival.org/issues/1130#issuecomment-427497855
@KevZawacki updated the Dialogues & Debates with a new speaker. If it is possible to add it to the guide, please refer to the linked issue.

**Comment by makikoumezawa** [comment]
@Saallen  Here is the final draft for a final review before sending to print on the 10th: https://docs.google.com/presentation/d/1bvVxf2aCBNS8CdUjWk-cYxwxdnEKnAe1GxssPhn0G7A/edit?usp=sharing

/cc @sabrinang @gideonthomas

**Comment by sabrinang** [comment]
I left you comments on the doc @makikoumezawa. Overall, the guide is looking amazing, clean and thoughtfully structured. Thank you for including additional content last minute as well and breaking up the sections with hackable pages to give some space in between. There are a few minor copy inconsistencies I noted (punctuation, capitalization) that I am unsure of myself that I hope Sarah or Gideon can help clarify.

**Comment by Saallen** [comment]
HI @makikoumezawa Could you please share this final draft as PDF for me to review? Find it very hard to review in the slide deck as cannot read the type properly

**Comment by makikoumezawa** [comment]
@Saallen Sabrina and I resolved all the comments from the google docs and is updated as a final draft.

Here is a pdf version so you can revise for a final review before sending to print: https://drive.google.com/open?id=16hCMyJnktAilN9S9fcUi3QqSiN-z2cuN

/cc @sabrinang @gideonthomas

**Comment by gideonthomas** [comment]
@makikoumezawa would you be able to replace `www.foundation.mozilla.org` to just `foundation.mozilla.org`?

**Comment by Saallen** [comment]
@makikoumezawa I made one final edit request on MozFest tips page but otherwise
AWESOME WORK- its gorgeous 🌷

**Comment by gideonthomas** [comment]
Added a small edit on page 3 as well. Let me know once these changes are done. Thanks @makikoumezawa!

**Comment by Saallen** [comment]
Partnership team made a request for sponsors logos to be ordered different on page 33 @makikoumezawa 
Presenting partner first
Then science fair partner

@gideonthomas did partnerships team raise the alignment with you also?

**Comment by gideonthomas** [comment]
@Saallen Nope, this is the first I'm hearing about this. This is the last change we're making to the guide though since @makikoumezawa needs to work on other stuff as well.

**Comment by Saallen** [comment]
OK- 100% UNDERSTAND

**Comment by gideonthomas** [comment]
@makikoumezawa would you be able to put the final exported file here...it will go to print tomorrow.

**Comment by makikoumezawa** [comment]
@gideonthomas **Here is the High-Quality Print Version of the Festival Guide:** 
https://drive.google.com/open?id=1sxxqW-zUZnAIRKdYLmBtw_auoGRh1cR7

**Package Folder:** https://drive.google.com/open?id=1ojZVYCfF7sva3xI8ZOTZE1RYJfVmEb-Y

I've adjusted the color palette to a Pantone color (The Plus Series Color Bridge Uncoated) so the color will look different on screen. 

**For online purposes, I've made an Online PDF version:** 
https://drive.google.com/open?id=1sxxqW-zUZnAIRKdYLmBtw_auoGRh1cR7


/cc @Saallen @sabrinang

**Comment by Saallen** [comment]
GONE TO PRINT - WHOOOPPP Great work everyone 🎆

**Comment by sabrinang** [comment]
Hey @makikoumezawa can you upload the digital online pdf as single pages? Issu generates single pages from your double page spreads so it's looking strange:
http://g.recordit.co/AHqimBozvS.gif

**Comment by makikoumezawa** [comment]
@sabrinang Here is the online pdf as single pages: https://drive.google.com/open?id=1sxxqW-zUZnAIRKdYLmBtw_auoGRh1cR7

**Comment by sabrinang** [comment]
Thanks!
