### ISSUE TITLE
App: Branding for Schedule (Guidebook)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#74]
### Description:
If we are using Guidebook's branded app this year there are a few design elements to prepare for it: 
- [ ] App Icon
- [ ] Promotional Image
- [ ] Splash Screen
- [ ] Homepage Logo
- [ ] Cover Image
- [ ] App Screenshots
- [ ] Colour Scheme
- [ ] Menu Icons

Guidebook has [support](https://support.guidebook.com/hc/en-us/articles/115002968827) on how we can customize as we build the app.

Note: We should pay attention to colours and icon size to ensure that they are legible and accessible. 

### Previous Application
![overview](https://user-images.githubusercontent.com/2492510/30724700-94d423d8-9ef4-11e7-9b1d-f9b8053c9b41.jpg)

### Reference from Last Year:
Github Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/20

**Comment by marcwalsh** [comment]
@sabrinang - the delvierables have slightly changed this year as we are no longer having a native app on iOS / Android.

### 1. Guidebook 'Space' Logo
_Shown in the 'Guidebook' mobile app when users search for the guide._
- 1024 x 1024 px (reccommended)

### 2. Theme Colours
_The UI (hex) colors of the guide itself, which are required for:_
- Base (Used for highlights, eg selected date on calendar or check boxes)
- Space Background (Used for main body background)
- Main Text (Used for headings in page/paragraph text)
- NavBar Background (Used for backgrounds of the banners on pages and navigation menu)
- NavBar Text (Used for titles inside the banners on pages / nav)
- NavBar Icon (Used for burger bar etc)

_Reference Image:_
![screen shot 2018-09-21 at 18 02 50](https://user-images.githubusercontent.com/30226684/45895269-a7230880-bdc8-11e8-86ba-67dd007ed573.png)

### 3. Cover Image and Brand Icon
_Shown on General Information screen when user opens the guide_
- Cover Image - 1440 px wide by 720 px tall
- Brand Icon - 232 px wide by 192 px tall

![screen shot 2018-09-21 at 18 06 18](https://user-images.githubusercontent.com/30226684/45895515-4942f080-bdc9-11e8-924b-40851931fef2.png)

### 4. Sidebar Icon Colour (Hex)
_Custom (hex vaule) colour of pre-designed icons in Guidebook reference images below:_

![screen shot 2018-09-21 at 18 05 42](https://user-images.githubusercontent.com/30226684/45895558-6b3c7300-bdc9-11e8-8707-d75e9126c5f3.png)

### 5. Icon for Experiences

**Comment by gideonthomas** [comment]
@mmmavis what is the latest time by which you need these designs by?

**Comment by mmmavis** [comment]
According to our [original timeline](https://docs.google.com/document/d/1ahAMhq_GKBKR1velvE6iQgrZBC07OA6xoXpdaU3w8I4/edit#heading=h.gjjtaveus8fg) Guidebook schedule will go live on October 8th Monday. Icons and banner etc need to be added to Guidebook before then and with Sarah's approval.

**Comment by Saallen** [comment]
@marcwalsh  can you confirm from the top comment what asset we need for this year since the app layout is slightly different?
@gideonthomas and @marcwalsh  once this list is updated -can you review last years assets to see what we can reuse??

**Comment by marcwalsh** [comment]
@Saallen @gideonthomas the only requirements are those in my [comment](https://github.com/MozillaFoundation/mozfest-design-2018/issues/74#issuecomment-423608423) and ideally an icon for experiences (something similar to what is in the style guide). 

We can reuse the App Icon for this year's Guidebook 'Space' Icon.

**Comment by Saallen** [comment]
It is hard to read in that format so to confirm here for @sabrinang 

- [ ] Space logo
- [ ] Cover image/branding
- [ ] Theme colours
- [ ] sidebar icon colour
- [ ] icons for spaces
- [ ] icon for experiences 


Icons for spaces is the same as last year

**Comment by sabrinang** [comment]
I logged into builder.guidebook.com to figure out what can be changed. I made changes to our guidebook space logo, space theme, guide cover, guide icon and I kept the pre-designed icon colour the same. I made an about icon, spaces/experiences mosaic icon, updated spaces colour and proportions and an experiences icon. I also made headers for the list: 
![mozilla-festival-2018_schedule-app_overview](https://user-images.githubusercontent.com/2492510/46380711-34335080-c658-11e8-98ba-152d6c192be2.png)

@Saallen @marcwalsh Please review in guidebook https://builder.guidebook.com/#/guides/147793/ as I have made all these updates there.

Assets available on gdrive here: https://drive.google.com/open?id=150g5I2fbaY2YYhC4yBA3y1Eh0LOenhh1

/cc @gideonthomas

**Comment by sabrinang** [comment]
@marcwalsh gave me some feedback that the wordmark was cropped in the menu view as it is used as background that is cropped-in/lightened so it should just be a texture. I updated guidebook with a version without the wordmark:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/2492510/46426476-93926e80-c6f3-11e8-9d4a-f6038ae02b79.png">

**Comment by gideonthomas** [comment]
Closing as completed!

**Comment by sabrinang** [comment]
Post MozFest Note: additional related guidebook icon requests in issues #103 #102
