### ISSUE TITLE
MozFest & MozFest House: Sponsorship Design Assets

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#75]
### Description
An overview of the sponsorship that is included in design assets this year. 

#### Presenting festival partner only

- x8 Floor Displays (2 Food/Bar Area, 2 Registration Table Area, 2 Lounge Area, 2 Backup) https://github.com/MozillaFoundation/mozfest-design-2018/issues/8
- x6 Posters (4 behind registration table are near entrance (welcome) sign, 2 Backup) https://github.com/MozillaFoundation/mozfest-design-2018/issues/84
- 1x Step & Repeat (near entrance area) https://github.com/MozillaFoundation/mozfest-design-2018/issues/85
- x2 Floor Sticker (2 for elevator entrance)  https://github.com/MozillaFoundation/mozfest-design-2018/issues/48 
- inclusion on Volunteer T-Shirt https://github.com/MozillaFoundation/mozfest-design-2018/issues/61

#### All Partners

- inclusion on Motion Graphic Video https://github.com/MozillaFoundation/mozfest-design-2018/issues/36
- inclusion on Sponsorship Banner https://github.com/MozillaFoundation/mozfest-design-2018/issues/49
- inclusion on [website](https://mozillafestival.org/team/sponsors) https://github.com/mozilla/mozillafestival.org/issues/1027
- inclusion on printed festival guide https://github.com/MozillaFoundation/mozfest-design-2018/issues/73
- inclusion on screens near stage https://github.com/MozillaFoundation/mozfest-design-2018/issues/39

### MozFest House Assets may include
- Welcome & Sponsor screens: https://github.com/MozillaFoundation/mozfest-design-2018/issues/68

### Sponsorship Swag
- Sticker Mule Webcam Stickers https://github.com/MozillaFoundation/mozfest-design-2018/issues/59

### Deadlines 
Here are some dates that we need hi-res (vector) logos and sponsorship titles received by to be included in the print or digital asset (if it is received later than this date it'll be miss being sent to print, for digital assets they may be included depending on capacity):

| Asset        |  Sponsors Assets Must Be Received By |
| ------------- |:-------------:| 
| Website | Oct 8 |  
| Printed Festival Guide | Sept 28 |
| Motion Graphic Video |  Oct 8 |
| Banner | Sept 28 |
| Screens near stage | Oct 15 |
| MozFest House Screens | Oct 8 |

### Reference to Last Year
GIthub Issue: https://github.com/MozillaFoundation/mozfest-design-2017/issues/2#issuecomment-345362215

**Comment by sabrinang** [comment]
@jcbarajas /ccing you on this issue so we can coordinate on these print/digital deadlines listed above. Can you check the list of desired assets you want to incorporate sponsorship? If there are more please comment on this issue and I'll file the corresponding asset issues so it can be included and triaged.

You can link any sponsorship logos (vector format prefered) you receive to be included in design on this issue.

**Comment by Saallen** [comment]
linking in @consuelamckenzie can you take this to your next sponsorship meeting.

**Comment by consuelamckenzie** [comment]
@Saallen This is already in play for the sponsorship team, they are aware of the following dates and all are we reiterate during every meeting since August 28th.

Asset | Sponsors Assets Must Be Received By
Website | October 8
Printed Festival Guide | September 28
Motion Graphic Video | October 15
Banner | October 1
Screens near stage | October 15
MozFest House Screens | October 8
Guidebook | September 30

All dates listed at the top of our meeting notes google doc.

We will continue to go through the dates up until each deadline...!

C

**Comment by consuelamckenzie** [comment]
@gideonthomas 
I hear these dates might change - Can you please confirm the dates you need all assets by?
Thanks!
Consuela

**Comment by Saallen** [comment]
Confirming on the 19/9/18 we have the following sponsorship partners and committed to branding these assets.

@consuelamckenzie to confirm what exactly "branded lounge space" means + can this be something the sponsor does on their own ?? And what does ""Reg Area Sponsor sign"" mean?
@consuelamckenzie to confirm that the design assets listed below is accurate.

cc @sabrinang  and @marcwalsh for information and ensuring we are matching our commitments
@gideonthomas 

### List of partner design assets

**Presenting festival partner** 
  - [ ] Shown in Video reel
  - [ ] Festival guide callout
  - [ ] Reg Area Sponsor sign (2 big ones)
  - [ ] Presenting sponsor logo on entrance sign
  - [ ] Logo on marketing materials
  - [ ] Logo on food and bar
  - [ ] Logo on Step and Repeat
  - [ ] Logo on volunteer T-shirt
  - [ ] Registration table branding
  - [ ] Giant logo floor sticker
  - [ ] Branding lounge space

**Science Fair partner**
- [ ] Shown in Video reel
- [ ] Festival guide callout
- [ ] SCIENCE FAIR POSTERS on 6th and 4th floors (2 big ones)

**Closing party partner**
- [ ] Shown in Video reel
- [ ] Festival guide callout
- [ ] at event entrance- 4th floor sunday night party

**Youth Zone partner**
- [ ] Shown in Video reel
- [ ] Festival guide callout
- [ ] In entrance to the Youth zone only

**Comment by gideonthomas** [comment]
@sabrinang would you be able to edit the comment above with the updated list of assets (and qty) you will be creating?

**Comment by sabrinang** [comment]
@gideonthomas I updated my original comment for this issue and filed new issues for the presenting festival partner assets.

**Comment by consuelamckenzie** [comment]
@gideonthomas @Saallen @sabrinang 

After my conversation and emails with the sponsorship team, they would like you to design the assets and send over to them for approval.

For further clarity on the items above here is an updated [sponsor benefits spreadsheet ](https://docs.google.com/spreadsheets/d/1Ws27D7OjGuoOG9AHbmR3InYFBuRgntJOu-y3ERQxEL0/edit#gid=0) with descriptions for each item. This is the detail of what was promised to our sponsors.

The sponsorship team would like the Presenting Partner logo to show up on in as many places as possible with their titling - Presenting Festival Partner. 
This is throughout MozHouse and MozFest.

The lounge space is what the team are devising with PIA.
In terms of design, we need to make sure the 2,500  Mozfest attendee's know we have a lounge space, where it is, and that it's clearly marked when you get there. 
The PIA logo has to be displayed in the festival guide, directional signage, entrance signage.

There are three options they have given us for branding - the choice of which logo fits where is yours.
[Logo](https://drive.google.com/open?id=1-qpa-oANqW6xFgtitQc2VZyUlSTpRihe) Private Internet Health

If further explanation is needed @jcbarajas can talk you through the detail.

**Comment by gideonthomas** [comment]
### Sponsor List

Name | Image | Partnership Type | Link |
--- | --- | --- | --- |
Sticker Mule | [Image](https://www.stickermule.com/assets/images/stores/sticker_mule/press/downloads/logo-colored/Sticker-Mule-logo-SVG-e614db0061.zip) | Closing Party Partner | [Link](https://mule.to/mozfest-2018) |
Private Internet Access | [Image](https://drive.google.com/open?id=1-qpa-oANqW6xFgtitQc2VZyUlSTpRihe) | Presenting Festival Partner | [Link](https://www.privateinternetaccess.com/) |
Internet Society | [Image](https://assets.internetsociety.org/Styleguide/#page/029105C2-BD06-4184-9C413CD5BAB15B76) | Science Fair Partner | [Link](https://www.internetsociety.org/) |
Samsung | [Image](https://drive.google.com/open?id=1SDf1_ndD_cH42uBU39QZJ6iYvhyqHZ9s) | Youth Zone Partner | [Link](https://www.samsung.com/uk/apps/samsung-internet/) |

Here are the list of design assets that need to be created. If there is more than one partner logo for an asset, you do not need to create separate assets for each logo.

## Digital

| Asset | Dimensions | Presenting Festival Partner | Science Fair Partner | Youth Zone Partner | Closing Party Partner | Qty (tentative) |
|---|---|---|---|---|---|---|
| Website logo - MozFest Homepage, Sponsor Page, Ticketing page | N/A | | | | | |
| Logo in motion graphic video | N/A | | | | | |

## Print

| Asset | Dimensions | Presenting Festival Partner | Science Fair Partner | Youth Zone Partner | Closing Party Partner | Qty (tentative) |
| Logo in Festival guide on sponsor page | N/A | | | | | |
| Logo in Festival guide on last page | N/A | | | | | |
| Sponsorship Banner | 3ft wide x 8ft tall | | | | | |
| MozFest House Entrance sign (floor display) | N/A | | | | | |
| Science Fair Entrance sign (floor display) | N/A | | | | | |
| Sponsorship Banner | N/A | | | | | |

**Comment by Saallen** [comment]
Hey @sabrinang and @gideonthomas I updated where the science fair partner and the sunday party partner posters will be located- please note this is not in the lobby as origionally thought

**Comment by gideonthomas** [comment]
## FINAL ASSET LIST

### Sponsor List

Name | Image | Partnership Type | Link |
--- | --- | --- | --- |
Sticker Mule | [Image](https://www.stickermule.com/assets/images/stores/sticker_mule/press/downloads/logo-colored/Sticker-Mule-logo-SVG-e614db0061.zip) | Closing Party Partner | [Link](https://mule.to/mozfest-2018) |
Private Internet Access | [Image](https://drive.google.com/open?id=1-qpa-oANqW6xFgtitQc2VZyUlSTpRihe) | Presenting Festival Partner | [Link](https://www.privateinternetaccess.com/) |
Internet Society | [Image](https://assets.internetsociety.org/Styleguide/#page/029105C2-BD06-4184-9C413CD5BAB15B76) | Science Fair Partner | [Link](https://www.internetsociety.org/) |
Samsung | [Image](https://drive.google.com/open?id=1SDf1_ndD_cH42uBU39QZJ6iYvhyqHZ9s) | Youth Zone Partner | [Link](https://www.samsung.com/uk/apps/samsung-internet/) |

Here are the list of design assets that need to be created. If there is more than one partner logo for an asset, you do not need to create separate assets for each logo.

## Digital

| Asset | Dimensions | Presenting Festival Partner | Science Fair Partner | Youth Zone Partner | Closing Party Partner | Qty (tentative) |
|---|---|---|---|---|---|---|
| Website logo - MozFest Sponsor Page | - | Yes | Yes | Yes | Yes | - |
| Logo in motion graphic video | - | Yes | Yes | Yes | Yes | - |

Would you also be able to quickly design a slide template for Science Fair and the main stage (D&D) that has whatever branding we're using for those two events. This is totally optional if you have time. 

## Print

| Asset | Dimensions | Presenting Festival Partner | Science Fair Partner | Youth Zone Partner | Closing Party Partner | Qty (tentative) |
|---|---|---|---|---|---|---|
| Logo in Festival guide on sponsor page | - | Yes | Yes | Yes | Yes | - |
| Logo in Festival guide on last page | - | Yes | - | - | - | - |
| Sponsorship Banner | 2ft wide x 7.1ft tall | Yes | Yes | Yes | Yes | x2 |
| Science Fair sign (poster) | A2 | Yes | Yes | - | - | x10 |
| MozFest Party sign (poster) | A2 | Yes | - | - | - | x10 |
| Networking Breakfast sign (poster) | A2 | Yes | - | - | - | x10 |
| Closing Party sign (poster) | A2 | Yes | - | - | Yes | x10 |
| Youth Zone sign (poster) | A2 | Yes | - | Yes | - | x5 |
| Science Fair Food/bar station (poster) | A2 | Yes | Yes | - | - | x10 |
| Closing Party Food/bar station (poster) | A2 | Yes | - | - | Yes | x10 |
| Generic Food/bar station (poster) | A2 | Yes | - | - | - | x10 |
| Step and repeat - with MozFest and Mozilla Logos as well | 227cm x 227cm x 30cm  | Yes | - | - | - | x1 |
| MozFest House floor display | - | Yes | - | - | - | x5 |
| General use floor display | - | Yes | - | - | - | x10 |
| Floor sticker for lobby | large | Yes | - | - | - | x2 |
| Floor sticker for closing party | large | - | - | - | Yes | x1 |
| Registration table (foamex posters) | A2/A3 | Yes | - | - | - | x4 |
| Volunteer T-shirt sleeves | - | Yes | - | - | - | - |

**Comment by gideonthomas** [comment]
@Saallen can you review copy template for the following signs:

### Event signs (Science Fair, MozFest House, etc.)

\<EVENT NAME\>
Sponsored by
\<PARTNER LOGO and NAME\>
\<PARTNERSHIP TYPE\>


### Food/Bar signs

Food & Drink
Sponsored by
\<PARTNER LOGO and NAME\>
\<PARTNERSHIP TYPE\>


Also, Sabrina mentioned that we can't really put stuff up on walls at RSA, so I changed the MozFest House event signs to be floor displays instead.

**Comment by Saallen** [comment]
Looks great

**Comment by Saallen** [comment]
@gideonthomas your step and repeat is wrong- its only the presenting partner here- not Sf

**Comment by gideonthomas** [comment]
Oh nice catch, thanks!
