### ISSUE TITLE
Dialogues & Debates: Speaker Photos

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#76]
### Description 
We have a few design assets (print & digital) that includes the faces of the Dialogues and Debates speakers. Provide hi-res photos of each speaker to be included. This list of assets include: printed festival guide, poster, gslide template, video motion graphic, social media graphics & website

https://github.com/MozillaFoundation/mozfest-design-2018/issues?q=is%3Aopen+is%3Aissue+label%3AD%26D

**Comment by KevZawacki** [comment]
Hi @sabrinang, you can find all speaker headshots [here](https://drive.google.com/drive/folders/1uz7gEXQOSy8JaQc-BUQjuNJ1p_FlHWza). 

Some are no hi-res... working on getting better ones.
