### ISSUE TITLE
Art + Data: Artist's Photos

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#77]
### Description
We have a few design assets (print & digital) that included the faces of the Artist Open Studios artists previously and assuming it would be similar for Art + Data this year. Provide hi-res photos of each artist and any images of their work to be included. 

This list of assets include: printed festival guide spread & video motion graphic. If we have the capacity we may include it on more digital platforms (example: social)

### Reference from last year
Festival guide spread: https://issuu.com/mozfest/docs/mozfest_2017_festival_guide/8
<img width="810" alt="image" src="https://user-images.githubusercontent.com/2492510/43809388-c23d8044-9a66-11e8-9490-4c133c7dec3b.png">

video motion graphic: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0S1BRZ25KTllHanc
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/2492510/43809518-65ca2398-9a67-11e8-9877-1a3c194d4340.png">

**Comment by gideonthomas** [comment]
@Saallen to assign to someone who will be responsible for taking a look at this issue and determining copy/assets as well as gathering them and providing them here. @Saallen to provide a deadline for this.

**Comment by Saallen** [comment]
I pinged the team one more time- If i dont hear from them by Tuesday lets leave them out

**Comment by Saallen** [comment]
Confirmed we will not be promoting individual artists @sabrinang.

**Comment by sabrinang** [comment]
Great thanks for confirming. We will not be collecting artist's photos - closing issue.
