### ISSUE TITLE
Social: Update Open Graph Image (og:image)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#78]
Update the site thumbnail image https://mozillafestival.org/assets/images/site-thumbnail.jpg. Update to current visual branding with Zilla Slab highlight lockup as the old image is in Fira Sans:

![](https://slack-redir.net/link?url=https%3A%2F%2Fmozillafestival.org%2Fassets%2Fimages%2Fsite-thumbnail.jpg)

**Comment by sabrinang** [comment]
Updated to the current zilla slab highlight lockup on crowd image for the og:image thumbnail:
![mozilla-festival_open-graph-thumbnail](https://user-images.githubusercontent.com/2492510/45657586-dc191d80-ba9f-11e8-8ed3-c01563ebb9e4.jpg)

https://drive.google.com/drive/u/1/folders/1qe4TSfRBEDOL8UXVy2Bs5L3mZAeiQFtO

/cc @gideonthomas

**Comment by zee-moz** [comment]
@sabrinang @gideonthomas this looks great-- let's get it out there. Who can implement?

**Comment by gideonthomas** [comment]
I can assign it to dev. Filed: https://github.com/mozilla/mozillafestival.org/issues/1110
