### ISSUE TITLE
Logo for Firefox Snippet

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#80]
Export the MozFest cog logo to be used on the FireFox Snippet (the banner along the bottom when you launch the browser).

**Comment by sabrinang** [comment]
@marcwalsh I iterated on some snippet icons and I'd suggest the lime-green/blue and/or purple since they stand out on a small scale and you can review:
<img width="2029" alt="mozilla-festival-2018_snippet-icon_overview 2x" src="https://user-images.githubusercontent.com/2492510/45340525-c8276600-b54b-11e8-9f66-d27021adc885.png">

Please use SVG file if you do not know the dimensions. You can find the SVG and PNG folder here: https://drive.google.com/open?id=1nJLVyszq6Zj7rSZPG1t_Ci7U7Rl_gFYg

@gideonthomas Marc mentioned we are submitting this soon last week but I am unsure of this asset deadline.

**Comment by gideonthomas** [comment]
@marcwalsh when would you need this ready by? Does the google drive link that @sabrinang shared have everything you need for the snippet (I assume you're responsible for handling the communication with MoCo re: the snippet)?

**Comment by marcwalsh** [comment]
Hey @gideonthomas and @sabrinang!

I'm working with @KGorr on this, but these will work just fine for us. If we need to submit exact sizes I'm happy to do that myself :)

Thanks both 👍
