### ISSUE TITLE
Sponsorship: Posters

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2018#84]
**Description:**
We would need some posters for the Presenting Festival Partner at MozFest. This can be the same design framed with MozFest 2018 branding and Presenting Festival Partner text with sponsor logo.

**Quantity:** 6 Total
- 4 behind Registration Table Area near entrance (welcome) sign
- 2 more just in case they are needed

**Format:**
On a rigid media - Cardboard or Foamex
https://www.pixartprinting.co.uk/wide-format/printing-flat-bed-rigid-materials/

These signs should be the same size and format as our Participation Guidelines https://github.com/MozillaFoundation/mozfest-design-2018/issues/56 and Photo/Video Consent posters https://github.com/MozillaFoundation/mozfest-design-2018/issues/55 so we can arrange with them.

**Related Issues:**
https://github.com/MozillaFoundation/mozfest-design-2018/issues/75#issuecomment-423204346

**Comment by Saallen** [comment]
Requesting we print 12

4 x rego
plus posters for different events and MozFest house

**Comment by gideonthomas** [comment]
@Saallen just confirming based on what we discussed...we only need 4 foamex posters with just the presenting partner to put behind the registration table right? The other "posters" will be on regular paper and printed at Ravensbourne?

**Comment by Saallen** [comment]
Yes that is correct

**Comment by gideonthomas** [comment]
Sponsorship Update: based on https://github.com/MozillaFoundation/mozfest-design-2018/issues/75#issuecomment-424507958

x4 foamex behind Registration Table Area near entrance (welcome) sign with the Presenting Festival Partner

**Comment by sabrinang** [comment]
I made the presenting festival partner signage on a 59.4cm x 59.4cm custom rigid media template to match the height of A2 posters (photo/video, participation guidelines) near registration.

![image](https://user-images.githubusercontent.com/2492510/46771947-8c96cd80-ccaa-11e8-9a32-4a74a77d8d76.png)


@Saallen Please review on redpen here: https://redpen.io/de6b97603e8b1dfcb0

Print PDF here: https://drive.google.com/drive/u/1/folders/1LwFaiDRQmNmlhR1C5US8Od9udS3I_9ew

**Comment by gideonthomas** [comment]
@jcbarajas would you be able to review this set of posters? This will show up behind the registration desk on hard cardboard. Link to poster - https://redpen.io/de6b97603e8b1dfcb0

**Comment by gideonthomas** [comment]
Juan approved via slack.

**Comment by marcwalsh** [comment]
Sent to print! ⛸

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The squared sponsorship signs were placed in between the participation guidelines and privacy alert posters on the mesh grate behind registration. I think we ended up using white tac to adhere them on (double sided tape didn’t work and the metal loops that came with it wouldn’t stay on).

![dsc02585](https://user-images.githubusercontent.com/2492510/48652609-3dcd0980-e9b5-11e8-8512-e349344042d9.jpg)
![img_6072](https://user-images.githubusercontent.com/2492510/48652601-2e4dc080-e9b5-11e8-99f6-d0a093f42f49.JPG)
