### ISSUE TITLE
Sponsorship: Event Entrance and Food/Bar Posters

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2018#86]
**Description:**
We would need posters for each event and the food/bar station to post outside their entrance (and possibly inside the event) that mentions the sponsors for that event or the food station. It can be the same design framed with MozFest 2018 branding and depending on the event - the corresponding sponsor logo(s).

The copy if it is an event will be:
EVENT NAME
Sponsored by
PARTNER LOGO(S) and NAME(S)
PARTNERSHIP TYPE

The copy if it is for the food/drink station will be:
Food & Drink
Sponsored by
PARTNER LOGO(S) and NAME(S)
PARTNERSHIP TYPE

**Quantity:** 75 Total
- 10 (event) for the Science Fair with the presenting festival partner and science fair partner
- 10 (event) for the MozFest Party with the presenting festival partner
- 10 (event) for the Networking Breakfast with the presenting festival partner
- 10 (event) for the Closing Party with the presenting festival partner and closing party partner
- 5 (event) for Youth Zone with the presenting festival partner and the youth zone partner
- 10 (food/bar) for the Science Fair with the presenting festival partner and the science fair partner
- 10 (food/bar) for the Closing Party with the presenting festival partner and the closing party partner
- 10 (food/bar) for the weekend with the presenting festival partner

**Format:**
On A2 size paper similar to the ones we use for D&D

**Related Issues:**
https://github.com/MozillaFoundation/mozfest-design-2018/issues/75#issuecomment-424507958

cc @sabrinang

**Comment by sabrinang** [comment]
@Saallen I designed the eight A2 posters in a set of blue or light versions for you to review which set you'd like to use. Note that Networking Breakfast is MozFest Breakfast in the festival guide so it is also changed here to align. 

Please review on redpen here: https://redpen.io/p/ue4d1b9684af817765

I have exported the files with trim marks and a 1cm bleed as it wasn't indicated how much bleed is needed. Print PDF files on gdrive here: https://drive.google.com/drive/u/1/folders/1JmRC1l4f7b-so4sx_eFMw-FrJPo8ByEr

<img width="790" alt="image" src="https://user-images.githubusercontent.com/2492510/46767854-32424080-cc9b-11e8-92f1-f0ec165e9501.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/2492510/46767863-379f8b00-cc9b-11e8-9817-fcea96aa7d7b.png">

/cc @gideonthomas

**Comment by sabrinang** [comment]
Update: We probably should go for the light set since I don't know all the brand guidelines for each logo but for example stickermule's includes:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/2492510/46770514-974e6400-cca4-11e8-949a-d5232748df11.png">
... so I don't think it can be on blue bg in the blue set

**Comment by gideonthomas** [comment]
@jcbarajas would you be able to review the event entrance sign posters and the food/bar posters - https://drive.google.com/file/d/1K9ITUohh3m3U2-ErwzLzA8gTUAQELx_X/view?usp=sharing

**Comment by gideonthomas** [comment]
Juan approved via slack!

**Comment by Saallen** [comment]
look great @sabrinang  thanks

**Comment by sabrinang** [comment]
## Post MozFest Documentation

These were put up during the corresponding sponsored events and food/bar stations. For next year, we can document a guideline so the poster locations and positions can be more consistent throughout the festival? @gideonthomas may have more details/suggestions.
 
![20180928-mozfest-sunday-115](https://user-images.githubusercontent.com/2492510/48652797-38bc8a00-e9b6-11e8-860e-e81f4b97cb3e.jpg)
![20180928-mozfest-sunday-116](https://user-images.githubusercontent.com/2492510/48652798-38bc8a00-e9b6-11e8-9338-c716d9c0c428.jpg)
![dsc02301](https://user-images.githubusercontent.com/2492510/48734287-e23f8d80-ebf9-11e8-9050-c416943b27b8.jpg)
![img_5898](https://user-images.githubusercontent.com/2492510/48734353-0ac78780-ebfa-11e8-85d4-7ad055b2ded9.JPG)
![dsc02442](https://user-images.githubusercontent.com/2492510/48734399-2d59a080-ebfa-11e8-9982-7429e0cd285e.jpg)
![dsc02296](https://user-images.githubusercontent.com/2492510/48734434-3fd3da00-ebfa-11e8-8609-5264f6b4d87e.jpg)
![dsc02278](https://user-images.githubusercontent.com/2492510/48734451-4b270580-ebfa-11e8-80e9-ec8a45e61d50.jpg)
![dsc02498](https://user-images.githubusercontent.com/2492510/48734376-203cb180-ebfa-11e8-88f8-ff25634da9a6.jpg)

**Comment by gideonthomas** [comment]
These were technically supposed to be entrance signs but it was hard to use them as such. My suggestion would be to either do a larger banner, or A1 size floor displays. For food/bar probably need an A3 size poster with a stand so that they can be put on the tables instead.
