### ISSUE TITLE
Location numbers- 

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mozfest-design-2018#87]
As per @mmmavis locations for guidebook the following "studios/rooms/locations for sessions are listed

Level 1 - 101
Level 1 - 102
Level 2 - 205
Level 2 - 206
Level 2 - 207
Level 2 - 208
Level 2 - 209
Level 2 - 210
Level 2 - 211
Level 2 - 212
Level 2 - 213
Level 4 - Big Space
Level 4 - Study Zone
Level 6 - 601
Level 6 - 602
Level 6 - 603
Level 6 - 604
Level 6 - 605
Level 6 - 606
Level 6 - 607
Level 7 - 702
Level 7 - 703
Level 7 - 706
Level 7 - 707
Level 7 - 708
Level 8 - 801
Level 8 - The Board Room
Level 8 - 804
Level 8 - 805
Level 8 - 806
Level 9 - 902
Level 9 - 903
Level 9 - Prototyping Lab
Level 9 - 905
Level 9 - 906
Level 9 - 907

Missing from mavis's location lists are 
203 

@sabrinang  I reviewed the new floor maps from raves and there are some missing location numbers that were on the maps last year but not this year. We will still want to program these and so highlighting for your designed maps
Level 1 - 101
Level 1 - 102
902 
703 and 702 

Missing from both maps and mavis locations are locations numbers within library- 
Can we make some up and add them into our resources ?? I added some ideas to this map
[scan.pdf](https://github.com/MozillaFoundation/mozfest-design-2018/files/2424559/scan.pdf)

cc @gideonthomas

**Comment by mmmavis** [comment]
@Saallen is `Level 2 - 203` in this year's list?

**Comment by Saallen** [comment]
Yes please

**Comment by sabrinang** [comment]
@makikoumezawa reference for your floor maps
