### ISSUE TITLE
Swag: master 

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mozfest-design-2018#90]
Here is a list of Swag which will be given as gifts at MozFest for @sabrinang, @marcwalsh  and @gideonthomas. @Rowestephanie1 will be coordinating this work

- [ ] Water bottle #89
- [ ] Bag #91 
- [ ] Notebook #92 
- [ ] Baseball cap TBC
- [ ] Woolly Hat TBC

**Comment by gideonthomas** [comment]
@Saallen and @rowestephanie1, please create the cap/hat tickets with print area dimensions and a link.

**Comment by rowestephanie1** [comment]
@gideonthomas @Saallen @sabrinang will create these today.

**Comment by gideonthomas** [comment]
@rowestephanie1 just a quick reminder about the cap/hat tickets.

**Comment by rowestephanie1** [comment]
@gideonthomas thanks for your patience with this. I will be sharing these today.

**Comment by rowestephanie1** [comment]
@gideonthomas @Saallen @Saallen Thanks all. This is all complete now.
