### ISSUE TITLE
Swag: Bag

### ISSUE THREAD

**Issue by rowestephanie1** [MozillaFoundation/mozfest-design-2018#91]
Please can we have a design for these bags http://www.pgbranding.com/scubadoo-119686.html 

<img width="329" alt="screen shot 2018-09-28 at 17 45 53" src="https://user-images.githubusercontent.com/43207831/46221804-5ff7c300-c346-11e8-9e15-c9452b589711.png">

Item comes in Blue, Red, Yellow and Black
How much would you like of each colour? Maximum total quantity 1600.

Print area is 100x200mm

Our budget would prefer a 1 colour print logo, however, we can also put a full colour logo on this.

This is the most urgent of our swag items. Deadline ideally 3rd October please.

For @sabrinang , @marcwalsh and @gideonthomas

**Comment by sabrinang** [comment]
Let's go with black, blue and yellow bags.
Quantity: 800 black; 400 blue; 400 yellow
Logo size: 45mmx45mm
1 colour print logo (white) SVG: https://drive.google.com/file/d/12BvM-NfAbrzcWyBR4qg7At4nN0OCdr6S/view?usp=sharing

Please position as seen on redpen here: https://redpen.io/rzee78a8a388bbc204
![mozilla-festival-2018_bag-design 2x](https://user-images.githubusercontent.com/2492510/46304475-a2e2b200-c563-11e8-8c9f-509bf27f7579.jpg)

@rowestephanie1 @Saallen Please review.
/cc @gideonthomas

**Comment by rowestephanie1** [comment]
@sabrina please can you send the exact colour and size of logo to use as a EPS Vector or High Res PDF?
The supplier doesn't use google drive or redpen so needs to have a word document or such. I am happy to screed shot the image above and share?

**Comment by rowestephanie1** [comment]
@sabrinang these look fantastic by the way

**Comment by sabrinang** [comment]
@rowestephanie1 The exact colour of the logo is white (HEX (#FFFFFF) RGB (255,255,255) CMYK (0,0,0,0)) and size is 4.5x4.5cm and you can download EPS PDF or SVG file of the logo for this bag on google drive here: https://drive.google.com/open?id=13ql-hwz2UcyCk30P--ZI2wlA-pujp7pP

or you can give your supplier this link to download as ZIP as an attachment here: 
[Mozilla-Festival-Logo_Bag-Design.zip](https://github.com/MozillaFoundation/mozfest-design-2018/files/2439024/Mozilla-Festival-Logo_Bag-Design.zip)

Yes, please save the image above and forward it to the supplier for reference of placement.

**Comment by rowestephanie1** [comment]
@sabrinang @gideonthomas Thank you for these. I am just waiting on confirmation from our suppliers... placed order with them but they are out of office at a event today.
Will update when order has been fully processed.

**Comment by rowestephanie1** [comment]
@sabrinang  @gideonthomas thanks for the efforts on this. These are now ordered. Closing tickets!
