### ISSUE TITLE
Swag: A6 Notebook

### ISSUE THREAD

**Issue by rowestephanie1** [MozillaFoundation/mozfest-design-2018#92]
Please can we have a full cover (four-colour digital printing) design for this item. The INSTRUCTIONS and TEMPLATE for creating the designed cover can be found on this web page when you scroll down. https://www.pixartprinting.co.uk/digital-litho-printing/office-products/customised-notebook/ 
<img width="345" alt="screen shot 2018-09-28 at 17 49 25" src="https://user-images.githubusercontent.com/43207831/46221989-deecfb80-c346-11e8-9694-74936d4a07c5.png">

Thread colour: yellow, green, red, black, blue pearl grey. See in image below. This one has green thread.
<img width="783" alt="screen shot 2018-09-28 at 17 48 36" src="https://user-images.githubusercontent.com/43207831/46221940-c0870000-c346-11e8-86d5-f3e35eb7bf48.png">

Quantity: 1,600

Book size: 10.8 x 14.8 cm 

For @sabrinang , @marcwalsh and @gideonthomas

**Comment by rowestephanie1** [comment]
@sabrinang @makikoumezawa @gideonthomas Just wondered how we are progressing with this one? I need to order this week latest. 
We can also have a variety of designs if you wish at no extra costs. I would suggest no more than 3 different designs. We have to place the order in batches of 500.
500 = design 1
500 = design 2
500 = design 3
100 = design 3

**Comment by rowestephanie1** [comment]
@sabrinang just to update you can also create an array of designs. we can order in batches of no more than 500. So for example;
500 = design 1
500 = design 2
500 = design 3
100 = design 3
I need to place this order imminently please.

**Comment by gideonthomas** [comment]
Hi @rowestephanie1 this should be done by end-of-day today.

**Comment by gideonthomas** [comment]
@makikoumezawa any updates on this?

**Comment by makikoumezawa** [comment]
@rowestephanie1 Here is the pdf for the Notebook cover: https://drive.google.com/open?id=16Lj9fgZ3o7bnuRPK0B2SCbKiizzTASqe

There are 4 covers that have different color iterations. Below are the specifications for each cover.

**1. Navy Blue Shade:** 500 w/ Blue thread
**2. Light Blue Shade:** 500 w/ Blue thread
**3. Black and White Shade:** 500 w/ Black thread
**4. Blue with Green Blocks:** 100 w/ Green thread


/cc @sabrinang @gideonthomas

**Comment by rowestephanie1** [comment]
@makikoumezawa @gideonthomas @sabrinang  very much appreciated... 
Please can you send through each design and specifications as separate pdfs please. They require each design to be uploaded separately.

**Comment by rowestephanie1** [comment]
@gideonthomas @makikoumezawa apologies for chasing but this really needs to get sent to print. I require the four different designs to be sent across as separate PDFs asap please.

**Comment by makikoumezawa** [comment]
@rowestephanie1 my apologies for not replying earlier. Here are the separate pdfs:

**1. Navy Blue Shade: 500 w/ Blue thread:** https://drive.google.com/open?id=1VJnPyPi2HIVbM9MuOAJEqfzVNlTT-eDO

**2. Light Blue Shade: 500 w/ Blue thread:** https://drive.google.com/open?id=1OiRK8GBEDNI3Bb4FDKf_EfnJ6-sofrQc

**3. Black and White Shade: 500 w/ Black thread:** https://drive.google.com/open?id=1qxIwWVrTwYmEit5xgcJLSN0c1vjoAaDq

**4. Blue with Green Blocks: 100 w/ Green thread:** https://drive.google.com/open?id=1C7DAe8Tjgfn07M3D1fk6bCmFRdfFrfkW

/cc @gideonthomas @sabrinang

**Comment by rowestephanie1** [comment]
@makikoumezawa Thank you very much for sharing these!

**Comment by rowestephanie1** [comment]
@gideonthomas @sabrinang @makikoumezawa These have been ordered. Thanks fro your assistance with the great designs!

**Comment by gideonthomas** [comment]
Thanks @rowestephanie1!
