### ISSUE TITLE
Swag: Festival Map

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2018#93]
Separated from #73 to keep that issue only about the festival guide

**Deadline** - October 18

### **Printing Concept Specifications (Map 2018)**

![screen shot 2018-09-13 at 3 36 38 pm](https://user-images.githubusercontent.com/41972873/45521271-1ddd5780-b772-11e8-8b06-f7b9fb6c2d2c.png)

Folded Map (Same size as notebook)
- **Folded Size:** A6 105 x 148 mm (4.13 × 5.83 in)
- **Unfolded Size:** A3 297 x 420 mm (11.69 x 16.53 in)
- **Printing Method:** Litho-printing on recycling paper? (if possible)
- **Paper Stock:** 120 gsm (same weight as main pages and not too flimsy when folded)

![printing_concept_specifications__festival_guide_2018__-_google_docs](https://user-images.githubusercontent.com/41972873/45522180-4cf5c800-b776-11e8-9c77-532b86e75ca5.png)

### Folding Instructions

![screen shot 2018-09-21 at 1 00 38 pm](https://user-images.githubusercontent.com/41972873/45903527-de7cbf80-bd9e-11e8-86e4-e39556965dd4.png)

Use an A3 (297 x 420 mm) paper size sectioned into an 8-page fold.

1. Start with an accordion fold with the front cover and back cover panel. Each panel will be 105 mm wide sectioned to 4 panels. 

2. Fold in behind from half point

3. Map will be folded into an A6 size (148 x 105 mm) 

cc @sabrinang, @marcwalsh

**Comment by sabrinang** [comment]
@makikoumezawa https://drive.google.com/open?id=1iMErQt_P7QJStHZiHipELgYR4P_7TcB3

**Comment by marcwalsh** [comment]
@gideonthomas - Just confirming that I'll need to send to print AM of Friday (UK Time) - the printers contacted me today and that is the latest it will work to get everything pre-folded.

**Comment by gideonthomas** [comment]
Perfect, thanks! @makikoumezawa are you able to make the current deadline of Thursday the 18th?

**Comment by makikoumezawa** [comment]
@gideonthomas Here is the pdf file: https://drive.google.com/open?id=1bGa65tUm1zSBT6PKA392IB52zgD9Qyzz

Could you review before being printed?

Redpen: https://redpen.io/p/szc2c715d43b11a28f

/cc @sabrinang @Saallen

**Comment by Saallen** [comment]
Looks great- approved for print

**Comment by gideonthomas** [comment]
Fix 1 (add 's' to Participation Guideline): https://drive.google.com/file/d/1YQxEjI0bBggRW5ciywm3GU8iRvPqAU_o/view?usp=sharing

Fix 2 (add trim and bleed marks): https://drive.google.com/file/d/126UeiAsTjjyMPqwdsH9vOwbPpJo99USY/view?usp=sharing

**Comment by marcwalsh** [comment]
Sent to print... Thanks for the quick fix on the S and trim lines!! 🛠
