### ISSUE TITLE
Swag: Festival Guide MozFest House Insert

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2018#94]
Separated from #73 to keep that ticket only about the festival guide

**Deadline** - October 11

### Content

https://docs.google.com/document/d/1_U-psv7RO6BaRpu3s58L1iDivh3pH5lgzVKZAUw7Fbc/edit#

### **Printing Concept Specifications (Mozfest House Insert 2018)**

![screen shot 2018-09-13 at 3 36 38 pm](https://user-images.githubusercontent.com/41972873/45521271-1ddd5780-b772-11e8-8b06-f7b9fb6c2d2c.png)

**Quantity:** 300

**Print Type:** [Pixart Small Custom Format prints](
https://www.pixartprinting.co.uk/digital-litho-printing/printing-other-formats/) 

**Paper Stock:** 300GSM recycled card

**Sizes:** Booklet Guide or Single Page Postcard Insert
- **Booklet Guide Size:** 117 x 200 mm (4.6 x 7.9 in) 
- **Single Page Postcard Size:** A6 105 x 148 mm (4.13 × 5.83 in)

**Template:** [A6 template](https://github.com/MozillaFoundation/mozfest-design-2018/files/2416111/pixartprinting-template-small-format-custom-formats.pdf)

**Instruction sheet:** [instruction sheet here](https://github.com/MozillaFoundation/mozfest-design-2018/files/2416097/instruction_172_en.pdf) since there aren't templates for custom sizes

cc @sabrinang and @marcwalsh

**Comment by makikoumezawa** [comment]
@Saallen Please review the MozFest House insert. Here is the pdf version: https://drive.google.com/open?id=1Jjp4BQsqS36mbFAsdG04Xc7MLmBxGxha

If you have any comments, please comment on the google docs: https://docs.google.com/presentation/d/14aDPsr3HcrmV9BF70le_oyvvAeI6_wlVeuSO9ZloGr4/edit?usp=sharing

/cc @gideonthomas @sabrinang

**Comment by Saallen** [comment]
Hey @makikoumezawa - I added comments to the slide deck

**Comment by makikoumezawa** [comment]
@Saallen Completed the MozFest House Insert. I've changed the time slots to the 24 hour time to stay consistent with the Festival Guide and also added the new events you've listed. 

Here is the pdf version: https://drive.google.com/open?id=1Jjp4BQsqS36mbFAsdG04Xc7MLmBxGxha

Google slides:
https://docs.google.com/presentation/d/14aDPsr3HcrmV9BF70le_oyvvAeI6_wlVeuSO9ZloGr4/edit?usp=sharing

/cc @sabrinang @gideonthomas

**Comment by gideonthomas** [comment]
@makikoumezawa there are a few more comments in the presentation. Let me know when you address them.

**Comment by makikoumezawa** [comment]
@gideonthomas  I've resolved Sabrina's comments. The pdf link is a revised version.

**Comment by gideonthomas** [comment]
Perfect! Thanks @makikoumezawa! @Saallen would you be able to take a quick final look?

**Comment by Saallen** [comment]
@makikoumezawa One amendment to a Thursday event-but marc amended.
Otherwise looks great and GONE TO PRINT 🎆

**Comment by marcwalsh** [comment]
Attached is the ammended artwork and placed into spreads for print.

[New Artwork](https://github.com/MozillaFoundation/mozfest-design-2018/files/2483769/mozfesthouseinsert.pdf)

**Comment by sabrinang** [comment]
## Post MozFest Documentation

This was printed on a semi-gloss card stock and was inserted in the back of the guide or used as a standalone guide throughout MozFest House:
![31777783058_cb7701e189_z](https://user-images.githubusercontent.com/2492510/48282852-b65d2480-e40f-11e8-96a2-34468ff36ff8.jpg)
![44925184024_ef7c1d8d33_z](https://user-images.githubusercontent.com/2492510/48282854-b65d2480-e40f-11e8-81de-e3b352b7ba7c.jpg)
![dsc02221](https://user-images.githubusercontent.com/2492510/48282866-bceb9c00-e40f-11e8-83cb-995a88bf5087.jpg)
