### ISSUE TITLE
Swag: Festival Guide Facilitators Insert

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2018#96]
Separated from #73 to keep that ticket only about the festival guide

**Deadline** - October 18

### **Printing Concept Specifications (Facilitators Insert 2018)**

![screen shot 2018-09-13 at 3 36 38 pm](https://user-images.githubusercontent.com/41972873/45521271-1ddd5780-b772-11e8-8b06-f7b9fb6c2d2c.png)

**Quantity:** 2600

**Print Type:** [Pixart Small Custom Format prints](
https://www.pixartprinting.co.uk/digital-litho-printing/printing-other-formats/) 

**Paper Stock:** 300GSM recycled card

**Sizes:** Single Page Postcard Insert (Large or Small)
- **Single Page Postcard Maximum Size:** 117 x 174 mm
- **Single Page Postcard Minimum Size:** A6 105 x 148 mm (4.13 × 5.83 in)

**Template:** [A6 template](https://github.com/MozillaFoundation/mozfest-design-2018/files/2416111/pixartprinting-template-small-format-custom-formats.pdf)

**Instruction sheet:** [instruction sheet here](https://github.com/MozillaFoundation/mozfest-design-2018/files/2416097/instruction_172_en.pdf) since there aren't templates for custom sizes

cc @sabrinang and @marcwalsh

**Comment by gideonthomas** [comment]
@Saallen can we cut this, it seems like a lot of work considering deadlines (and the fact that we don't have content for this yet)?

**Comment by Saallen** [comment]
Yes- closing issue
