### ISSUE TITLE
Swag - Caps

### ISSUE THREAD

**Issue by rowestephanie1** [MozillaFoundation/mozfest-design-2018#97]
@sabrinang @gideonthomas 
Please find a link for branded caps below.
https://www.xamax.co.uk/result-core-memphis-6-panel-brushed-cotton-low-profile-cap.html
What colour would we like for our caps? We can have an array. We don't plan on ordering more than 800-1000 of these as we want some woolly hats too.
We can have up to a 7000 stitch embroidered for this...
Logo size no bigger than 5cmx5cm

**Comment by rowestephanie1** [comment]
@gideonthomas @sabrinang how are we getting on with designs for this item please?

**Comment by gideonthomas** [comment]
@rowestephanie1 should be ready by EOD today based on the deadline labelled above.

**Comment by sabrinang** [comment]
I'm not sure how many colours you need but these caps can be in:
* black
* navy blue
* azure
* purple

For the logo size, the gear logo can be 4cm in diameter. It can be 2cm above the brim seam.

![mozilla-festival-2018_swag-cap-examples](https://user-images.githubusercontent.com/2492510/46651586-5eec4000-cb55-11e8-8ae3-be8a6521bcfc.png)

4cm gear logo SVG/EPS/PDF file on gdrive here: https://drive.google.com/open?id=1IC9L0V07_b5AT2aBD1LMiei3zQneA5iS

**Comment by rowestephanie1** [comment]
@gideonthomas @sabrinang Thank you for providing.

**Comment by rowestephanie1** [comment]
@gideonthomas @sabrinang - Thanks for the efforts on this... We are going with woolly hats solely. Closing ticket.
