### ISSUE TITLE
Swag - Woolly Hats

### ISSUE THREAD

**Issue by rowestephanie1** [MozillaFoundation/mozfest-design-2018#98]
@sabrinang @Saallen @gideonthomas  
Please find a link for woolly hats below
https://www.arcadiaonline.co.uk/product-10738-beechfield-cuffed-beanie.aspx#title

What colour would we like for our woolly hats? (It doesn't specify all the colours available, just says 60 different colours so feel free to suggest and I can request.)

We can have embroidery logo up to 5000 stitches.

Print size is up to us to decide. See examples below.
https://mail.google.com/mail/u/0/?ui=2&ik=1183dfdfd8&view=att&th=166400be9650cd9f&attid=0.1&disp=safe&z
https://mail.google.com/mail/u/0/?ui=2&ik=1183dfdfd8&view=att&th=166400be9650cd9f&attid=0.2&disp=safe&zww

**Comment by gideonthomas** [comment]
Hi @rowestephanie1 would you be able to link the examples separately? We can't view them since those links are email links.

**Comment by rowestephanie1** [comment]
@gideonthomas @sabrinang  
Please see an example below.
<img width="350" alt="screen shot 2018-10-04 at 22 02 05" src="https://user-images.githubusercontent.com/43207831/46502981-6c39bf80-c821-11e8-9a84-e75cb7133f2e.png">

**Comment by rowestephanie1** [comment]
@gideonthomas @sabrinang how are we getting on with designs for this item please?

**Comment by sabrinang** [comment]
The site is unclear what colours are available, I am unsure how many you need but these would be the prefered colours:
* black
* antique grey
* heather royal blue
* heather purple 

For the logo size, the gear logo can be 3cm in diameter. There are no dimensions of the hat brim itself so it I’m assuming it is approximately ~2cm from the edges.

![mozilla-festival-2018_swag-touque-examples](https://user-images.githubusercontent.com/2492510/46649986-de771080-cb4f-11e8-80b5-1e6641b9fae7.png)

3cm gear logo SVG/EPS/PDF file on gdrive here: https://drive.google.com/open?id=1Hp0ECAFBdAHtBje4LO2Rzbo8OLexs_CV

@rowestephanie1 Please review.

/cc @gideonthomas

**Comment by rowestephanie1** [comment]
@gideonthomas @sabrinang thank you for sending these designs across... trying to source these colours specifically. Original supplier can't provide the purple. Will be completed with way today.

**Comment by gideonthomas** [comment]
Thanks @rowestephanie1!
