### ISSUE TITLE
Design support for Science Fair Slides

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mozfest-design-2018#99]
Required --Slides created for Science Fair mini nets at Ravensbourne- Friday 26th Oct
cc @xmatthewx to allocate design support
cc @rowestephanie1 for logos and content support

Below are numbers representing different slides sharing content requested on each slide

1. Welcome to Science Fair
2. Thank you to our following sponsors for supporting Mozfest 2018
3. Our presenting partner Private Internet Access
4. Our  Science fair partner Internet Society
5. Sticker mule and Samsung
6. Science Fair takes place over level 4 and 6 with 15 demos on each floor
7. Be sure to visit these great demos by..
8.  ...next slides contains the logos,- 4 to a page
https://docs.google.com/spreadsheets/d/1M00nfZXc-Z651_UIKxsJa8ulITHcph6Ff7SGYunRyYQ/edit#gid=0

**Comment by natalieworth** [comment]
@Saallen For point 8, do you want just the logo on each slide, or also some content/ name/ maybe the description of each?

**Comment by natalieworth** [comment]
Have gotten a start on [this deck here](https://docs.google.com/presentation/d/1DnL7AhbnMiSwaTOxxCmKDmBJFV1F9SMfgYZAMeo3XUs/edit?usp=sharing) for the Science Fair. 

cc @Saallen @gideonthomas and @sabrinang if you could do a brand check too before I get too far along.

**Comment by gideonthomas** [comment]
@Saallen confirming based on our previous sponsor decisions -- we aren't including the Closing and Youth Zone Partner in the Science Fair slides right?

**Comment by sabrinang** [comment]
@natalieworth looking good! For the sponsorship slides 2-5 can you match the style of the banner https://github.com/MozillaFoundation/mozfest-design-2018/issues/49#issuecomment-429419477 ?

**Comment by Saallen** [comment]
@gideonthomas Emmmmm, I was thanking them for their overall support but if you think this is a little off brand then fine to remove. Can you review for sense check too @gideonthomas

**Comment by Saallen** [comment]
Oh @natalieworth looking great thanks

**Comment by gideonthomas** [comment]
my suggestion would be to amend the sponsor copy to be "Thank you to our following sponsors for supporting the MozFest 2018 Science Fair" and only including Private internet access and internet society.

**Comment by natalieworth** [comment]
@Saallen So not all of the logos were in the doc file (I think there are only about 6). I ended up just including a type-based/ info about each demo on the last 4 slides, and included a logo slide at the very end in case it was important to show them? https://docs.google.com/presentation/d/1DnL7AhbnMiSwaTOxxCmKDmBJFV1F9SMfgYZAMeo3XUs/edit#slide=id.p

The last organization also didn't provide a demo name or content (Brangerbriz), so I just included the demo name as Brangerbriz—hope that's okay :) 

cc @gideonthomas @sabrinang

**Comment by rowestephanie1** [comment]
@natalieworth all the logo's are in this folder https://drive.google.com/drive/folders/1vWB-5x0ciU1w6fG6HpCLH66M36JYfmQ9?usp=sharing separate to where the detail breakdown is. Brangerbriz have now provided more details also (in the spreadsheet)...

cc @gideonthomas

**Comment by natalieworth** [comment]
Thanks @rowestephanie1 ! [I've now updated the slides. ](https://docs.google.com/presentation/d/1DnL7AhbnMiSwaTOxxCmKDmBJFV1F9SMfgYZAMeo3XUs/edit#slide=id.p)

@Saallen Slide [7-8 has the logos](https://docs.google.com/presentation/d/1DnL7AhbnMiSwaTOxxCmKDmBJFV1F9SMfgYZAMeo3XUs/edit#slide=id.g45125a528a_0_84) and 9-11 have the individual demo info/ name of each. I made 9-11 before getting all the logos, so if that level of detail isn't needed, feel free to delete them.

cc @gideonthomas

**Comment by rowestephanie1** [comment]
@natalieworth thank you for these slides, I have included more demo's and logo's in the document that will need to be added. Perhaps we do a final check off of these on Wednesday?

Can also have this made into a video as that is the format that is required for the venue screens to play. If we confirmed final images and such by Wednesday would Thursday be fine to get it back in a video format or more time would be required? 

cc @Saallen @gideonthomas

**Comment by gideonthomas** [comment]
@rowestephanie1 can you add all those new demos and logos here as a comment on github? It's hard to find what's new in that spreadsheet.

**Comment by rowestephanie1** [comment]
@gideonthomas @natalieworth yeah of course will do so... can we also remove the "d" logo next to dot everyone on slide 7 please?

**Comment by rowestephanie1** [comment]
@gideonthomas @natalieworth was having difficulty adding... see the missing ones detailed below by matching logo name. Is this okay?

Psiphon
Mozilla open leaders
Moss 2
Project Lantern
BB_full_logo
Permanent wider logo
ttc logo
SecFirst
Highlander logo
W3

**Comment by gideonthomas** [comment]
@Saallen does the design itself look fine? We can update with more logos after that.

**Comment by rowestephanie1** [comment]
@natalieworth @gideonthomas Once completed how can we go about this getting this converted to a MP4 or several jpegs please?

**Comment by gideonthomas** [comment]
@rowestephanie1 @natalieworth can do that for you.

**Comment by rowestephanie1** [comment]
@gideonthomas @natalieworth perfect. we will need to update slide 6 with the final number of demo's we may not quite have 30 and the distribution won't be even across the two floors

**Comment by gideonthomas** [comment]
@rowestephanie1 we need to finalize this for tomorrow. We'll be updating the slides tomorrow morning based on the content in the spreadsheet, and we won't be able to make changes after that.

**Comment by rowestephanie1** [comment]
Sorry @natalieworth @gideonthomas I had started writing a comment and got distracted. I have spoken to Sarah she is happy with the look... Some changes to make below please.

Slide 6 I have removed the number 15   
Slide 7 and 8 changed to read "MozFest Science Fair Demos ***By**" - added in by
Slide 7 I removed "D" logo top right - so can be replaced
I have deleted slides 9-11

Please can we add all additional logo's in previous comment and detailed below:
Psiphon
Mozilla open leaders
Moss 2
Project Lantern
BB_full_logo
Permanent wider logo
ttc logo
SecFirst
Highlander logo
W3
OCCRP
Internet Society (again please)

Can we then have this converted into two files please. Both mp4 format and several jpegs please?

**Comment by natalieworth** [comment]
@rowestephanie1 There is a "WebThing" file https://drive.google.com/file/d/0B8G9dgkfPwUVcVN2OVE0UVpoaEQxUlVyRDB4dWxCa19BQnZJ/view?usp=sharing

Should I include that too?

**Comment by natalieworth** [comment]
@rowestephanie1 I think we have W3 twice, is that okay?

**Comment by natalieworth** [comment]
@rowestephanie1 I've added the additional logos to the slides (with the exception of the 'WebThing' by Samsung logo—not sure if we are needing that?

I also added the additional media partner on [slide 5 (sharable).](https://docs.google.com/presentation/d/1DnL7AhbnMiSwaTOxxCmKDmBJFV1F9SMfgYZAMeo3XUs/edit#slide=id.g44623c4d68_0_63)

If it's good to go, I can export and ad images to a video format.

cc @gideonthomas @Saallen

**Comment by rowestephanie1** [comment]
@natalieworth thanks for the update, please can you remove one of the W3 logo's and add the webthing one please - they are paticipating.

cc @Saallen @gideonthomas

**Comment by natalieworth** [comment]
Thanks @rowestephanie1 , I made the [final updates in the slide deck ](https://docs.google.com/presentation/d/1DnL7AhbnMiSwaTOxxCmKDmBJFV1F9SMfgYZAMeo3XUs/edit#slide=id.g45125a528a_0_84)and have also exported the [slides to a video file here](https://drive.google.com/drive/folders/12tYIZUSfWJvH-UjiEx0P3LMCywBAPn76?usp=sharing).

cc @gideonthomas @Saallen @marcwalsh

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The science fair slides were displayed on the large screens by the stage as well as all the mounted hanging screens in the science fair area:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/2492510/48282233-fde2b100-e40d-11e8-8bd4-b0e2c2ce13a9.png">

![dsc02292](https://user-images.githubusercontent.com/2492510/48282290-24a0e780-e40e-11e8-94e1-42c882b22479.jpg)
![dsc02286](https://user-images.githubusercontent.com/2492510/48282236-020ece80-e40e-11e8-882b-c5a3bb8a97b1.jpg)
